### ISSUE TITLE
Datepicker don't bind value to ngModel

### ISSUE THREAD

**Issue by ZeBigDuck** [InfomediaLtd/angular2-materialize#10]
Hi all!

First, thank you for your awesome work!

Datepicker seems to be working, value is reported to input, but I still have no value in my [(ngModel)]="object.date"

Did I miss something ? Thank you for your feedback.

**Comment by rubyboy** [comment]
Thanks for the feedback :)
I may have time tomorrow to take a look. In the meanwhile I'm adding @criticalbh, who might have a better idea than me why this is happening.

**Comment by criticalbh** [comment]
I will take a look. Thanks for reporting.

**Comment by criticalbh** [comment]
-done

**Comment by rubyboy** [comment]
Thanks @criticalbh. Merged https://github.com/InfomediaLtd/angular2-materialize/commit/845b1167cf4253d689faf4227903165394e67618

@ZeBigDuck would you be able to confirm this is fixed?

**Comment by ZeBigDuck** [comment]
Sorry I don't know how to test, it seems that npm registry have not be updated.

**Comment by rubyboy** [comment]
Give it a try again now - I've deployed latest version (1.4.1) to npm.
I've also deployed it to the demo site: http://angular2-materialize.surge.sh

**Comment by ZeBigDuck** [comment]
Ok it works! Thank you very much for this awesome lib guys :+1:

**Comment by rubyboy** [comment]
No worries. Thanks for your feedback!

**Comment by KyDenZ** [comment]
Hello,

I would like to know if it still works? (15.1.8) I try to make it work and it does not work, even by doing a simple copy paste examples it is always undefined.

Thank you

**Comment by rubyboy** [comment]
@KyDenZ yes it does. Look at the sample code: https://github.com/InfomediaLtd/angular2-materialize/blob/master/sample/src/app/components/datepicker.ts
Demo: https://infomedialtd.github.io/angular2-materialize/#/DatePicker
