### ISSUE TITLE
EXCEPTION: Uncaught (in promise): TypeError: $(...).materialbox is not a function

### ISSUE THREAD

**Issue by tdewangan** [InfomediaLtd/angular2-materialize#100]
@rubyboy looks like materialize js is not loaded in the build, can you please have a look on below repository and let me know what i missed.
[https://github.com/tdewangan/angular2-webpack-materialize.git](https://github.com/tdewangan/angular2-webpack-materialize.git)

Thanks

**Comment by rubyboy** [comment]
Indeed, you need to install (and import) materialize-css separately, before angular2-materialize.
I don't see any in your project. Did you? (npm install materialize-css --save)
Check out this section in the README: https://github.com/InfomediaLtd/angular2-materialize#installing-and-configuring-angular2-materialize-with-webpack

**Comment by tdewangan** [comment]
Sorry my bad forgot to commit changes

**Comment by rubyboy** [comment]
Here's a sample repo: https://github.com/InfomediaLtd/angular2-webpack-starter
