### ISSUE TITLE
collapsible element is not expanding

### ISSUE THREAD

**Issue by SefaOray** [InfomediaLtd/angular2-materialize#102]
To clarify, collapsible element is working fine as it is. My problem is rather spesific. 

I'm making an api call when collapsible header is clicked and binding result to collapsible body. 

The problem is: I have to click the collapsible header exactly 3 times to open it. 

Here is my template:

```
    <ul materialize="collapsible" class="CharacterList collapsible" data-collapsible="expandable">
        <li>
        <div class="chacter collapsible-header" (click)="toggle()">
            <i class="medium material-icons">contacts</i> Characters
        </div>

        <div class="collapsible-body" *ngFor="let item of characters">
            <character-selector [character]="item"></character-selector>
        </div>
        </li>
    </ul>
```

And my toggle function

```
    toggle(){
      if(!this.initialized){
            this.initialized = true;
            this.characterListService.getCharactersInKey(this.apiKey.id).subscribe((res)=> {
              this.characters = res;
          }, (err) => {console.log(err)});
      }
    }
```

My api calls takes less than 1 second. I tested and confirmed that it's not about waiting the api call to finish. 

Any tips to help me debug this?

**Comment by eamonnmag** [comment]
+1 on this. I'm also having troubles with collapsible.

`
<ul materialize="collapsible" class="collapsible" data-collapsible="accordion">
                    <li *ngFor="let topic of getEnrichedTopics(index)">
                        <div class="collapsible-header">
                            {{topic.name}}
                            <span class="badge">{{topic.value | number : '1.4-4'}}</span>
                        </div>
                        <div class="collapsible-body">
                            <p>details...</p></div>
                    </li>
                </ul>
`

**Comment by rubyboy** [comment]
@SefaOray what is happening here is the Collapsible function gets called before you populate the body, thus not showing anything on first click. Then, on second click it collapses (which looks the same, not showing any body). On third click it actually expands agains and now shows data.

Here's a solution:
- You need to prevent the expansion on first click
- When data arrives manually trigger "collapsible"

Something like this:
```html
    <ul materialize="collapsible" class="CharacterList collapsible" data-collapsible="expandable" [materializeActions]="collapsibleActions">
        <li>
        <div class="chacter collapsible-header" (click)="toggle($event)">
            <i class="medium material-icons">contacts</i> Characters
        </div>

        <div class="collapsible-body" *ngFor="let item of characters">
            {{item}}
        </div>
        </li>
    </ul>
```

```js
    characters = [];
    initialized = false;
    collapsibleActions = new EventEmitter<string>();

    toggle($event){
      if(!this.initialized){
        this.initialized = true;
        window.setTimeout(() => {
          this.characters = [1,2,3];
          this.collapsibleActions.emit("collapsible");
        },1000);
        $event.preventDefault();
      }
    }
```
