### ISSUE TITLE
Wrong behavior with angular-cli@webpack

### ISSUE THREAD

**Issue by juanpmarin-infocorp** [InfomediaLtd/angular2-materialize#103]
Hi, how are you ? 

The library not works correctly with the latest version of the cli, I test it with sideNav and it not work, with the dropdown works well

Thank you

**Comment by rubyboy** [comment]
Need a bit more info. Maybe share a repository that shows the problem.
If you're in the mood to debug and fix we'd love a PR.
Thanks.

**Comment by unseen1980** [comment]
Hey @rubyboy , I have issues as well. I can't get angular2-materialize to work with angular-cli webpack version. I think I am not installing the libraries properly. Did you try it? Any luck?

Regards
Chris

**Comment by rubyboy** [comment]
I haven't tried it since @Sixthdim created a PR (https://github.com/InfomediaLtd/angular2-materialize/pull/84) to fix incompatibilities with the CLI on RC-5. Maybe he or @pchristou can comment on this.

**Comment by pchristou** [comment]
I ended up abandoning cli and going back to a RC5 boiler plate of starter pack along with materialize.

**Comment by juanpmarin-infocorp** [comment]
This issue is related with the exception 
`Uncaught TypeError: Vel is not a function` 

I fixed it hacking the cli at the moment, in `node_modules/angular-cli/addon/ng2/models/webpack-build-common.ts` I added the following lines in the plugins object:

```
new webpack.ProvidePlugin({
  $: "jquery",
  jQuery: "jquery",
  "window.jQuery": "jquery",
  Hammer: "hammerjs/hammer"
}),
```

Doing that the issue is solved until the angular-cli team do that we can use own settings.

**Comment by Sixthdim** [comment]
As @rubyboy stated, we need a little more detail to provide feedback. How did you set this up in your app? Are you getting any errors with line numbers? I have been using angular2-materialize successfully in my angular-cli webpack.2 app since my PR (https://github.com/InfomediaLtd/angular2-materialize/pull/84). The webpack instructions in the readme worked for me, minus the webpack config part.

Did you import your required scripts in your `app.module.ts`? Like...
````
import 'jquery';
import 'materialize-css';
import 'angular2-materialize';
````

I have not encountered the `Uncaught TypeError: Vel is not a function` error. I'm not sure what script that would be coming from.

**Comment by wceolin** [comment]
@Sixthdim I'm trying to import it the way you said but I'm getting the following error:

`Couldn't find Materialize object on window. It is created by the materialize-css library. Please import materialize-css before importing angular2-materialize.`

Is there something else we have to do to import it using `angular-cli@webpack`?

**Comment by juanpmarin-infocorp** [comment]
Hi, the correct way to import jquery and materialize is using the scripts array on the angular-cli.json file, like this: 

`{
  "project": {
    "version": "1.0.0-beta.12-1",
    "name": "sample-project"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": "assets",
      "index": "index.html",
      "main": "main.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.json",
      "prefix": "app",
      "mobile": false,
      "styles": [
        "styles.scss",
        "../node_modules/material-design-icons/iconfont/material-icons.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/materialize-css/bin/materialize.js"
      ],
      "environments": {
        "source": "environments/environment.ts",
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "addons": [],
  "packages": [],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "prefixInterfaces": false
  }
}
`

Doing the is not necesary to import jquery and materialize-css like @Sixthdim suggest, you must just import angular2-materialize
