### ISSUE TITLE
carousel

### ISSUE THREAD

**Issue by Saul-Simhon** [InfomediaLtd/angular2-materialize#109]
Hi,
Not sure if I got this right, but I have not been able to get the materialize carousel to work. Not sure if its a bug, not support, or if I'm doing something wrong..see template code below. (everything else i tried this far seems to work). 

<div materialize="carousel" class="carousel carousel-slider center" data-indicators="true">
  <div class="carousel-fixed-item center">
    <a class="btn waves-effect white grey-text darken-text-2">button</a>
  </div>
  <div class="carousel-item red white-text" href="#one!">
    <h2>First Panel</h2>
    <p class="white-text">This is your first panel</p>
  </div>
  <div class="carousel-item amber white-text" href="#two!">
    <h2>Second Panel</h2>
    <p class="white-text">This is your second panel</p>
  </div>
  <div class="carousel-item green white-text" href="#three!">
    <h2>Third Panel</h2>
    <p class="white-text">This is your third panel</p>
  </div>
  <div class="carousel-item blue white-text" href="#four!">
    <h2>Fourth Panel</h2>
    <p class="white-text">This is your fourth panel</p>
  </div>
</div>

**Comment by rubyboy** [comment]
@Saul-Simhon what does your code look like?

See here for an example: https://github.com/InfomediaLtd/angular2-materialize/issues/71
