### ISSUE TITLE
TypeError: Cannot read property 'swing' of undefined

### ISSUE THREAD

**Issue by mairanteodoro** [InfomediaLtd/angular2-materialize#111]
I was getting this error while trying to use `angular2-materialize` on an Angular2 project of mine. Apparently, jQuery was not being loaded, despite following all the steps described [here](https://www.npmjs.com/package/angular2-materialize#installing--configuring-angular2-materialize-in-projects-created-with-angular-cliwebpack-100-beta11-webpack8) (installing and configuring angular2-materialize in projects created with `angular-cli@webpack`).

It turns out that, in order to get rid of the error and have the app working, I had to change the `scripts` in the`angular-cli.json` file to **point to the minified version of jQuery** instead of the full version as mentioned in the step-by-step installation and configuring manual.

**Comment by sh4d0000** [comment]
I have the same problem using the latest angular-cli.

If I use the min version I get "velocity not a function" problem tough

**Comment by rubyboy** [comment]
Check out the following two issues. Maybe they'll have info that would help you import MaterializeCSS properly with the CLI: https://github.com/InfomediaLtd/angular2-materialize/issues/82 , https://github.com/InfomediaLtd/angular2-materialize/issues/103

If you find that the documentation needs adjustment, I'd be more than happy to approve a PR with these changes.

**Comment by sh4d0000** [comment]
After hours trying stuff I have removed and reinstalled angular-cli and suddenly everything started to work. It's not the first time my angular-cli installation gets messed up :/ ...angular-cli is still in beta.

**Comment by gdlm91** [comment]
I was having this issue as I reported in #78 . Then I tried this repo they were recomendind, and it worked
https://github.com/pragdev/angular_example

My package.json and angular-cli.json files were almos the same, except for one thing: My proyect had angular-cli 1.0.0-beta.17, and this repo had 1.0.0-beta.15.

I changed that on my package.json, reinstalled everything, and now my nav is working fine!

**Comment by bardiarastin** [comment]
@mairanteodoro i had the same problem and your solution solved it . tnx . 
version : 1.0.0-beta.18

**Comment by abhinaypandey** [comment]
I am having the same issue as raised by @mairanteodoro . Followed all the above steps still getting the same issue while running the application. Getting errors as stated by @mairanteodoro

**Comment by rastographics** [comment]
Same problem as OP (cannot read property 'swing'), using  angular-cli 1.0.0-beta.19-3
Problem also fixed for me by using jquery.min

**Comment by rastographics** [comment]
This fixed the problem for me:

In `main.ts` I had:

`import 'materialize-css';
import 'angular2-materialize';`

After removing those two lines, everything now works!

**Comment by omidh28** [comment]
Also happens when slim version of jQuery is used

**Comment by brockklein** [comment]
Just removed `import 'materialize-css` per @rastographics recommendation above and that did the trick. I was getting the `Uncaught TypeError: e.velocity is not a function` on my mobile collapsible nav bar (`materialize="sideNav"`). 

Since I included the Materialize CSS in `angular-cli.json`

```
"styles": [
        "../node_modules/materialize-css/dist/css/materialize.css",
        "styles.css"
      ],
```

I didn't need to import it again (in my case I was importing it in `AppModule`). Guess the double CSS import was causing conflicts somehow (I have no clue how...).
