### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'jQuery.easing.swing')

### ISSUE THREAD

**Issue by bernhardwaidacher** [InfomediaLtd/angular2-materialize#113]
I get this error after I've installed angular2-materialize as explained in "Installing & configuring angular2-materialize in projects created with angular-cli@webpack (1.0.0-beta.11-webpack.8)"

I've used this code to test:
```
<ul materialize="collapsible" class="collapsible" data-collapsible="accordion">
  <li>
    <div class="collapsible-header"><i class="material-icons">filter_drama</i>First</div>
    <div class="collapsible-body"><p>Lorem ipsum dolor sit amet.</p></div>
  </li>
  <li>
    <div class="collapsible-header"><i class="material-icons">place</i>Second</div>
    <div class="collapsible-body"><p>Lorem ipsum dolor sit amet.</p></div>
  </li>
  <li>
    <div class="collapsible-header"><i class="material-icons">whatshot</i>Third</div>
    <div class="collapsible-body"><p>Lorem ipsum dolor sit amet.</p></div>
  </li>
</ul>
```

**Comment by rubyboy** [comment]
sounds like jQuery (or jQuery.easing) is not found. Make sure you bring in jQuery and the right version of it.
Also, check out this issue that had the same problem and was solved by reinstalling the cli: https://github.com/InfomediaLtd/angular2-materialize/issues/111
If none of that works, maybe @sh4d0000 can share a repository that works and you can compare the configuration.

**Comment by bernhardwaidacher** [comment]
Thank, with chaning the path of jquery to min in worked. That what it looks like now:
```
"scripts": [
        "../node_modules/jquery/dist/jquery.min.js",
        "../node_modules/materialize-css/dist/js/materialize.js"
      ],
```

However, it still doesn't work fine. I wanted to test it with this: 
```
import { Component } from '@angular/core';


@Component({
  selector: "app-root",
  template: `
        <ul materialize="collapsible" class="collapsible" data-collapsible="accordion">
          <li>
            <div class="collapsible-header"><i class="material-icons">filter_drama</i>First</div>
            <div class="collapsible-body"><p>Lorem ipsum dolor sit amet.</p></div>
          </li>
          <li>
            <div class="collapsible-header"><i class="material-icons">place</i>Second</div>
            <div class="collapsible-body"><p>Lorem ipsum dolor sit amet.</p></div>
          </li>
          <li>
            <div class="collapsible-header"><i class="material-icons">whatshot</i>Third</div>
            <div class="collapsible-body"><p>Lorem ipsum dolor sit amet.</p></div>
          </li>
        </ul>
        `,
  styleUrls: ['./app.component.css']
})
export class AppComponent {}
```
There is no javascript error or something like that, but the effects and transitions are not working properly. I made a short video to demonstrate: https://vid.me/nZzG

**Comment by rubyboy** [comment]
I'm not using the Webpack CLI myself so I can't help you much there, but I'm pretty sure that one of the dependencies is missing. Either the MaterializeCSS or its JS.
Also, make sure that the loading order is jQuery->Materialize->angular2-materialize. Each of these depends on the others.
Maybe try finding a project that works and copy its config? Consult with @sh4d0000 on his project setup.

**Comment by sh4d0000** [comment]
Sorry for being late. Here a working repo using angular-cli 1.0.0-beta.15 and Materialize: https://github.com/pragdev/angular_example

**It is important** to make sure you have clean installation of angular-cli so please follow these instructions first: https://github.com/angular/angular-cli#updating-angular-cli

After that clone the repo and _npm install_ in your project. Hope it helps.

**Comment by bernhardwaidacher** [comment]
THANK YOU SO MUCH @sh4d0000 

I've cloned your repo, copied my files into it, and everything works now!! I have no idea why, I've compared the config files and they were identical

I don't know, but thanks :)

**Comment by rubyboy** [comment]
Closing this one.

@sh4d0000 thank you so much for sharing your repository and the way to link angular2-materialize with the CLI. If this example repo is something you're maintaining, I'd love to link to it from this repository as a resource for people who may be using the CLI with angular2-materialize. Let me know if that's something you'd be open to. Thanks!

**Comment by pragdev** [comment]
@rubyboy I'll be happy to maintain it, feel free to link.
