### ISSUE TITLE
Couldn't find materialize function ''tooltip' on element or the global Materialize object.

### ISSUE THREAD

**Issue by tettusud** [InfomediaLtd/angular2-materialize#114]
I am using  angular component 2.0.0 . I followed the steps explained in npm page. am getting below error for any compoenent
Couldn't find materialize function ''tooltip' on element or the global Materialize object.
Any idea?
Does it work only for Angular Rc?

**Comment by Nestyko** [comment]
Please provide some more information about your setup.
I had a similar issue with some functions that weren't recognized as well like "parallax" and "sideNav", that happend when I used the https://github.com/AngularClass/angular2-webpack-starter this repo seems to load jquery several times which results in the Materialize functions being binded to only one of those jquery instances, and may result that the jquery that you are calling tooltip on be a different one.

To resolve this problem I started using the last angular-cli which uses webpack and there is documentation on how to set it up in the readme of angular2-materialize

More information on this closed issue #44 
Some solutions in that issue suggested by @rubyboy:

If you are using webpack is to use this repo https://github.com/InfomediaLtd/angular2-materialize

or try using JSPM

**Comment by sudharsantk** [comment]
Hi am using angular2-seed project , I added webpack as shown in npm-angular2
https://github.com/sudharsantk/angular2.
I imported both ..

**Comment by aaronfdes** [comment]
I'm getting a similar problem
`Couldn't find materialize function ''collapsible' on element or the global Materialize object.`

I've followed the steps from the npm page and even tried a few variations. Im no webpack expert just started using it a couple of weeks ago. If someone could tell me whats wrong.
Here is my repo https://github.com/aaronfdes/Angular-2-webpack-starter in the materialcss branch.

**Comment by sudharsantk** [comment]
I resolved it ,add it to the main.ts
import "materialize-css";
import "angular2-materialize";
import 'materializecss';
import 'materialize';

I checked in files, aarondfdes you can refer to my code it works

https://github.com/sudharsantk/angular2.

**Comment by aaronfdes** [comment]
im getting `Module not found: Error: Cannot resolve module 'materializecss'`
did you install these packages separately because i didn't see them in your package.json?

**Comment by sudharsantk** [comment]
Actually its not necessary as well.I copied from my previous example

**Comment by Tempus35** [comment]
Having the same issue with materializeActions. I am using Webpack as well but I am beyond confused on what @sudharsantk discussed with the imports and the repo is dead he linked. Here is the error I am getting: 

`index.js:29 Uncaught Error: Couldn't find materialize function ''openModal' on element or the global Materialize object.`

**Comment by rubyboy** [comment]
@sudharsantk can we close this issue or is it still a problem?

@Tempus35 it would be helpful if you could provide a link to your repository or a simplified repository example of your problem. People may be able to help provided these additional details.
I'd start by searching this repository for solutions (in closed issues) and then create a separate issue describing your specific use case. Thanks.

**Comment by Tempus35** [comment]
[Sample Repo](https://github.com/Tempus35/angular2-materialize-webpack2)
I used the angular2webpack2-starter then added in Materialize-Css and Angular2-Materialize. A sample of the error can be found by running npm install, npm start, going to localhost:3000 and clicking lazy on the left, the errors show in the console.

**Comment by Blazzze** [comment]
i also have this issue..
checked in 2 projects:
one of them:  with webpack without lazy loaded modules (works)
the other: with webpack too WITH lazy loaded module, and with a shared module importing MaterializeModule...

i get a 
Couldn't find materialize function ''tooltip' on element or the global Materialize object.
or 
Couldn't find materialize function ''material_select' on element or the global Materialize object.
(which one i try to put anywhere in a component inside those 2 modules
