### ISSUE TITLE
(SystemJS) Multiple anonymous defines in module

### ISSUE THREAD

**Issue by MrSnappingTurtle** [InfomediaLtd/angular2-materialize#115]
Hello,

I am getting the following error:

![error](https://cloud.githubusercontent.com/assets/8148243/18820162/136c0d44-8350-11e6-8f56-2c91b82424e2.PNG)

The weird thing is that my project was working earlier. I build my project into a separate directory so I have to copy over the required node modules. Before, I wasn't preserving the folder structure so all the files were dumped into a `build/libs/` directory. I now adjusted it so that it goes into the proper structure (e.g. `build/node_modules/materialize-css/...` or `build/node_modules/@angular/...`). This change however, started triggering the error above. I have seen #18 but I don't see any differences between what I am doing and the solution mentioned there.

My setup:
- Angular 2
- SystemJS
- Electron (I don't think this matters, though)

`app.html`

``` html
...
<title>Carrots</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <base href="../../../">

    <script type="text/javascript" src="node_modules/jquery/dist/jquery.min.js"></script>

    <!-- Materialize -->
    <link type="text/css" rel="stylesheet" href="node_modules/materialize-css/dist/css/materialize.min.css" media="screen,projection" />
    <script src="node_modules/hammerjs/hammer.min.js"></script>
    <script src="node_modules/materialize-css/dist/js/materialize.min.js"></script>
    <link href="./app/components/fonts/fonts.css" rel="stylesheet">

    <script src="node_modules/zone.js/dist/zone.js"></script>
    <script src="node_modules/reflect-metadata/Reflect.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>

    <script src="systemjs.config.js"></script>
    <script>
      System.import('app').catch(function(err){ console.error(err); });
    </script>
    <link rel="stylesheet" ype="text/css" href="app/layouts/app/app.css" />
  </head>

  <body>
    <my-app>
      ...
```

`systemjs.config.js`

``` js
(function (global) {
  System.config({
    paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      app: 'app',

      // angular bundles
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',

      // other libraries
      'rxjs': 'npm:rxjs',

      // Materialize
      'materialize-css': 'npm:materialize-css',
      'angular2-materialize': 'npm:angular2-materialize',
      'materialize': 'npm:angular2-materialize'
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      app: {
        main: './main.js',
        defaultExtension: 'js'
      },
      rxjs: {
        defaultExtension: 'js'
      },
      'materialize': {
        main: 'dist/materialize-directive',
        defaultExtension: 'js'
      },
      'materialize-css': {
        main: 'dist/js/materialize'
      }
    }
  })
})(this)
```

Structure:
![structure](https://cloud.githubusercontent.com/assets/8148243/18820525/195f3d0e-8353-11e6-8c4b-f6a1f1d58304.PNG)

Thanks!

**Comment by allahbaksh** [comment]
Even I am facing similar issue. I am trying to add materialize in code generated by jhipster and stuck at 
localhost/:103 Error: Error: Multiple anonymous defines in module http://localhost:9000/vendor/materialize-css/dist/js/materialize.js
	    at eval (http://localhost:9000/vendor/materialize-css/dist/js/materialize.js:238:9)
	    at eval (http://localhost:9000/vendor/materialize-css/dist/js/materialize.js:244:2)
	    at eval (http://localhost:9000/vendor/materialize-css/dist/js/materialize.js:7470:3)
	Evaluating http://localhost:9000/vendor/materialize-css/dist/js/materialize.js
	Error loading http://localhost:9000/vendor/materialize-css/dist/js/materialize.js as "materialize-css" from http://localhost:9000/app/app.main.js(anonymous function) @ localhost/:103

@rubyboy  do we have solution for this apart from what is mentioned in #18

**Comment by rubyboy** [comment]
I'm using JSPM, so I'm not sure I can help with other setups. You can view the project how SystemJS is configured via JSPM, if that helps.
Seems like a common issue trying to import MaterializeCSS. That's why we decided to separate the MaterializeCSS dependency and not import them in angular2-materialize.

Common issues that I've seen are: not bringing jQuery, wrong version of jQuery (MaterializeCSS doesn't support latest), importing jQuery or MaterializeCSS multiple times, not importing Materialize/jQuery/hammerJS.

**Comment by Bucabug** [comment]
@MrSnappingTurtle  @allahbaksh did either of you get anywhere with this problem? I am experiencing it myself now.

**Comment by MrSnappingTurtle** [comment]
@Bucabug I've been busy so I haven't had time to work on side projects. I'll try to figure it out this weekend. I'll update when I find something.

**Comment by Bucabug** [comment]
Thanks for that @MrSnappingTurtle . I'm going to be looking into myself today/tomorrow so if I find anything I'll report back.

**Comment by Bucabug** [comment]
I've managed to get it working...

I looked at the docs and in the [Configuring-angular2-materialize-in-projects-created-with-angular-cli](https://www.npmjs.com/package/angular2-materialize#installing--configuring-angular2-materialize-in-projects-created-with-angular-cli) section I noticed that the package configuration for 'materialize-css' has the following property set

````
"format": "global"
````

I added that property the packages definition of materialize-css in my system js and this fixes the error for me.

My system.js.config.js is now as follows:

````javascript
var isPublic = typeof window != "undefined";

/**
 * System configuration for Angular 2 samples
 * Adjust as necessary for your application needs.
 */
(function(global) {
  System.config({
    paths: {
      // paths serve as alias
      'npm:': (isPublic) ? '/' : 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      app: 'client',
      // angular bundles
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
      // other libraries
      'rxjs': 'npm:rxjs',
      'js-base64': 'npm:js-base64/base64.js',
      'buffer': '@empty',
      'angular2-jwt': 'npm:angular2-jwt/angular2-jwt.js',
      'materialize-css': 'npm:materialize-css',
      'angular2-materialize': 'npm:angular2-materialize'
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      'app': {
        'main': './main.js',
        'defaultExtension': 'js'
      },
      'rxjs': {
        'defaultExtension': 'js'
      },
      'materialize-css': {
        "format": "global",
        "main": "dist/js/materialize",
        "defaultExtension": "js"
      },
      'angular2-materialize': {
        "main": "dist/index",
        "defaultExtension": "js"
      }
    }
  });
})(this);
````

**Comment by rubyboy** [comment]
Given the solution above I'm going to close the bug. Please let me know (or create a PR) if there's anything that needs to change in the docs. Thanks to everyone who contributed.

**Comment by brockklein** [comment]
Leaving this here for posterity's sake:

I have a vanilla SystemJS setup and the solution at https://github.com/InfomediaLtd/angular2-materialize/issues/18#issuecomment-209950965 does not work, but the solution above does work.
