### ISSUE TITLE
Modal redirect

### ISSUE THREAD

**Issue by isametal88** [InfomediaLtd/angular2-materialize#116]
Hi guys,

I'm new to Angular2 environment, be patient with me :-)
I'm currently using angular2-materialize in my application, mainly because official angular2-material is really behind in development.
I'm trying to use the modal provided by the library, but something is clearly wrong with my settings.
I just copied the example, but clicking the link changes the url to #modal1, without (of course) opening the modal.
What have I may done wrong?

I tried to use the component in a previous version of the application, there were CSS issues (the black overlay was on top of the modal) but it seemed to work. Something needs to be changed in the switch to Webpack?
I'm also using the form select, so I believe that the JS is loaded properly...

Thank you very much

Isaia

**Comment by rubyboy** [comment]
@isametal88 what setup are you using (webpack, cli, etc.) ? Maybe share a repository with the problem.

**Comment by isametal88** [comment]
I 'm using webpack in this last version.
I can't share the repository, though.

I'm not very familiar with these configurations, tell me what you need to see and I'll send it to you.

Thank you very much for your quick response.

Isaia

**Comment by rubyboy** [comment]
Have a look at how this project is configured: https://github.com/InfomediaLtd/angular2-webpack-starter
Maybe you can create a small repository that reproduces your issue so people can help you. Very difficult to help without the details.

**Comment by isametal88** [comment]
Be patient with me, please :-) .
I cloned that repository, integrated the modal example and it's working properly.
My own project started from the angular2-webpack-starter (the original version). I tried to compare the two versions, but the differences are huge (that said, I edited only small part of the configurations).
I tried upgrading the angular 2 version to the final (the one I'm currently using), the router to 3.0.0. and change the router mode removing the hash. And it's still working fine.
In the meantime i wrote my own dialog component, but for obvious reason I'd like to use yours.
I know that is very difficult this way, but could you point me in the right direction?
