### ISSUE TITLE
EXCEPTION: ReferenceError: Materialize is not defined

### ISSUE THREAD

**Issue by moumoune** [InfomediaLtd/angular2-materialize#12]
I've some problem with integration of angular2-materialize in my Angular2 app.

Here is my code:

index.html:
```
System.config({
            map: {
                "ng2-translate": "node_modules/ng2-translate",
                "materialize-css": "node-modules/materialize-css",
                "angular2-materialize": "node_modules/angular2-materialize"
            },
            packages:  {
                    dist: {
                    format: 'register',
                    defaultExtension: 'js'
                },
                "ng2-translate": {
                    "defaultExtension": "js"
                },
                "materialize-css": {
                    "main": "dist/js/materialize"
                },
                "angular2-materialize": {
                    "main": "dist/materialize-directive",
                    "defaultExtension": "js"
                }
            }
        });
```

main.ts:
`import "angular2-materialize";`

home.component.ts:
```
import {MaterializeDirective} from "angular2-materialize";

@Component({
    selector: 'swp-home',
    templateUrl: 'app/memberarea/components/home.component.html',
    directives: [RouterLink, MaterializeDirective]
})

```
Template of my component:
`<a materialize="tooltip" class="btn tooltipped" data-position="bottom" data-delay="50" data-tooltip="I am tooltip">Hover me!</a>`

and here my error:
EXCEPTION: ReferenceError: Materialize is not defined
angular2.dev.js:23730 EXCEPTION: ReferenceError: Materialize is not definedBrowserDomAdapter.logError @ angular2.dev.js:23730BrowserDomAdapter.logGroup @ angular2.dev.js:23741ExceptionHandler.call @ angular2.dev.js:1292(anonymous function) @ angular2.dev.js:12674schedulerFn @ angular2.dev.js:13078SafeSubscriber.__tryOrUnsub @ Rx.js:10775SafeSubscriber.next @ Rx.js:10730Subscriber._next @ Rx.js:10690Subscriber.next @ Rx.js:10667Subject._finalNext @ Rx.js:11191Subject._next @ Rx.js:11183Subject.next @ Rx.js:11142EventEmitter.emit @ angular2.dev.js:13059NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ angular2.dev.js:13477NgZoneImpl.inner.inner.fork.onHandleError @ angular2.dev.js:2233ZoneDelegate.handleError @ angular2-polyfills.js:326Zone.runGuarded @ angular2-polyfills.js:235NgZoneImpl.runInner @ angular2.dev.js:2245NgZone.run @ angular2.dev.js:13560(anonymous function) @ angular2.dev.js:12773schedulerFn @ angular2.dev.js:13078SafeSubscriber.__tryOrUnsub @ Rx.js:10775SafeSubscriber.next @ Rx.js:10730Subscriber._next @ Rx.js:10690Subscriber.next @ Rx.js:10667Subject._finalNext @ Rx.js:11191Subject._next @ Rx.js:11183Subject.next @ Rx.js:11142EventEmitter.emit @ angular2.dev.js:13059NgZone._checkStable @ angular2.dev.js:13500NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.setMicrotask @ angular2.dev.js:13471NgZoneImpl.inner.inner.fork.onHasTask @ angular2.dev.js:2225ZoneDelegate.hasTask @ angular2-polyfills.js:381ZoneDelegate._updateTaskCount @ angular2-polyfills.js:399ZoneDelegate.invokeTask @ angular2-polyfills.js:359Zone.runTask @ angular2-polyfills.js:254drainMicroTaskQueue @ angular2-polyfills.js:473ZoneTask.invoke @ angular2-polyfills.js:425
angular2.dev.js:23730 STACKTRACE:BrowserDomAdapter.logError @ angular2.dev.js:23730ExceptionHandler.call @ angular2.dev.js:1294(anonymous function) @ angular2.dev.js:12674schedulerFn @ angular2.dev.js:13078SafeSubscriber.__tryOrUnsub @ Rx.js:10775SafeSubscriber.next @ Rx.js:10730Subscriber._next @ Rx.js:10690Subscriber.next @ Rx.js:10667Subject._finalNext @ Rx.js:11191Subject._next @ Rx.js:11183Subject.next @ Rx.js:11142EventEmitter.emit @ angular2.dev.js:13059NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ angular2.dev.js:13477NgZoneImpl.inner.inner.fork.onHandleError @ angular2.dev.js:2233ZoneDelegate.handleError @ angular2-polyfills.js:326Zone.runGuarded @ angular2-polyfills.js:235NgZoneImpl.runInner @ angular2.dev.js:2245NgZone.run @ angular2.dev.js:13560(anonymous function) @ angular2.dev.js:12773schedulerFn @ angular2.dev.js:13078SafeSubscriber.__tryOrUnsub @ Rx.js:10775SafeSubscriber.next @ Rx.js:10730Subscriber._next @ Rx.js:10690Subscriber.next @ Rx.js:10667Subject._finalNext @ Rx.js:11191Subject._next @ Rx.js:11183Subject.next @ Rx.js:11142EventEmitter.emit @ angular2.dev.js:13059NgZone._checkStable @ angular2.dev.js:13500NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.setMicrotask @ angular2.dev.js:13471NgZoneImpl.inner.inner.fork.onHasTask @ angular2.dev.js:2225ZoneDelegate.hasTask @ angular2-polyfills.js:381ZoneDelegate._updateTaskCount @ angular2-polyfills.js:399ZoneDelegate.invokeTask @ angular2-polyfills.js:359Zone.runTask @ angular2-polyfills.js:254drainMicroTaskQueue @ angular2-polyfills.js:473ZoneTask.invoke @ angular2-polyfills.js:425
angular2.dev.js:23730 ReferenceError: Materialize is not defined
    at MaterializeDirective.performElementUpdates (http://localhost:3000/node_modules/angular2-materialize/dist/materialize-directive.js:58:13)

**Comment by rubyboy** [comment]
@moumoune are you using Webpack or JSPM? I think it's something to do with the way your module loader is defined. It needs to have "materialize" defined as an alias.

Here's how you do that with JSPM:
```js
System.config({
  ...
  packages: {
    ...
    "materialize": {
      "main": "dist/js/materialize"
    }
  },
```

And this is with Webpack:
```js
var webpack = require("webpack");
module.exports = {
  //...
  resolve: {
    alias: {
      materializecss: 'materialize-css/dist/css/materialize.css',
      materialize: 'materialize-css/dist/js/materialize.js',
      //...
    }
    //...
  },
```

If you're not sure how to do that you can give me a link to Github or upload a zip of the project and I can take a look.

**Comment by moumoune** [comment]
Hey, thank you for your quick reply. I use only SystemJS, and i go to try materialize as an alias.

I'll try that and then I'll post something

**Comment by moumoune** [comment]
I don't use Webpack or JSPM but npm and SystemJS module loader.
I change alias like this: `"materialize": "node_modules/angular2-materialize"`

Same error :(

 I send you my zip project: https://drive.google.com/open?id=0Bzekw6FaXUXNQWhNcEc2OE9SZDQ

**Comment by rubyboy** [comment]
In index.html add this to your mapping section of System.js:
```js
System.config({
            map: {
                //...
                "angular2-materialize": "node_modules/angular2-materialize"
```
And then uncomment your materialize import:
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
```

After that it should work.

**Comment by rubyboy** [comment]
@moumoune did you get it working?

**Comment by moumoune** [comment]
I try this this morning :)

**Comment by moumoune** [comment]
@rubyboy Ok, it's work ! Thx a lot, for your help and for this awesome library.
I close this issue.
