### ISSUE TITLE
Pull request with move from Angular RC5 to 2.0

### ISSUE THREAD

**Issue by allahbaksh** [InfomediaLtd/angular2-materialize#120]
@rubyboy I have done some changes in source and also in the package.json, config.json files. There are still some errors to be resolved.
https://github.com/allahbaksh/angular2-materialize
Can you please help in resolving these 
https://travis-ci.org/allahbaksh/angular2-materialize/builds/163354520

**Comment by rubyboy** [comment]
@allahbaksh I should have time early next week. Would you like to give me permissions to your branch and we'll get that one working fully before merging?

**Comment by rubyboy** [comment]
@allahbaksh thanks heaps for your contribution. I've updated your fork with a few tiny fixes and merged the PR. angular2-materialize is now on ng2 thanks to your effort! :)
