### ISSUE TITLE
Add metadata.json file generation for Angular AoT compilation support

### ISSUE THREAD

**Issue by bitbeter** [InfomediaLtd/angular2-materialize#121]
I have an issue about AoT compilation support in angular 2 that it want metadeta.json for compilation step.
If possible for you add this files to your project.

**Comment by rubyboy** [comment]
Haven't tried AoT yet. You're more than welcome to add the file and send me a PR. I'd happily merge it.

**Comment by vesteraas** [comment]
A good article on the subject: https://medium.com/@isaacplmann/getting-your-angular-2-library-ready-for-aot-90d1347bcad#.r9xqehoy8

**Comment by mbeckenbach** [comment]
@rubyboy you should try AoT. Brings my app from 2.5 MB page load down to 0.8 k and it renders at the speed of light

**Comment by rubyboy** [comment]
@mbeckenbach sounds cool! I may have a stab at it in a few weeks. Depends on our delivery timelines.

**Comment by vesteraas** [comment]
We needed AoT support for this component in our project, so I followed the guide mentioned above, and fixed it.  You could check https://github.com/vesteraas/angular2-materialize to see what I did to make it work.  Ideally, I should create a PR, but I feel that my take on it was more like a quick-fix, and not the best way to implement it.

**Comment by vesteraas** [comment]
@mbeckenbach you could run `npm pack` in my fork, and then just install the generated tarball in your project.

**Comment by mbeckenbach** [comment]
ok. will i try that tomorrow and provide feedback

**Comment by AAAnderson7301** [comment]
@vesteraas I am still getting  Unexpected value 'MaterializeDirective' in my module.ts file. I tried the tarball

**Comment by mbeckenbach** [comment]
Same with me. But it looks like we will remove materializecss anyway and move to paper webcomponents because of the better integration.

**Comment by vesteraas** [comment]
You should run `gulp` in my fork, before running `npm pack`.  The resulting tarball is ~28kB in size.  In your project, you should add `MaterializeModule` in your components modules `import` section.

**Comment by FoodBuster** [comment]
@vesteraas Thanks for the info, but unfortunately gulp is throwing an error for me (below). If there isn't an easy solution to this, could you please commit the tarball to your forked package? Would be  awesome to just clone and install.

`
Error: Command failed: ./node_modules/.bin/ngc -p tsconfig.json
/Users/edMokhtarian/Desktop/angular2-materialize/node_modules/@angular/compiler-cli/src/private_import_compiler.js:10
exports.AssetUrl = compiler_1.__compiler_private__.AssetUrl;

Cannot read property 'AssetUrl' of undefined
    at Object.<anonymous> ([...]/Desktop/angular2-materialize/node_modules/@angular/compiler-cli/src/private_import_compiler.js:10:51)
`

**Comment by FoodBuster** [comment]
So I figured out the error: In the newest version of angular2-materialize, before doing npm install, we need to set angular package versions below 2.02 (package.json has them as ^2.01. I went with v2.0.0, but 2.01 probably works).

So, the full workflow is: 1) clone repo, 2) set angular package versions, 3) npm install in cloned repo, 4) npm pack in cloned repo, 5) npm install tarball in project.

**Comment by w3chtml** [comment]
@vesteraas @FoodBuster Thanks for effort. Let me add some information/confirmation:
All true as @FoodBuster's  message. Here is my diff with @vesteraas repo in `package.json`:
```
-    "@angular/compiler-cli": "^0.6.3",
+    "@angular/compiler-cli": "^2.0.1",
```

**Comment by vesteraas** [comment]
I managed to delete my fork of this project, by accident :(

**Comment by rubyboy** [comment]
https://github.com/InfomediaLtd/angular2-materialize/pull/166 has been merged. Thanks @Maistho !
