### ISSUE TITLE
TypeError: $(...).material_chip is not a function

### ISSUE THREAD

**Issue by russon77** [InfomediaLtd/angular2-materialize#122]
Is `$().material_chip` not supported by this library? `material_select()`, `lean_modal()` and a few other functions are supported, but I cannot get chips to work. 

Any ideas?

**Comment by n0mid** [comment]
When I use material_chip and add [(ngModel)] I got next error: 
No value accessor for form control with unspecified name attribute

I used it: 
`<div materialize="material_chip" [(ngModel)]="tags"></div>`

With: 
    `<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>`

**Comment by rubyboy** [comment]
@russon77 I've added example of how to use chips with angular2-materialize: https://github.com/InfomediaLtd/angular2-materialize/blob/master/app/components/chips.ts

@n0mid unfortunately, there's no support for ngModel with chips. It's a custom MaterializeCSS component and it doesn't support two way binding out of the box. I'll add a separate issue to support that somehow. You're welcome to implement this support and create a PR, if you wish to help and contribute.

**Comment by hugocalheira** [comment]
How to reset/redefine chips init?

**Comment by westwick** [comment]
I'm also trying to find a way to reset chips init

**Comment by rubyboy** [comment]
@hugocalheira @westwick see here: https://github.com/InfomediaLtd/angular2-materialize/issues/327#issuecomment-317161588

```html
<div class="chips" materialize="material_chip" [materializeParams]="[chipsInit]" [materializeActions]="chipsActions"></div>
<a class="waves-effect waves-light btn" (click)="updateChips()">Update Chips</a>
```
```js
chipsActions = new EventEmitter<string|MaterializeAction>();
  updateChips() {
    const newChipsInit = {
      data: [{
        tag: 'Apple2',
      }, {
        tag: 'Google2',
      }],
    }
    this.chipsActions.emit({action:"material_chip",params:[newChipsInit]});
  }
```
