### ISSUE TITLE
Testing error when adding Materialize bindable properties.

### ISSUE THREAD

**Issue by pabloFuente** [InfomediaLtd/angular2-materialize#123]
When adding _[materializeActions]_, _[materializeParams]_ or _[materializeSelectOptions]_ to component templates, fatal errors show up when testing.

Maybe is just an "import" problem, but the other materialize directives work properly (the moment those binding properties are removed the tests work just fine).

Error:
`Chrome 53.0.2785 (Linux 0.0.0) login-modal component without overriding should have Welcome Title FAILED Can't bind to 'materializeActions' since it isn't a known property of 'div'. ("<div id="modal" class="modal" materialize [ERROR ->][materializeActions]="actions"> <div class="modal-content"> "): LoginModalComponent@0:42`

**Comment by rubyboy** [comment]
Have you added MaterializeDirective to the declarations of your NgModule? Please try the latest version (5.2.0) that if fully compatible to the latest version of angular2.
If it's still not working for you, take a look at the example app in the angular2-materialize repository. Try running it. Does that one work for you?

**Comment by pabloFuente** [comment]
I have the latest 5.2.0 version of the library. MaterializeModule is imported in my NgModule (app.module.ts):
```
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    MaterializeModule,
    routing,
  ],
```
My project is an angular-cli project, and running _ng test_ just makes those errors appear. Obviously, if I try to import or declare again MaterializeModule or MaterializeDirective inside my .spec files, Chrome throws a duplicated importing error, so that means it has correctly imported MaterializeDirective through MaterializeModule  in the NgModule.

I can perfectly run the example app in the angular2-materialize repository. I don't see any test to run in it, though.

My component.spec.ts file is basically this one:
```
...
describe('navbar component', () => {
   beforeEach(() => {
      TestBed.configureTestingModule({
         declarations: [NavbarComponent],
         providers: [{ provide: AuthenticationService, useClass: MockAuthenticationService }]
     });
   });
   describe('without overriding', () => {
      beforeEach(async(() => {
        TestBed.compileComponents();
       }));
       it('should have Sign up and Log in buttons', async(() => {
         let fixture = TestBed.createComponent(NavbarComponent);
         fixture.detectChanges();
         let compiled = fixture.debugElement.nativeElement;
         expect(compiled).toContainText('Sign up');
         expect(compiled).toContainText('Log in');
    }));
...
```

**Comment by rubyboy** [comment]
@sh4d0000 has provided [here](https://github.com/InfomediaLtd/angular2-materialize/issues/113) a link to his repository with example of angular2-materialize with the CLI: https://github.com/pragdev/angular_example 
Take a look and see if it's got tests that resemble yours and if there's a hint there to the setup.
I hope that helps.

**Comment by pabloFuente** [comment]
Thank you, but there are no tests with Materialize bindable properties there.
I'll try to figure this out. If I make it, I will post my solution here.
In the meantime, I will just test services and components without those attributes in their HTML.

**Comment by ammuench** [comment]
I'm running into the same issues as @pabloFuente here.  Whenever I import the library into a `*.spec.ts* file I get the duplicated importing error as stated above

**Comment by CNSKnight** [comment]
This should be related to my non-test scenario where eg [MaterializeParams] is not found in component templates of a module imported by a parent module that contains the import and declaration. The typical error thrown is:
```Error:
Template parse errors:
Can't bind to 'materializeParams' since it isn't a known property of 'a'. ("modal-trigger" materialize="leanModal" [ERROR ->][materializeParams]="[{dismissible: true, starting_top:'1%', ending_top: '3%'}]" href="#rPrevModal">P"):
```

**Comment by pabloFuente** [comment]
I finally investigated the problem and it had (as it usually has...) a pretty silly solution.

In `karma.conf.js` file, **files** attribute needed to be extended from


    files: [
      { pattern: 'node_modules/jquery/dist/jquery.js', watched: false},
      { pattern: 'node_modules/materialize-css/dist/js/materialize.js', watched: false},
      { pattern: './src/test.ts', watched: false}
    ],

**Comment by atwoodhouse** [comment]
In my case I had missed adding MaterializeModule to imports, at @NgModule, in app.module.ts.
Make sure to double check all the installation steps for angular2-materialize. Solved it for me!

**Comment by gnavneet2007** [comment]
@pabloFuente , The working solution is here
1. change  "materialize-css": "^0.100.1" in package.json
2. run npm install
That's it
