### ISSUE TITLE
Material Box reloading not working

### ISSUE THREAD

**Issue by aaronfdes** [InfomediaLtd/angular2-materialize#125]
The following code works when i load the component for the first time. However when i navigate away and come back to the page, it stops working. Clicking the image does nothing. There are no errors in the console as well. 

If i reload the page using the browser reload button it works again for the first time. Navigating through the application still causes the problem to occur.

```html
<div class="card-image">
<img class="materialboxed" materialize="materialbox" src="...path to url on server...">
</div>
```

If it matters im using angular-cli

**Comment by rubyboy** [comment]
@aaronfdes are you able to check if this is still happening with the latest version?
I tried reproducing, but it seems to work well.

```html
<img materialize="materialbox" width="650" src="http://materializecss.com/images/sample-1.jpg">
```

I'll close this issue for now, but if you find that it's till a problem we can reopen.
Thanks.
