### ISSUE TITLE
Issue trying to contribute 

### ISSUE THREAD

**Issue by AAAnderson7301** [InfomediaLtd/angular2-materialize#126]
Hello, I forked the repo and am trying to contribute to submit a pr for AOT support. I am getting an error just trying to do gulp tsc on a clean project. Getting an error with zone.js. "/zone.js.d.ts' is not a module." Do you have the same issue?

**Comment by rubyboy** [comment]
@AAAnderson7301 I'm seeing these as well. It's weird as they don't show when running "tsc" outside of gulp.
But the build itself completes successfully, so it shouldn't be a blocker (although, would be great to fix any TS compilation error).

**Comment by AAAnderson7301** [comment]
@rubyboy  What command should I be running to do a build ? Sorry I am new to contributing

**Comment by rubyboy** [comment]
Not a problem at all. Thanks for offering to contribute! :)

To run the distribution step you should run "npm run dist", which runs the whole gulp script. It should create the distribution into the /dist folder. It should contain just the "js" and "d.ts" files that would be used in other projects.
The project also includes commitizen, so you can use "npm commit" to check in with a structured comment. You don't have to - I'll do that anyway when merging your PR.

BTW, you don't actually need to run the distribution step, unless you want to test that it works. The build flow (commit+TravisCI publish to NPM) does that. You'll get an email from TravisCI if you check in errors :)

**Comment by AAAnderson7301** [comment]
Thank you
