### ISSUE TITLE
Visual bug when dynamic content is added inside collapsible-body.

### ISSUE THREAD

**Issue by pabloFuente** [InfomediaLtd/angular2-materialize#128]
I dynamically instantiate some **accordion** components using ngFor. Their internal content has different sizes (in fact, I have some tabs inside of them).
The problem can be totally understood with this example:

![ezgif-3628228522](https://cloud.githubusercontent.com/assets/15049534/19096503/2ac71f70-8a9d-11e6-9d3c-ea266e42094b.gif)

The accordion seems to initiate the animation with the **height of the previous opened accordion**. If it's lower than the next one, the animation ends half its way, and if it's higher it ends too far.

Anyway, that looks pretty ugly while in other cases when there aren't changes in height involved it looks nice and smooth (I have tested this component from top to bottom). I don't think this a misused of the component, just a bug. Any idea?

_PS: The same problem appears when instead of a tab component I simply add two different views controlled by a binary *ngIf, activated and deactivated via button. Changing the view just collapses the unfold effect of the accordion. And all data is correctly instanciated before each animation, I have considered that._

**Comment by rubyboy** [comment]
@pabloFuente could you confirm if this also happens with vanilla MaterializeCSS (http://materializecss.com/getting-started.html) or just when you have the angular2-materialize bindings? Thanks.

**Comment by pabloFuente** [comment]
Ok, I have tested this situation with no Angular, no angular-cli, no binding involved:

- **Pure HTML and CSS**, no dynamic content with different collapsible-body heights:

![collapsible no dynamic](https://cloud.githubusercontent.com/assets/15049534/19112500/64e4cc4e-8b05-11e6-8748-7ccee95a139f.gif)
Obviously, no problem here.

- **Dynamic content** inside first collapsible body with a little of jQuery:

![collapsible dynamic](https://cloud.githubusercontent.com/assets/15049534/19112528/9a300eb8-8b05-11e6-977a-a63698d6773d.gif)
No bug here. Although the height of the content is being modified in real time, there are no visual problems.
Those tabs are hardcoded, by the way. There's nothing similar to ngFor in this example. But I have compared the final HTML in my angular2-materialize project and in this simple example and there are no substantial differences in structure between both of them (unique identifiers for every couple [tab-header, tab-content], etc...).

Just to be clear, if the bug would had occured, it would have been _when I change first tab content clicking the button and inmediately I click second collapsible_. I do exactly that in this example but everything is correct.

**Comment by pabloFuente** [comment]
Doing some research, this is probably related to the impossibility of creating animations from _0_ to _auto_ heights or widths. I don't know how materialize faces this problem, but I am pretty sure CSS limited animations has something to do with it.
