### ISSUE TITLE
materializeActions sidenav

### ISSUE THREAD

**Issue by sqwk** [InfomediaLtd/angular2-materialize#129]
What do I need to emit using the materializeActions eventemitter to get a sidenav to open or show? I tried `this.sidenavActions.emit('sideNav(\'show\')');` and  `this.sidenavActions.emit(['sideNav', 'show']));`

**Comment by rubyboy** [comment]
The actions are separate to the params. Try putting the params in [materializeParams]="theParams".
You can even have the sideNav in "magerialize="sideNav" and the params will start with theParams=["hide"]. Then, when you want to show it you can update theParams=["show"].

**Comment by mischelebuha** [comment]
How can I set "closeOnClick: true"?
So that the SideNav is closed with a click on a router link?

**Comment by rubyboy** [comment]
Pass it as a param: [materializeParams]="[{closeOnClick:true}]".
I think it should work similar to dialogs. See dialog example here: https://github.com/InfomediaLtd/angular2-materialize/blob/master/app/components/dialogs.ts

**Comment by sqwk** [comment]
The following works:

    this.sidenavActions = new EventEmitter<any>();
    this.sidenavParams = [];

    public showSidenav(): void {
        this.sidenavParams = ['show'];
        this.sidenavActions.emit('sideNav');
    }

    <div (click)="showSidenav()" id="welcome">Another sidenav trigger</div>
    <div id="sidenav" class="side-nav"></div>

    <a materialize="sideNav" [materializeParams]="sidenavParams" [materializeActions]="sidenavActions" data-activates="sidenav" class="btn-floating btn-flat waves-effect waves-light transparent" (click)="hideWelcome = true">
        <i class="material-icons">menu</i>
    </a>

**Comment by rubyboy** [comment]
@sqwk thanks.
I've also created the following issue to make it easier to emit actions that have params: https://github.com/InfomediaLtd/angular2-materialize/issues/130

**Comment by rubyboy** [comment]
FYI, the latest version of angular2-materialize supports sending params when emitting actions.

**Comment by bigggge** [comment]
I want close the sideNav but the code not working,plz help me
```
    sidenavActions = new EventEmitter<any|MaterializeAction>();
    closeSideNav() {
            this.sideNavActions.emit({action: "sideNav", params: ['hide']});
    }
```
html
```
<li class="bold" routerLinkActive="active">
                    <a routerLink="/moments" (click)="closeSideNav()" class="waves-effect waves-cyan">
                        <i class="material-icons">event</i>Moments</a>
                </li>
```

**Comment by bigggge** [comment]
I found when it is large screen ,it can‘t hide
when it is small screen like phone it can hide.

**Comment by pnishank** [comment]
@bigggge in my case it hides on large screens too here is my sideNav code
`<nav>
    <div class="nav-wrapper">
      <a href="#!" class="brand-logo">Logo</a>
      <a href="#" materialize="sideNav" data-activates="slide-out"
         [materializeParams]="[{edge:'left',closeOnClick:true}]" class="button-collapse"><i
        class="material-icons">menu</i></a>
      <ul id="slide-out" class="side-nav fixed">
        <li class="logo"><a [routerLink]="['/']">Home</a></li>
        <li><a [routerLink]="['/login']" class="collapsible-header" *ngIf="!auth.validToken()">Login</a></li>
        
        <li class="no-padding" *ngIf="auth.validToken()">
          <ul class="collapsible collapsible-accordion">
            <li class="bold"><a class="collapsible-header  waves-effect waves-teal">Markets</a>
              <div class="collapsible-body">
                <ul>
                  <li><a [routerLink]="['/markets']">List</a></li>
                  <li><a [routerLink]="['/market/new']" *ngIf="auth.checkCurrentUserType('admin')">New</a></li>
                </ul>
              </div>
            </li>
          </ul>
        </li>
....`

**Comment by mathwww** [comment]
I've been facing a similar problem, when I change the "theParams" value to ['hide'] it does not hide the nav bar
