### ISSUE TITLE
date picker closeOnSelect?

### ISSUE THREAD

**Issue by sudharsantk** [InfomediaLtd/angular2-materialize#135]
Hi team,
  is date picker's closeOnSelect: true option supported?

**Comment by rubyboy** [comment]
Not sure if MaterializeCSS supports it. Their documentation (http://materializecss.com/forms.html) says "At this time, not all pickadate.js options are working with our implementation". Need to test.
Can you try with vanilla MaterializeCSS? If it works there and not with angular2-materialize let us know. Thanks.

**Comment by rubyboy** [comment]
Seems like MaterializeCSS isn't supporting it. I suggest opening an issue on the MaterializeCSS repository.

Here's the HTML I tested this feature:
```html
<html>
  <head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
  </head>
  <body>
      <input type="date" class="datepicker"></br>
    <script>
      $(document).ready(function() {
        $('.datepicker').pickadate({
          closeOnSelect: true
        });      
      });
    </script>
  </body>
</html>
```

**Comment by rubyboy** [comment]
https://github.com/Dogfalo/materialize/pull/3321

**Comment by sudharsantk** [comment]
Thank you ruby boy, I already contacted them

----- Reply message -----
