### ISSUE TITLE
Unexpected close of select with multiple option 

### ISSUE THREAD

**Issue by ArThoX** [InfomediaLtd/angular2-materialize#136]
Hi

I want the user to be able to select multiple numbers in a 1 to 100 sequence. That selection would be mirrored in the `counts` variable.

Concretely `counts` is the ngModel of the select that is `multiple` and contains a `ngModelChange` callback that allows me to do my logic after the selection change.

This works, however, the UI interaction seems broken:

- Clicking the first `option` directly closes the `select`'s panel (unexpected).
- Clicking the other `option` works as expected (panel not closed, option ticked or unticked)

What coule be wrong ?
(I was not able to build a plunkr, if you have one with angular2-materialize working I'd try to reproduce...)

Regards

```
  <div class="row">
    <div class="input-field col s4">
      <select [(ngModel)]="counts" (ngModelChange)="onCountChange($event)" materialize="material_select" multiple>
        <option value="" disabled selected>Please pick</option>
        <option value="1">one</option><!-- Clicking that option has an unexpected behavior -->
        <option value="2">two</option>
         ....
        <option value="100">onehundred</option>
      </select>
      <label>Count</label>
    </div>
  </div>
```

**Comment by rubyboy** [comment]
The problem is with the following logic:
```js
    public ngDoCheck() {
      const nativeElement = this._el.nativeElement;
      if (this.isSelect() && nativeElement.value!=this.previousValue) {
        // handle select changes of the model
        this.previousValue = nativeElement.value;
        this.performLocalElementUpdates();
      }
      return false;
    }
```
When ```this.performLocalElementUpdates``` is called the dropdown closes.
Also, multi select ngModel doesn't work because it dispatched an "input" event, while "change" is required.

I'll update the code to always dispatch "change", for both single and multi select, and add a check for "multi" during ngDoCheck to avoid calling ```performLocalElementUpdates```.

**Comment by rubyboy** [comment]
@ArThoX please test the latest version [5.2.1](https://www.npmjs.com/package/angular2-materialize) and let us know if this is solved.

**Comment by ArThoX** [comment]
@rubyboy 
Confirmed, working with 5.2.1.
