### ISSUE TITLE
Update project to ng2 final?

### ISSUE THREAD

**Issue by pchristou** [InfomediaLtd/angular2-materialize#138]
Apologies if this is a silly question but in order to update the angular2-materialize project from rc5 to angular 2 final, is it simply a matter of updating the dependencies in package.json then running an npm install?

Would appreciate some input before I invest time working on this...

**Comment by rubyboy** [comment]
Yes, I think so. Look at the example project in the repository. It's all using the final version.

**Comment by pchristou** [comment]
@rubyboy wasn't straightforward but I got there in the end. I basically used the angular starter as the base and then applied the latest angular2-materialize release on the top. All updated from RC5 to 2.0.1.

Thanks!
