### ISSUE TITLE
Can't pass variable to tooltip

### ISSUE THREAD

**Issue by MilosStanic** [InfomediaLtd/angular2-materialize#14]
Hi, 
I've been trying to pass a variable to a tooltip. It just renders the variable name, not value. If I pass it within double curly brackets, Angular reports an error. 

Any solution?

**Comment by rubyboy** [comment]
@MilosStanic , you can bind custom properties using the [attr.propertyName](https://angular.io/docs/ts/latest/cheatsheet.html) syntax.

Here's an example of binding a tooltip text to a property called ```tooltipText``` :
```js
<a materialize="tooltip" class="btn tooltipped" [attr.data-tooltip]="tooltipText">Hover me!</a>
```

I've updated the example code in the project to have this syntax as well, for future reference: https://github.com/InfomediaLtd/angular2-materialize/blob/master/app/components/dialogs.ts#L24

Hopefully this would work for you. Thanks for bringing this up - I'm sure it would help other developers.

**Comment by MilosStanic** [comment]
Thanks, it works. Although I wanted to pass the value through a pipe like: 
`{{item.price | currency: LMEs.currency}}` and display that in a tool tip, but this is good enough.

**Comment by rubyboy** [comment]
Pipes should work as well. Try this (I used the built-in "date" pipe):
```js
@Component({
    selector: "dialogs",
    directives: [MaterializeDirective],
    template: `<a materialize="tooltip" class="btn tooltipped" data-position="bottom" data-delay="50" [attr.data-tooltip]="tooltipText | date:'MM/dd/yy'">Hover me!</a>`
})
export class Dialogs {
  tooltipText = new Date();
}
```

![image](https://cloud.githubusercontent.com/assets/1908166/14128344/cae21008-f66b-11e5-82b5-665d8cd86392.png)

**Comment by AndrewWeb-Dev** [comment]
I'm running into a similar issue. I am trying to pass the current value of my variable into the ```data-tooltip``` attribute of my element. The value of the variable changes based on my switch case condition which is triggered by an event binding on the same element.

```
 gridView: boolean = true;
  tooltipText: string;

  ngOnInit() {

  	this.tooltipText = "List View"

  }
  
  viewToggle(e) {

  	this.gridView = !this.gridView;

  	switch (this.gridView) {
  		case true: 
  			// code...
  			e.target.innerHTML = "view_list";
  			this.tooltipText = "List View";
  			break;
  		case false: 
  			// code...
  			e.target.innerHTML = "view_module";
  			this.tooltipText = "Grid View";
  			break;
  	}
  	

  }
```

Here is my template

```
<i #viewSwitcher class="material-icons hoverable z-depth-2" role="button" materialize="tooltip" [(attr.data-tooltip)]="tooltipText" (click)="viewToggle($event)">view_list</i>
```

**Comment by Akitha** [comment]
This is All you need

`matTooltip={{variable}}`
