### ISSUE TITLE
collapsible, Dropodown not working 

### ISSUE THREAD

**Issue by prgwar** [InfomediaLtd/angular2-materialize#141]
When I try to use collapsible and dropdown its closing immediately after opening please help me to resolve this 
i have included the materialize="collapsible"  directive and other features are working perfect

![c collapsible](https://cloud.githubusercontent.com/assets/11192559/19484967/258cb8a0-9577-11e6-9520-8342c82a9532.gif)

**Comment by rubyboy** [comment]
Does this also happen to you in the example app that exist in the repository?
You can also check http://angular2-materialize.surge.sh/#/Collapsible

If that's not reproducible there then we'll need more info on how you use it and your setup as it will be related to that.

**Comment by apimobi** [comment]
@prgwar did you find the solution?
I have the same problem.

**Comment by prgwar** [comment]
I had the same problem in pragdev,  example , I tried out the new version angular2-materialize still facing the problem

**Comment by rubyboy** [comment]
@apimobi @prgwar to confirm, this is happening to you here? http://angular2-materialize.surge.sh/#/Collapsible
Are you able to provide the OS and browser versions you're using?
Thanks.

**Comment by apimobi** [comment]
@rubyboy  no problem on  http://angular2-materialize.surge.sh/#/Collapsible for me.
It should be a problem in our config.

**Comment by bruha** [comment]
Same problem for me. Works fine on http://angular2-materialize.surge.sh/#/Collapsible
Has anybody solved it?

**Comment by omar27** [comment]
I'm facing same issue. Any solution?

**Comment by apimobi** [comment]
hi,

If you remove  : import "materialize-css";
from app.module.ts it's working

maybe you should remove from installation guide in
Installing & configuring angular2-materialize in projects created with angular-cli@webpack (1.0.0-beta.11-webpack.8)

**Comment by rubyboy** [comment]
@allahbaksh would you be able to comment on this, if it's necessary to remove that import?

**Comment by allahbaksh** [comment]
@rubyboy Yes it should be removed.

**Comment by rubyboy** [comment]
I've updated the documentation.
@prgwar are you able to you confirm this fixes the problem? Thanks.

**Comment by netfish88** [comment]
but there is issue when you remove the  _import "materialize-css";_

for example. 

```
<div materialize="carousel" [materializeParams]="[{full_width: true}]" class="carousel carousel-slider center" data-indicators="true">
    <div class="carousel-fixed-item center">
        <a class="btn waves-effect white grey-text darken-text-2">button</a>
    </div>
    <div class="carousel-item red white-text" href="#one!">
        <h2>First Panel</h2>
        <p class="white-text">This is your first panel</p>
    </div>
    <div class="carousel-item amber white-text" href="#two!">
        <h2>Second Panel</h2>
        <p class="white-text">This is your second panel</p>
    </div>
    <div class="carousel-item green white-text" href="#three!">
        <h2>Third Panel</h2>
        <p class="white-text">This is your third panel</p>
    </div>
    <div class="carousel-item blue white-text" href="#four!">
        <h2>Fourth Panel</h2>
        <p class="white-text">This is your fourth panel</p>
    </div>
</div>

<ul materialize="collapsible" class="collapsible" data-collapsible="accordion">
    <li>
        <div class="collapsible-header"><i class="material-icons">filter_drama</i>First</div>
        <div class="collapsible-body"><p>Lorem ipsum dolor sit amet.</p></div>
    </li>
    <li>
        <div class="collapsible-header"><i class="material-icons">place</i>Second</div>
        <div class="collapsible-body"><p>Lorem ipsum dolor sit amet.</p></div>
    </li>
    <li>
        <div class="collapsible-header"><i class="material-icons">whatshot</i>Third</div>
        <div class="collapsible-body"><p>Lorem ipsum dolor sit amet.</p></div>
    </li>
</ul>
```
if you include the materialize-css, only carousel works.
and if you exclude it. only collapsible works. 

I can't find the difference between config on my project and demo own.

**Comment by rodz-dev** [comment]
I had the same issued with the dropdown. The solution that is working for me is in the index page i have imported the materialize.min.js before the jquery.min.js and it solved the problem

**Comment by drapadubok** [comment]
For me solution by rodz-dev worked, but materialize.min.js complains about 
Uncaught ReferenceError: $ is not defined at materialize.min.js:6 
(doesn't create any problems), but not looking nice.

**Comment by bigghe** [comment]
For me that solution don't work, I still have problem with collapsible.
If I refresh the page and then navigate to the component (ng2) where the collapsible element are located, they don't work.
BUT if I refresh the page when I'm on collapsible's component, then they work. 
Can you help me?

**Comment by rodz-dev** [comment]
Just to comment I am using angular cli and I am not longer using in the index page for these solutions. I am just using npm to install jquery and materialize for angular 2. It is working fine and not issues. Basically I am not importing anything in my index page

**Comment by bigghe** [comment]
I solved this with 

    declare var $: any;

after all the imports on my component and then

    ngAfterViewInit() {
        $( '.collapsible' ).collapsible();
    }

**Comment by akashbiz** [comment]
Hello @bigghe, this simple hack worked for me, but still I think there should be some method written @rubyboy in materializeAction so that we can use that method to open and close collapsible programatically.

Thanks.

**Comment by rubyboy** [comment]
@akashbiz see below an example of programmatic collapsible.
Does the original problem @prgwar reported with the auto-closing collapsible still happen with the latest version of angular2-materialize? Anyone can share a repo where that's happening?

```js
import {MaterializeDirective, MaterializeAction} from "angular2-materialize";
import {Component, EventEmitter} from "@angular/core"

@Component({
    selector: "collapsible",
    template: `
        <a class="waves-effect waves-light btn" (click)="openFirst()">Open First</a>
        <a class="waves-effect waves-light btn" (click)="closeFirst()">Close First</a>
        <br/><br/>
        <ul materialize="collapsible" class="collapsible" data-collapsible="accordion" [materializeParams]="params" [materializeActions]="actions1">
          <li>
            <div class="collapsible-header"><i class="material-icons">filter_drama</i>First</div>
            <div class="collapsible-body"><p>Lorem ipsum dolor sit amet.</p></div>
          </li>
          <li>
            <div class="collapsible-header active"><i class="material-icons">place</i>Second</div>
            <div class="collapsible-body"><p>Lorem ipsum dolor sit amet.</p></div>
          </li>
          <li>
            <div class="collapsible-header"><i class="material-icons">whatshot</i>Third</div>
            <div class="collapsible-body"><p>Lorem ipsum dolor sit amet.</p></div>
          </li>
        </ul>
        <br/><br/>
        <ul materialize="collapsible" class="collapsible" data-collapsible="accordion">
          <li *ngFor="let value of values">
            <div class="collapsible-header">{{value}}</div>
            <div class="collapsible-body"><p>{{value}}</p></div>
          </li>
        </ul>
    `
})
export class Collapsible {

    actions1 = new EventEmitter<string|MaterializeAction>();


    params = [
      {
        onOpen: (el) => {
          console.log("Collapsible open", el);
        },
        onClose: (el) => {
          console.log("Collapsible close", el);
        }
      }
    ];

    values = ["First", "Second", "Third"];

    openFirst() {
      this.actions1.emit({action:"collapsible",params:['open',0]});
    }

    closeFirst() {
      this.actions1.emit({action:"collapsible",params:['close',0]});
    }
}
```

**Comment by akashbiz** [comment]
This worked well. Thanks @rubyboy

**Comment by rubyboy** [comment]
Thanks for the quick response. Closing this issue now.

**Comment by marciomsm** [comment]
@rubyboy I want to load with all items opened, but it is not working. Do you have any idea if is missing something in my code?

```
    <ul class="collapsible" data-collapsible="expandable" materialize="collapsible">
      <li>
        <div class="collapsible-header active">First<i class="material-icons right">&#xE316;</i></div>
        <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
      </li>
      <li>
        <div class="collapsible-header active">Second<i class="material-icons right">&#xE316;</i></div>
        <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
      </li>
      <li>
        <div class="collapsible-header active">Third<i class="material-icons right">&#xE316;</i></div>
        <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
      </li>
    </ul>
```

Thanks.

**Comment by rubyboy** [comment]
@marciomsm code looks fine. Here's a plunker with your code that expands them all: https://plnkr.co/edit/7zzyx1S7B7O7G6uLUj40?p=preview

**Comment by marciomsm** [comment]
@rubyboy thank you very much, I already fixed it. I just updated the angular2-materialize to the last version.

**Comment by mmisumi-ciandt** [comment]
@rubyboy do you know if we have some way to render collapsible opened when we use ngFor? I am getting the data from server.

```
<ul class="collapsible" data-collapsible="expandable" materialize="collapsible">
      <li  *ngFor="let data of list">
        <div class="collapsible-header active">{{data.title}}<i class="material-icons right">&#xE316;</i></div>
        <div class="collapsible-body"><span>{{data.name}}</span></div>
      </li>
    </ul>
```

**Comment by marciomsm** [comment]
@rubyboy do you know if we have some way to render collapsible opened when we use ngFor? I am getting the data from server.

```
<ul class="collapsible" data-collapsible="expandable" materialize="collapsible">
      <li  *ngFor="let data of list">
        <div class="collapsible-header active">{{data.title}}<i class="material-icons right">&#xE316;</i></div>
        <div class="collapsible-body"><span>{{data.name}}</span></div>
      </li>
    </ul>
```

**Comment by C0rporeus** [comment]
> Resolví esto con
> 
> ```
> declare var $: any;
> ```
> después de todas las importaciones en mi componente y luego
> 
> ```
> ngAfterViewInit() {
>     $( '.collapsible' ).collapsible();
> }
> ```

Llevaba eones tratando de solucionar esto... gracias... (pense que estaban usando vanillaJs pero aun hay dependencia de Jquery)
