### ISSUE TITLE
Angular CLI - cannot find module jquery

### ISSUE THREAD

**Issue by bliitzkrieg** [InfomediaLtd/angular2-materialize#144]
I followed the guide for angular CLI `Installing & configuring angular2-materialize in projects created with angular-cli@webpack` on `v1.0.0-beta.18` and I keep getting errors:

```
Uncaught Error: Cannot find module 'jquery'
Uncaught TypeError: Cannot read property 'swing' of undefined
```

 I am not sure how to resolve it. I see the jquery and materialize-css in my `scripts.bundle.js` but an error is still being thrown.

**Comment by rubyboy** [comment]
This helps? https://github.com/InfomediaLtd/angular2-materialize/issues/111#issuecomment-256531546
(downgrading CLI to beta-15)

**Comment by kazkis** [comment]
hi @bliitzkrieg , I'm using this package without any problem with the latest `angular-cli` version (`v1.0.0-beta.18`). I didn't follow the guide here, because I think it does some unnecessary steps for me.

This is what I've done, just be sure to try it in a new clean project:

1 - install materialize-css and angular2-materialize

```
npm install materialize-css --save
npm install angular2-materialize --save
```

2 - add styles and scripts in angular-cli.json

```
"styles": [
   "styles.css",
   "../node_modules/materialize-css/dist/css/materialize.css"
],
"scripts": [
   "../node_modules/jquery/dist/jquery.js",
   "../node_modules/materialize-css/dist/js/materialize.js"
],
```

3 - Import MaterializeModule in app.module.ts

```
import { MaterializeModule } from 'angular2-materialize';

@NgModule({
   declarations: [ AppComponent ],
   imports: [
      BrowserModule,
      FormsModule,
      HttpModule,
      MaterializeModule
   ],
```

4 - Add this line at the end of the header of index.html

`<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">`

**Comment by ihabZhaika** [comment]
@kazkis 
i tried your way . but still get this error now
`Uncaught TypeError: Cannot read property 'swing' of undefined
`

**Comment by rubyboy** [comment]
@ihabZhaika did you try angular-cli 1.0.0-beta.17 and using a minified jQuery?
I haven't really used the CLI, so I'm only extracting this info from past issues and how people solved them.

**Comment by ihabZhaika** [comment]
@rubyboy
hi,
yes i saw all the issues here that talk about it
i tried beta 15 , 17 ,18 ,19-3
if use the minified i get k.velocity error

**Comment by rubyboy** [comment]
@ihabZhaika does it also happen to you on the project CLI project? https://github.com/pragdev/angular_example

**Comment by ihabZhaika** [comment]
@rubyboy
For this repo the answer is : no , but i get
`Module '"/home/ihab/WebstormProjects/tesss/node_modules/angular2-materialize/dist/index"' has no exported member 'MaterializeAction'.
`

**Comment by rubyboy** [comment]
@ihabZhaika interesting, I don't see any code in that repo that uses MaterializeAction. Also, it's using version 5.2.1 of angular2-materialize, which haven't had MaterializeAction in it - that would explain the problem, if this project did have code that tries using MaterializeAction.
Can you point me at the code that causes this in that repo?
If it's your own code, you should first update the dependency of angular2-materialize in package.json to the latest version (6.x).

**Comment by chriscurnow** [comment]
I just seen half a day on this – but finally licked it. After trying lots of suggestions here I set up a new angular-cli project and used @kazkis instructions for installing. It worked in the new project.

Back to my project and nothing wanted to work.

I kept getting the error `TypeError: undefined is not an object (evaluating 'jQuery.easing.swing')`

Even when I deleted just about all the scripts from angular-cli.json (including materialise) and the imports in app.module it still gave this error.

I racked my brains to think of what I might have done that I needed to undo.

The answer was the following from the instructions:

`import "materialize-css";`
`import "angular2-materialize";`

**Comment by rubyboy** [comment]
If someone can confirm this is the correct approach I'm happy to update the docs (or receive a PR for the proper way to use the module in CLI based projects).

**Comment by NoMoreLoad** [comment]
@rubyboy I can configm. 
angular-cli 1.0.0-beta.26 (webpack 2.2.0 inside, with tree-shaking)
1. `npm install -g angular-cli`
2. `ng new PROJECT_NAME`
3. `cd PROJECT_NAME`
4. `npm install jquery@2 hammerjs materialize-css angular2-materialize --save`
5. Open _**angular-cli.json**_ with any text editor. 
5.1. Go to section _**apps**_ and find _**styles**_ array inside it (with only _styles.css_ value by default), add the following line inside array `../node_modules/materialize-css/dist/css/materialize.css` before any styles.
5.2. Go to section _**apps**_ and find _**scripts**_ array inside it, and add the following lines inside array
```
../node_modules/jquery/dist/jquery.js
../node_modules/hammerjs/hammer.js
../node_modules/materialize-css/dist/js/materialize.js
```
6. Go to **_src/app_** folder inside your project and open _**app.module.ts**_
6.1. Add `import { MaterializeModule } from 'angular2-materialize';` on top of the file
6.2 Add `MaterializeModule` inside **_imports_** array of _**@NgModule**_ decorator.
7. Go to project's root and run `ng build --prod --aot`
8. PROFIT!

**Comment by rubyboy** [comment]
@NoMoreLoad thanks heaps. I've updated the documentation based on your comment

**Comment by valiknet18** [comment]
@NoMoreLoad It didn't help resolve my problem. Error ```Uncaught TypeError: Cannot read property 'swing' of undefined``` still throwing. Link to my config file https://github.com/valiknet18/cdu-webchat-frontend/blob/master/angular-cli.json.
