### ISSUE TITLE
Angular-CLI AoT Unexpected value 'MaterializeModule' imported by the module 'MyCustomModule'

### ISSUE THREAD

**Issue by criticalbh** [InfomediaLtd/angular2-materialize#145]
When I try to compile the code using `ng build --aot` I get the following error:

```
0% compilingUnexpected value 'MaterializeModule' imported by the module 'MyCustomModule'
Error: Unexpected value 'MaterializeModule' imported by the module 'MyCustomModule'

```

**Comment by rubyboy** [comment]
Related to https://github.com/InfomediaLtd/angular2-materialize/issues/121 ?

**Comment by CNSKnight** [comment]
+1 - #dead-end???

**Comment by CNSKnight** [comment]
I've had this, and resolved by re-factoring out multiples of ``export class...`` - ie those unrelated to the target of @DeCorator eg @NgModule

**Comment by w3chtml** [comment]
@CNSKnight Can you please give more details how exactly you resolved it?

**Comment by CNSKnight** [comment]
@w3chtml - @criticalbh likely has an @NgModule script which also includes ``export class SomeOtherClass`` which confuses some part of the build. Have **only** the ``@NgModule`` and its target  ``export class...`` in the script file - no other class exports.
