### ISSUE TITLE
materializeParams not working for 'dropdown'

### ISSUE THREAD

**Issue by wceolin** [InfomediaLtd/angular2-materialize#148]
Apparently, `materializeParams` isn't working with `dropdown`. For example, the following has no effect:

```
<a materialize="dropdown" [materializeParams]="[{hover: true}]" class="dropdown-button" data-activates="dropdown1">
  Dropdown<i class="material-icons right">arrow_drop_down</i>
</a>
```

I tried the `modal` one and it worked fine. The issue is only with `dropdown`.

I'm using `angular2-materialize 5.2.1` with `angular-cli 1.0.0-beta.19-3`.

**Comment by rubyboy** [comment]
@wceolin thanks for reporting this issue.

I tried reproducing and indeed I see that it's not droping the dropdown when hovering.
Then, I tried reproducing it with MaterializeCSS itself and it's still not dropping. See code below.

Are you able to take a look and let me know if I'm doing (or expecting) something wrong or if indeed it's a MaterializeCSS issue that needs to be reported on their repository and not here? Thanks.

```html
<html>
  <head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
  </head>
  <body>
      <a class='dropdown-button btn' href='#' data-activates='dropdown1'>Drop Me!</a>

      <!-- Dropdown Structure -->
      <ul id='dropdown1' class='dropdown-content'>
        <li><a href="#!">one</a></li>
        <li><a href="#!">two</a></li>
        <li class="divider"></li>
        <li><a href="#!">three</a></li>
      </ul>

      <script>
        $(document).ready(function() {
          $('.dropdown-button').dropdown({
              hover: true
            }
          );    
        });
      </script>
  </body>
</html>
```

**Comment by rubyboy** [comment]
Confirmed it's a bug in MaterilizeCSS: https://github.com/Dogfalo/materialize/issues/3417

**Comment by rubyboy** [comment]
Fixed by upgrading the dependency to the latest MatrializeCSS that's just been released with a fix for this issue.
Version 6.0.0 of angular2-materialize has been released (there were breaking changes in Materialize so I've also bumped the angular2-materialize major version).
