### ISSUE TITLE
Upgrade to work with materialize-css 0.97.8

### ISSUE THREAD

**Issue by vesteraas** [InfomediaLtd/angular2-materialize#149]
v0.97.8 (October 30th)

- Refactored Modal plugin
- Tabs now supported in navbar
- Chips data can now be reinitiailized
- Minor side nav fixes
- FAB to toolbar component added
- Fixed dropdown options bug

**Comment by rubyboy** [comment]
Thanks for the heads up. Version 6.0.0 released (there were breaking changes in Materialize so I've also bumped the angular2-materialize major version).
