### ISSUE TITLE
Can't put it working =/

### ISSUE THREAD

**Issue by gustavobissolli** [InfomediaLtd/angular2-materialize#15]
Hi guys! I am new in Angular 2 and I am having some problems to use angular2-materialize on my Project!

I am not using webpack (barely know what is it) but I've installed all the dependencies though NPM (hammerjs, materialize and materialize-directive) and added manually the JS files on my index.html and I am facing this error:

`materialize-directive.js:10 Uncaught ReferenceError: require is not defined(anonymous function) @ materialize-directive.js:10
system.src.js:1085 XHR finished loading: GET "http://localhost:3000/src/main.js".fetchTextFromURL @ system.src.js:1085(anonymous function) @ system.src.js:1646ZoneAwarePromise @ angular2-polyfills.js:589(anonymous function) @ system.src.js:1645(anonymous function) @ system.src.js:2667(anonymous function) @ system.src.js:3239(anonymous function) @ system.src.js:3506(anonymous function) @ system.src.js:3888(anonymous function) @ system.src.js:4347(anonymous function) @ system.src.js:4599(anonymous function) @ system.src.js:337ZoneDelegate.invoke @ angular2-polyfills.js:332Zone.run @ angular2-polyfills.js:227(anonymous function) @ angular2-polyfills.js:576ZoneDelegate.invokeTask @ angular2-polyfills.js:365Zone.runTask @ angular2-polyfills.js:263drainMicroTaskQueue @ angular2-polyfills.js:482$ @ system-polyfills.src.js:1340H @ system-polyfills.src.js:1340R.when @ system-polyfills.src.js:1340T.run @ system-polyfills.src.js:1340t._drain @ system-polyfills.src.js:1340drain @ system-polyfills.src.js:1340e @ system-polyfills.src.js:1340`

Some one can help-me? 

My scripts:
`
<script src="node_modules/angular2/bundles/angular2-polyfills.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>
    <script src="node_modules/rxjs/bundles/Rx.js"></script>
    <script src="node_modules/angular2/bundles/angular2.dev.js"></script>
    <script src="node_modules/angular2/bundles/router.dev.js"></script>

    <script src="bower_components/jquery/dist/jquery.js"></script>
    <script src="bower_components/jquery-ui/jquery-ui.js"></script>
    <script src="bower_components/bootstrap/dist/js/bootstrap.js"></script>
    <script src="node_modules/hammerjs/hammer.js"></script>
    <script src="node_modules/materialize-css/dist/js/materialize.js"></script>
`

Thanks in advance!

**Comment by rubyboy** [comment]
I suggest using [SystemJS](https://github.com/systemjs/systemjs).
If you don't want to bring that in then you'll need an implementation of require (either CommonJS or AMD). You can try loading [RequireJS](http://requirejs.org). I haven't tried it myself for this setup so I can't guarantee that it would work just by importing the RequireJS script, but it's worth trying.
If you can share your code (Github or attach) I'm happy to take a look and see if I can help with that.

**Comment by rubyboy** [comment]
Did you get it to work?
Maybe this can help: https://github.com/InfomediaLtd/angular2-materialize/issues/17

**Comment by rubyboy** [comment]
I've added some documentation on how to use it without JSPM or webpack. Just SystemJS.
