### ISSUE TITLE
Materialize displayEffect called before body is loaded

### ISSUE THREAD

**Issue by Misterweb** [InfomediaLtd/angular2-materialize#154]
Hello everyone,
I'm new to Materialize-css and his angular2 implementation.

I'm trying to make it work, but adding angular2-materialize package to my build provoke an exception at runtime.

`materialize.min.js:3110 Uncaught TypeError: Cannot read property 'addEventListener' of null(…)
h.displayEffect @ materialize.min.js:3110
18../materialize-directive @ index.js:12`

Note that i had to apply a beautifier to the code to see more clearly.

So i searched a little, and the exception is happening in materialize.js :
`h.displayEffect = function(b) {
            b = b || {}, "duration" in b && (j.duration = b.duration), j.wrapInput(i(".waves-effect")), "ontouchstart" in a && document.body.addEventListener("touchstart", g, !1), document.body.addEventListener("mousedown", g, !1)
        }`

Called from index.js (angular2-materialize) :
`Waves.displayEffect();`

When i'm debugging, i see that document.body is null when Waves.displayEffect() is called, while the regular materialize displayEffect call is done from a "DOMContentLoaded" event (where body is ok).
I'm doing something wrong ?

**Specs** 
"angular2-materialize": "^6.0.0",
"materialize-css": "^0.97.8",
"hammerjs": "^2.0.8",
"jquery": "^2.2.4"

Used in a gulp/browserify context.
Seen on Chrome and Edge (not tested on others)

Imports in index.html done like that :
`    
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    
    
    
    <link rel="stylesheet" href="statics/css/styles.css" media="screen,projection" />

    
    
    <script src="node_modules/core-js/js/shim.min.js"></script>
    <script src="node_modules/zone.js/js/zone.js"></script>

    <script src="node_modules/jquery/js/jquery.min.js"></script>   
    <script src="node_modules/materialize/js/materialize.min.js"></script>

    <script src="app/bundle.js"></script> 

    
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />`

Thanks for your help !

**Comment by rubyboy** [comment]
Do you have a body in your html document? This could be the problem.
If you do, try pushing the scripts (or at least the bundle script) to the bottom of the body)

**Comment by Misterweb** [comment]
Indeed, putting the bundle script at the end of the body resolved the issue, thanks for the tips !
