### ISSUE TITLE
Unexpected value 'MaterializeModule' imported by the module XyZ

### ISSUE THREAD

**Issue by CNSKnight** [InfomediaLtd/angular2-materialize#156]
I'm getting this, but only on a SystemJS build. Meanwhile may other experiencing on various stacks and therefore likely unrelated to angular2-materialize.
Just posting In case anyone has encountered and resolved.

**Comment by rubyboy** [comment]
Sounds very related to your setup. Do you have a solution?

**Comment by CNSKnight** [comment]
idk - Moved on to WebPack
