### ISSUE TITLE
Error: Unexpected value 'LangSwitcherComponent' exported by the module 'MultilingualModule'

### ISSUE THREAD

**Issue by CNSKnight** [InfomediaLtd/angular2-materialize#157]

**Comment by rubyboy** [comment]
@CNSKnight I have no idea how this related to angular2-materialize. Can you elaborate please?
If you know what needs to be fixed a PR would be very welcome :)

**Comment by CNSKnight** [comment]
@rubyboy sorry, idk how this ended up here either. you may safely delete.
