### ISSUE TITLE
Carousel doesn't update with *ngFor

### ISSUE THREAD

**Issue by apbetioli** [InfomediaLtd/angular2-materialize#159]
I followed this example and created a carousel with *ngFor. 
https://github.com/InfomediaLtd/angular2-webpack-starter

It only works when it is first rendered. When I add a new item to the list or replace the itens in the list, it doesn't show correctly. The carousel doesn't apply those transform styles to the new item. e.g.

A carousel-item div when the page is first rendered:

`<div _ngcontent-ixe-5="" class="carousel-item" style="z-index: 0; opacity: 1; display: block; transform: translateX(0px) translateX(0px) translateX(0px) translateZ(0px);">`

A carousel-item div added:

`<div _ngcontent-sqd-3="" class="carousel-item">`

**Comment by rubyboy** [comment]
I couldn't find a nice way to do that with MaterializeCSS as it's not built for dynamically updating the carousel. But, following the hack proposed here http://stackoverflow.com/questions/39398417/is-it-possible-to-dynamically-add-a-slide-to-an-existing-materialize-carousel I managed to do it.
See here example code: https://github.com/InfomediaLtd/angular2-materialize/blob/master/app/components/carousel.ts
