### ISSUE TITLE
Couldn't find materialize function ''modal'

### ISSUE THREAD

**Issue by Appsbender** [InfomediaLtd/angular2-materialize#161]
I tried all other directives like collapsible,tooltip, dropdown, tabs, material_select, sideNav... it works fine but in modal no luck of making it work.

 Correct me if I'm wrong, I tried to dig in the directives ([found here](https://github.com/InfomediaLtd/angular2-materialize/blob/master/src/materialize-directive.ts)) but I couldn't see the modal function... I think it is missing?

**Comment by rubyboy** [comment]
@Appsbender are you using the latest MaterializeCSS? This function was introduced only in the latest version (previously is was called "leanModal".
The code is here: https://github.com/Dogfalo/materialize/blob/master/js/modal.js#L174

**Comment by sheeput** [comment]
@Appsbender  - not sure if you got this resolved.   I had the problem and it was something simple (and dumb I forgot).  I forgot to update my CSS to 0.97.8.

**Comment by Appsbender** [comment]
@rubyboy and @sheeput  : It's already been resolved. Thanks for the quick reply.
