### ISSUE TITLE
textarea autoresize when changing content dynamically

### ISSUE THREAD

**Issue by awexfwex** [InfomediaLtd/angular2-materialize#163]
As per http://materializecss.com/forms.html#textarea , you need to trigger the "autoresize" event manually when updating textareas programmatically.

**Comment by rubyboy** [comment]
@awexfwex thanks for the note. A PR would be wonderful, if you're interested in contributing - more than happy to provide guidance on how to do that.
Cheers.

**Comment by rubyboy** [comment]
@awexfwex thanks heaps for fixing this.
Are you able to confirm this has been fixed in the latest released version and close the issue?

**Comment by awexfwex** [comment]
No, the previous pull request wasn't properly detecting changes for all scenarios. It was working for my specific scenario, but #172 addresses this.

Are there any automated tests?

**Comment by rubyboy** [comment]
There aren't any at the moment. I had a few a while ago, but after having some trouble with TravisCI I omitted them. We do need some :)
Merging now, so you can test again.

**Comment by awexfwex** [comment]
I've given it some smoke tests, but nothing thorough. Seems fine.
