### ISSUE TITLE
Bug dynamic modal with text edit

### ISSUE THREAD

**Issue by tozik** [InfomediaLtd/angular2-materialize#165]
Hi there)
Thank you for your materialize for angular 2
We are use your library (for angular-2) with my friends
Us need a  modal, but we have trouble.
When we put in modal textedit, or any components, textedit doesn't works, you can see on the picture how.
label from textedit doesn't up, and when i try writing text, i'm not see him.
i can see only when it is allocated
can you help please, we lost many timy for find trouble)

................(click)="openModal()........

		
		<div id="modal1" materialize="modal" class="modal" [materializeParams]="[{dismissible: true}]" [materializeActions]="modalActions">
			<div class="modal-content">
				<div class="container">
					<div class="z-depth-1 grey lighten-4 row" style="display: inline-block; padding: 32px 48px 0px 48px; border: 1px solid #EEE;">

						<form class="col s12" method="post">
							<div class='row'>
								<div class='col s12'>
								</div>
							</div>

							<div class='row'>
								<div class='input-field col s12'>
									<input class='validate' type='email' name='email' id='email' />
									<label for='email'>Enter your email</label>
								</div>
							</div>

							<div class='row'>
								<div class='input-field col s12'>
									<input class='validate' type='password' name='password' id='password' />
									<label for='password'>Enter your password</label>
								</div>
								<label style='float: right;'>
								<a class='pink-text' href='#!'><b>Forgot Password?</b></a>
							</label>
							</div>

							<br />
							<div class='row'>
								<button type='submit' name='btn_login' class='col s12 btn btn-large waves-effect indigo'>Login</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>

		<side-menu></side-menu>
	</div>
`

![scr](https://cloud.githubusercontent.com/assets/18100033/20153639/c4f78866-a6d4-11e6-808e-799e974bdb16.png)

**Comment by rubyboy** [comment]
Sorry, not sure I understand the problem.

Here's the complete code I used to test:
```js
import {MaterializeDirective,MaterializeAction} from "../../src/index";
import {Component,EventEmitter} from "@angular/core"

@Component({
    selector: "dialogs",
    template: `
      <!-- Modal Trigger -->
      <a class="waves-effect waves-light btn modal-trigger" (click)="openModal()">Modal</a>

      <!-- Modal Structure -->
      <div id="modal1" materialize="modal" class="modal" [materializeParams]="[{dismissible: true}]" [materializeActions]="modalActions">
        <div class="modal-content">
          <div class="container">
            <div class="z-depth-1 grey lighten-4 row" style="display: inline-block; padding: 32px 48px 0px 48px; border: 1px solid #EEE;">

              <form class="col s12" method="post">
                <div class='row'>
                  <div class='col s12'>
                  </div>
                </div>

                <div class='row'>
                  <div class='input-field col s12'>
                    <input class='validate' type='email' name='email' id='email' />
                    <label for='email'>Enter your email</label>
                  </div>
                </div>

                <div class='row'>
                  <div class='input-field col s12'>
                    <input class='validate' type='password' name='password' id='password' />
                    <label for='password'>Enter your password</label>
                  </div>
                  <label style='float: right;'>
                    <a class='pink-text' href='#!'><b>Forgot Password?</b></a>
                  </label>
                </div>

                <br />
                <div class='row'>
                  <button type='submit' name='btn_login' class='col s12 btn btn-large waves-effect indigo'>Login</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    `
})
export class Dialogs {
  modalActions = new EventEmitter<string|MaterializeAction>();
  openModal() {
    this.modalActions.emit({action:"modal",params:['open']});
  }
  closeModal() {
    this.modalActions.emit({action:"modal",params:['close']});
  }
}
```

Here's what it looks like for me:

![modal](https://cloud.githubusercontent.com/assets/1908166/20167727/0249b580-a726-11e6-98f4-dfaf025de948.gif)

**Comment by tozik** [comment]
oo thank for faster answer, but on me doesn't works
if you put modal descryption in component will be work??

**Comment by tozik** [comment]
we are find problem
needed was put description modal, outside component navbar, and call modal from navbar
thanks

**Comment by rubyboy** [comment]
@tozik would you be able to post your code with the fix here?
Also, if this is fixed pleased close the issue. Thanks.

**Comment by csu6** [comment]
Hello,

I want the same, but the button that open the modal i want to put in header.component.ts 
` <a class="waves-effect waves-light btn modal-trigger" (click)="openModal()">Modal</a>`

And the modal is in login.component.ts, because in header.component.ts  i have two buttons to open the modal, so how can i call the openModal() from another component ?


Thanks you

**Comment by jomarbarnobal** [comment]
just want to add question how to close modal if success login?

**Comment by rubyboy** [comment]
@jomarbarnobal make sure that in your template you point the dialog to the actions:
```html
<div id="modal1" materialize="modal" class="modal" [materializeParams]="[{dismissible: true}]" [materializeActions]="modalActions">
```
