### ISSUE TITLE
side-nav issue with materializecss v0.97.8 and angular2-materialize bindings

### ISSUE THREAD

**Issue by pier7529** [InfomediaLtd/angular2-materialize#167]
Hi,
I'm trying to migrate my personnal website from static HTML pages using materialize-v0.97.8 (without angular2-materialize) to angular2-materialize but I stumble on side-nav.
The 2 websites are in same context in terms of : materializecss v0.97.8 and jquery-2.2.4.min.js so it' probably due when I have the angular2-materialize bindings.

So I try to have the same features from side-nav with angular2-materialize v6.0.1 **on small screens.**

I've prepared a [codepen](https://codepen.io/pier7529/pen/woGzaB)

The expected rendering :
![image](https://cloud.githubusercontent.com/assets/20623346/20238441/f8d128f4-a8eb-11e6-8436-6c5dedfaaf1a.png)
if I change in codepen the line  class="side-nav" to materialize="side-nav", I got this 
![image](https://cloud.githubusercontent.com/assets/20623346/20238463/aae9ee2c-a8ec-11e6-8537-efebabfbab40.png)
Issues **on small screens.**:
1. the Home icon is not in top left corner (as in first screenshot).
2. there's a grey overlay on first click on 'menu' icon

Any help would be greatly appreciated ;-)

my package.json file
{
  "name": "angular-quickstart",
  "version": "1.0.0",
  "description": "QuickStart package.json from the documentation, supplemented with testing support",
  "scripts": {
    "start": "concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "docker-build": "docker build -t ng2-quickstart .",
    "docker": "npm run docker-build && docker run -it --rm -p 3000:3000 -p 3001:3001 ng2-quickstart",
    "pree2e": "npm run webdriver:update",
    "e2e": "tsc && concurrently \"http-server -s\" \"protractor protractor.config.js\" --kill-others --success first",
    "lint": "tslint ./app/**/*.ts -t verbose",
    "lite": "lite-server",
    "test": "tsc && concurrently \"tsc -w\" \"karma start karma.conf.js\"",
    "test-once": "tsc && karma start karma.conf.js --single-run",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "webdriver:update": "webdriver-manager update"
  },
  "keywords": [],
  "author": "",
  "licenses": [
    {
      "type": "MIT",
      "url": "https://github.com/angular/angular.io/blob/master/LICENSE"
    }
  ],
  "dependencies": {
    "@angular/common": "~2.1.2",
    "@angular/compiler": "~2.1.2",
    "@angular/core": "~2.1.2",
    "@angular/forms": "~2.1.2",
    "@angular/http": "~2.1.2",
    "@angular/platform-browser": "~2.1.2",
    "@angular/platform-browser-dynamic": "~2.1.2",
    "@angular/router": "~3.1.2",
    "@angular/upgrade": "~2.1.2",
    "angular-in-memory-web-api": "~0.1.13",
    "angular2-materialize": "^6.0.1",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "install": "^0.8.2",
    "jquery": "^2.2.4",
    "materialize-css": "^0.97.8",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.40",
    "typescript": "^2.0.7",
    "zone.js": "^0.6.26"
  },
  "devDependencies": {
    "concurrently": "^3.1.0",
    "lite-server": "^2.2.2",
    "typescript": "^2.0.3",
    "canonical-path": "0.0.2",
    "http-server": "^0.9.0",
    "tslint": "^3.15.1",
    "lodash": "^4.16.4",
    "jasmine-core": "~2.4.1",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-htmlfile-reporter": "^0.3.4",
    "karma-jasmine": "^1.0.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "4.0.9",
    "webdriver-manager": "10.2.5",
    "rimraf": "^2.5.4",
    "@types/core-js": "^0.9.34",
    "@types/node": "^6.0.46",
    "@types/jasmine": "^2.5.36",
    "@types/selenium-webdriver": "^2.53.33"
  },
  "repository": {}
}

**Comment by rubyboy** [comment]
@pier7529 you need to call the "sideNav" function on the button, just like you did in your static example:
```js
$('.button-collapse').sideNav({
      menuWidth: 300, // Default is 240
      edge: 'left', // Choose the horizontal origin
      closeOnClick: true, // Closes side-nav on <a> clicks, useful for Angular/Meteor
      draggable: true // Choose whether you can drag to open on touch screens
    });
```

Here's how you'd do that with angular2-materialize:
```html
<a href="#" data-activates="nav-mobile" class="button-collapse"
       materialize="sideNav"
       [materializeParams]="[{menuWidth: 300,edge: 'left', closeOnClick: true, draggable: true}]"><i class="material-icons">menu</i></a>
```

Notice that you need both the "sideNav" and params, in your case. You need to remove your previous (wrong) ```materialize="side-nav"``` code.

When trying your static code and the new angular2-materialize version side-by-side they look the same to me. Let me know if it's otherwise.

From codepen:
![image](https://cloud.githubusercontent.com/assets/1908166/20244012/c36bf1f2-a978-11e6-80f9-82b69f11f5e5.png)

In my test (using your code with the adjustments I've provided above):
![image](https://cloud.githubusercontent.com/assets/1908166/20244015/cf27ed98-a978-11e6-9cc2-125bf8133d7c.png)

**Comment by pier7529** [comment]
@rubyboy I've apply your advice and it works like a charm. Thanks a lot.

I also added "materialize="dropdown" before  class="dropdown-button" to get the list for large screen and I replaced for "nav-mobile" the class dropdown-content by a "collapsible" accordion. Still have some adjustments in CSS... etc.

For information [codepen](https://codepen.io/pier7529/pen/pNypYd)

**Comment by abramjstamper** [comment]
I'm also having a similar issue. Whenever I click my side-nav menu, the menu pops up for a second, but then disappears as the background darkens. I believe I have the API followed correctly. I've even added the params from this issue request just to make sure, but apparently I'm still missing something.

```
<div class="navbar-fixed">
    <nav class="indigo">
    <div class="nav-wrapper">
      <a href="/" class="brand-logo">{{title}}</a>
      <a href="#" data-activates="nav-mobile" class="button-collapse" materialize="sideNav"
        [materializeParams]="[{menuWidth: 300,edge: 'left', closeOnClick: true, draggable: true}]"><i class="material-icons">menu</i>
      </a>
      <ul class="right hide-on-med-and-down">
        <li><a routerLink="/dashboard">Dashboard</a></li>
        <li><a routerLink="/fast">Fast Words</a></li>
        <li>extra link</li>
        <li>Logout</li>
      </ul>
      <ul id="nav-mobile" class="side-nav">
        <li><a routerLink="/dashboard">Dashboard</a></li>
        <li><a routerLink="/fast">Fast Words</a></li>
        <li>extra link</li>
        <li>Logout</li>
      </ul>
    </div>
  </nav>
  </div>       
  <router-outlet></router-outlet>
```

Before
![screen shot 2016-11-15 at 1 28 03 pm](https://cloud.githubusercontent.com/assets/9876126/20318247/7022a28c-ab37-11e6-8356-e4151540d0d2.jpg)

Pops out for a split second (hard to get a screenshot)
![screen shot 2016-11-15 at 1 36 32 pm](https://cloud.githubusercontent.com/assets/9876126/20318623/f0c77f6a-ab38-11e6-8c69-e107d0a4a9bb.jpg)

After I click the hamburger
![screen shot 2016-11-15 at 1 28 23 pm](https://cloud.githubusercontent.com/assets/9876126/20318246/7010e07e-ab37-11e6-90bd-e197528ff6cc.jpg)

Package.json
```
"dependencies": {
    "@angular/common": "~2.1.1",
    "@angular/compiler": "~2.1.1",
    "@angular/core": "~2.1.1",
    "@angular/forms": "~2.1.1",
    "@angular/http": "~2.1.1",
    "@angular/platform-browser": "~2.1.1",
    "@angular/platform-browser-dynamic": "~2.1.1",
    "@angular/router": "~3.1.1",
    "@angular/upgrade": "~2.1.1",
    "angular-in-memory-web-api": "~0.1.13",
    "angular2-materialize": "^6.1.1",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "jquery": "^2.2.4",
    "materialize-css": "^0.97.8",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.39",
    "zone.js": "^0.6.25"
  },
  "devDependencies": {
    "@types/core-js": "^0.9.34",
    "@types/node": "^6.0.45",
    "concurrently": "^3.0.0",
    "lite-server": "^2.2.2",
    "typescript": "^2.0.3"
  },
```
