### ISSUE TITLE
angular2-materialize not start unexpected token error

### ISSUE THREAD

**Issue by blandofgod** [InfomediaLtd/angular2-materialize#17]
I have been trying to load angular2-material in a very basic angular2 example.  I am having a hard time getting the service to start.  I get an error: angular2-polyfills.js:332 Error: SyntaxError: Unexpected token <(…)
Usually this is because of the system.js configuration in my index.html so i was hoping someone could assist me.

here is my system.config settings

`
System.config({

            packages: {
                app: {
                    format: 'register',
                    defaultExtension: 'js'
                },
                'materialize': {//I think the issue may be with 'main'.  Is this main, reference my main.ts?
                    'main': 'dist/js/materialize'
                }
            },
            map: {//not sure if this is necessary
                'materialize': 'node_modules/materialize-css'
            }
        });`

Also, i had a difficult time understanding the jspm installation. I have never used jspm and only have used the system.js installation on the angular 2 page.  The jspm install overriding the dependencies did not make sense to me and i was unable to get this to run.  Is jspm required for angular2-materialize?

Thank you for the help.

**Comment by rubyboy** [comment]
@blandofgod JSPM is not required. What are you using for transpiling your code?

If you are not using any tool and just want a plain JS script imports with SystemJS you can import Materialize normally, like described in the [Getting Started](http://materializecss.com/getting-started.html):
```html
 <!-- Compiled and minified CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
<!--Import jQuery before materialize.js-->
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<!-- Compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>       
```

Then, add the following to your SystemJS config, so importing angular2-materialize works:
```js
System.config({
            map: {
                //...
                "angular2-materialize": "node_modules/angular2-materialize"
```

If the import of angular2-materialize still doesn't work for you, are you able to share your code (Github or zip) ? I can try taking a look and getting it to work.

There was an issue some time ago of someone who had a similar problem (he wasn't using JSPM nor Webpack) and the setup above worked for him: https://github.com/InfomediaLtd/angular2-materialize/issues/12
If this solves the problem for you as well then we could add some documentation for setting up angular2-materialize with pure SystemJS configuration.

**Comment by blandofgod** [comment]
@rubyboy Thank you for the quick reply.  I am new to component loading so i was unsure whether or not jspm was required in order for angular2-materialize to work. I will test this out when i get home this afternoon. If i still have issues i can post my code.  Its all just test code to learn the basic functions of angular2.

As for the transpiler, I do not call out any specific transpiler so whichever the [angular 2 quickstart guide](https://angular.io/docs/ts/latest/quickstart.html) uses is the one i am using.

Is there any benefit using jspm over pure systemjs or does it come down to personal preference?

Thank you for the assistance.  I will get back to you later today.

**Comment by rubyboy** [comment]
JSPM is really cool. It lets you manage your dependencies in a very easy way, plus helps with bundling the app. Watch this video for a quick intro to JSPM: https://www.youtube.com/watch?v=iukBMY4apvI

**Comment by blandofgod** [comment]
Thank you for posting the previous users issue, that really helped me out.


         System.config({
            packages: {
                app: {
                    format: 'register',
                    defaultExtension: 'js'
                },
                "angular2-materialize": {
                    "main": "dist/materialize-directive",
                    "defaultExtension": "js"
                }
            },
            map: {//The map location needs to be located outside of the package directive
                "angular2-materialize": "node_modules/angular2-materialize",
                "materialize-css": "node-modules/materialize-css",
            }
        });

I added this to my index.html

    <link rel="stylesheet" href="css/materialize/materialize.min.css">
    <script src="js/jquery/jquery-1.12.1.min.js"></script>
    <script src="js/materialize/materialize.min.js"></script>

Lastly, just in case another user runs across this, remove bootstrap declarations.  Bootstrap will not work with materialize.  At least that solved the issue for me.

Thanks for all the help!

I am going to play around with it now
