### ISSUE TITLE
How to use scrollSpy in navbar ?

### ISSUE THREAD

**Issue by NatsuOnFire** [InfomediaLtd/angular2-materialize#170]
Hi,
I have problem, scrollSpy does nothing in my project.

I have this : 
```
<nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Logo</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="#test1">Test 1</a></li>
        <li><a href="#test2">Test 2</a></li>
        <li><a href="#test3">Test 3</a></li>
      </ul>
    </div>
  </nav>
```

```
<section materialize="scrollSpy" class="scrollspy" id="test1">
/* HTML bloc */
</section
```

**Comment by rubyboy** [comment]
@NatsuOnFire are you able to post the full html that works with plain MaterializeCSS (no Angular) and does what you expect with scrollSpy? Then, we can try taking that and making sure it works the same way with angualr2-materialize.
You can find in the repo a vanilla HTML file to play around with: https://github.com/InfomediaLtd/angular2-materialize/blob/master/index-materializecss.html

**Comment by rubyboy** [comment]
Duplicate: https://github.com/InfomediaLtd/angular2-materialize/issues/316
