### ISSUE TITLE
Keep Track of Modal Open/Closed Status

### ISSUE THREAD

**Issue by phixMe** [InfomediaLtd/angular2-materialize#173]
I have an application that needs to keep track if the modal is currently opened or closed. I can do this by having an event that tracks when the modal is closed. However there are many ways to do this, completing a form, pressing esc, clicking outside the modal. Is there currently a way the framework tracks this. If not, what would be the best practice.

**Comment by rubyboy** [comment]
Interesting question. Do you have an idea how you'd do that with vanilla MaterializeCSS? I think we should keep it as close as possible to the implementation without Angular, so if we know how it's done without Angular we could think of how to approach it with the wrapper.

**Comment by phixMe** [comment]
I'm not totally sure how to do this without just vanilla Materialize, but I have since written code to look at the DOM and see if the modal is present. Not the best solution, but I needed it in a flash.

**Comment by rubyboy** [comment]
Thanks for updating and keeping the issue list tidy :)

**Comment by phixMe** [comment]
I have found a pretty nifty solution without modifying anything in materialize. This is working great in version 5.2.1, and I assume will translate to later versions. Maybe this should be included in the documentation.

```html
<div id="demoModal" class="modal" materialize [materializeParams]="[{complete: closeEvent}]" [materializeActions]="modalActions">
</div>
```

```typescript
private closeEvent(){
  // clean up after modal is closed
}

```

**Comment by rubyboy** [comment]
Cool, thanks for the update. feel free to submit a PR with the docs update.
I'm closing the issue, though, given that you found a way to do it.
