### ISSUE TITLE
How to close the fab menu programatically

### ISSUE THREAD

**Issue by bigggge** [InfomediaLtd/angular2-materialize#174]
I want close the fab automatically when I click the fab child buttons 
like 
```
  $('.fixed-action-btn').closeFAB();

```
but i don't know how to close fab menu in ng2-materialize?

I try these code
```
  onChildClick(event: any) {
       event.target.closeFAB();//don't work , 
    }
```
how to get the `'.fixed-action-btn'` dom element to close fab?

**Comment by rubyboy** [comment]
You can use the MaterializeActions. Check out the modal example in the readme.

**Comment by Cmte-Kirk** [comment]
I solved this problem like this:
criei um `scriptAux.js` na raiz da aplicação com o codigo abaixo

```
$(document).ready(function() {

  $('.close-fab').click(function(){
    $('.fixed-action-btn').closeFAB();
  });

});
```
Include the `scriptAux.js` file in the scripts section of the `angular-cli.json` file.

```
      "scripts": [
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/materialize-css/dist/js/materialize.js",
        "../scriptAux.js"
      ]
```
The fab button looks like this:

```
  <div #fb class="fixed-action-btn click-to-toggle menu-deck">
    <a class="btn-floating btn red">
      <i class="material-icons">menu</i>
    </a>
    <ul class="">
      <li><a class="btn-floating red close-fab" ><i class="material-icons">remove</i></a></li>
      <li><a class="btn-floating yellow darken-1 close-fab"><i class="material-icons">create</i></a></li>
      <li><a class="btn-floating green close-fab"  (click)="openModal()"><i class="material-icons">add</i></a></li>
    </ul>
  </div>
```

**Comment by rubyboy** [comment]
Thanks. For the record, I think a more "Angular way" is preferable, using MaterialActions, like here: https://github.com/InfomediaLtd/angular2-materialize/blob/master/app/components/dialogs.ts
