### ISSUE TITLE
Autocomplete:  not working on first page load.

### ISSUE THREAD

**Issue by sheeput** [InfomediaLtd/angular2-materialize#176]
I have an angular 2 application that is using MaterializeCSS and Angular2-materialize (latest of both).  I'm having some problems with the autocomplete feature.  It works GREAT when I reload a page, but not when I first navigate to the page.  I know.. It doesn't make sense.   There are no console errors on the page either. 

Here is what my html  looks like (stripped down)

`<div class="row">
	<div class="input-field col s8">
		<input class="autocomplete"
			   id="autocomplete"
			   #sPOS
			   type="text"
			   materialize="autocomplete"
			   [materializeParams]="[{'data': {'School':null, 'Blah' :null}}]"
			   [(ngModel)]="site.placeOfServiceText"
			   name="placeOfServiceText"/>
		<label for="autocomplete" class="black-text">Place of Service Code</label>
	</div>
</div>
`
If you need more info let me know.   If navigate to my page and enter this input box, and type 'Bl'  the autocomplete popup doesn't work.   If I reload (F5) the page, and do the same thing it works.

I'm not sure if I'm missing a hook or have something else causing me trauma.

Thanks.

**Comment by phixMe** [comment]
I have been having this issue as well, It seems that any kind of Materialism.js is not getting called at all. For me this doesn't work for a modal, the full screen image zoom, the tabs and the autocomplete. I'm somewhat nonplussed how this occurs, it also occurs after I do a redirect to another page in my application with a `this.router.navigate(['xxxxx']`.

**Comment by rubyboy** [comment]
@sheeput indeed a weird one. I couldn't reproduce it on my sample apps.
Is it happening on a specific browser or OS?
And does it not happen with vanilla MaterializeCSS?

**Comment by sheeput** [comment]
@rubyboy  - Sorry, I was able to find my problem.   We had some css that was causing the problem. Thanks for your help.

**Comment by rubyboy** [comment]
Cool, thanks for keeping the issue list clean :)
