### ISSUE TITLE
select option and data-icon <= no directive in angular2-materialize

### ISSUE THREAD

**Issue by Stefan1980uk** [InfomediaLtd/angular2-materialize#177]
At first I would say angular2-materialize is really help me, but as usual something seems like not implemented fully or please show me what I do wrong:

There is my code:
````
<select materialize="material_select" [materializeSelectOptions]="selectOptions">
<option *ngFor='let destCurrency of currencyList' [ngValue]="destCurrency.currencyCode">
<img src="img/flags//{{destCurrency.countryCode}}.png" width="20" height="13" alt="{{destCurrency.countryName}}  flag">{{destCurrency.countryName}} - {{destCurrency.currencyName}}({{destCurrency.currencyCode}})</option>
</select>
````

as you can guess <img> property are render as string in input form (materialize ul li element) at dropdown images are float to right and are stretched so I try use data-icon attribute in <option....

when I try use as following:
````
<option *ngFor='let destCurrency of currencyList' [ngValue]="destCurrency.currencyCode" data-icon="img/flags/{{destCurrency.countryCode}}.png" class="left">{{destCurrency.countryName}} - {{destCurrency.currencyName}}({{destCurrency.currencyCode}})</option>`
````
I have following error message in console:

zone.js@0.6.26:388 Unhandled Promise rejection: Template parse errors:
Can't bind to 'data-icon' since it isn't a known property of 'option'. ("tions">
    <option *ngFor='let destCurrency of currencyList' [ngValue]="destCurrency.currencyCode" [ERROR ->][data-icon]="img/flags/{{destCurrency.countryCode}}.png"><img src="http"): CurrencyConverterComponent@20:92 ; Zone: <root> ; Task: Promise.then ; Value: BaseException {message: "Template parse errors:↵Can't bind to 'data-icon' s…img src="http"): CurrencyConverterComponent@20:92", stack: "Error: Template parse errors:↵Can't bind to 'data-…keTask (https://npmcdn.com/zone.js@0.6.26:265:35)"} Error: Template parse errors:
Can't bind to 'data-icon' since it isn't a known property of 'option'. ("tions">

Looking forward for any advice how implemented data-icon in option.

**Comment by rogueai** [comment]
I was looking at the same issue, and turns out it's unrelated to the materialize directive. This is because `data-icon` is just a normal attribute and can't be bound as a property, as described here: https://github.com/angular/angular/issues/4385

The solution would be for you to change your code this way:
`[attr.data-icon]="img/flags/{{destCurrency.countryCode}}.png"`

**Comment by marciomsm** [comment]
I got the same error. Does anyone know how to fix it?

I tried two ways unsuccessfully.

**data-icon="{{option.icon}}"**
```
<select materialize="material_select" name="stations" [materializeSelectOptions]="list" [(ngModel)]="model">
        <option value="" disabled selected>Choose an option</option>
        <option *ngFor="let option of list" [ngValue]="option" data-icon="{{option.icon}}" class="left">{{option.name}}</option>
</select>
```

**[attr.data-icon]="{{option.icon}}"** 
```
<select materialize="material_select" name="stations" [materializeSelectOptions]="list" [(ngModel)]="model">
        <option value="" disabled selected>Choose an option</option>
        <option *ngFor="let option of list" [ngValue]="option" [attr.data-icon]="{{option.icon}}" class="left">{{option.name}}</option>
</select>
```

**Comment by rogueai** [comment]
@marciomsm I might be wrong, but I think you need to remove the braces from `[attr.data-icon]`, this should work:
`<option *ngFor="let option of list" [ngValue]="option" [attr.data-icon]="option.icon" class="left">{{option.name}}</option>

**Comment by marciomsm** [comment]
@rogueai thank you so much. It is working now.

**Comment by rubyboy** [comment]
@rogueai thanks for answering!
