### ISSUE TITLE
Add and remove chips event

### ISSUE THREAD

**Issue by conqsys** [InfomediaLtd/angular2-materialize#178]
i need the to save to database when i add a chips or remove chips in angular 2 how can i do that?

**Comment by rubyboy** [comment]
Thanks for raising this issue.
I've now added support for chip events. Here's sample code:
```js
import {Component} from "@angular/core"

@Component({
    selector: "chips",
    template: `
        <div class="chips" materialize="material_chip" (chip.add)="add($event.detail)" (chip.delete)="delete($event.detail)"></div>
    `
})
export class Chips {

  add(chip) {
    console.log("Chip added: " + chip.tag);
  }

  delete(chip) {
    console.log("Chip deleted: " + chip.tag);
  }
}
```

**Comment by moranil** [comment]
add, select, delete events are working for me in angular2 using webpack. 

However I wanted chips not to have close btn when populated from data.
and also multiple select option.

I am building tag cloud using chips, I wanted to populate tags from database and user to select multiple tags. Is chips are good for this use case.

@rubyboy  This is great framework, I had to choose it over angular official implementation. Thanks you very much for developing this.

**Comment by rubyboy** [comment]
See sample code here: https://github.com/InfomediaLtd/angular2-materialize/blob/master/sample/src/app/components/chips.ts
