### ISSUE TITLE
Working example with systemjs

### ISSUE THREAD

**Issue by JoostvdB94** [InfomediaLtd/angular2-materialize#18]
Is it possible to suggest a working example using systemjs?
I cannot get it to work with https://github.com/Elecash/angular2-testing

**Comment by rubyboy** [comment]
Does this help? https://github.com/InfomediaLtd/angular2-materialize/issues/17

**Comment by JoostvdB94** [comment]
I have mapped my modules like this:
` System.config({
        defaultJSExtensions: true,
        map: {//The map location needs to be located outside of the package directive
            "angular2-materialize": "node_modules/angular2-materialize/dist/index",
            "materialize":"dist/js/materialize/bin/materialize"
        }
    });`

and i'm getting this error: 
`Error: Error: Multiple anonymous defines in module http://localhost:8875/dist/js/materialize/bin/materialize.js
	    at eval (http://localhost:8875/dist/js/materialize/bin/materialize.js:234:18013)
	    at eval (http://localhost:8875/dist/js/materialize/bin/materialize.js:234:18112)
	Evaluating http://localhost:8875/dist/js/materialize/bin/materialize.js
	Error loading http://localhost:8875/dist/js/materialize/bin/materialize.js as "materialize" from http://localhost:8875/node_modules/angular2-materialize/dist/index.js`
in my browser. Any ideas?

**Comment by rubyboy** [comment]
Try this:
- Update your materialize CSS import to
```html
    <link type="text/css" rel="stylesheet" href="node_modules/materialize-css/dist/css/materialize.css" media="screen,projection" />
```
- Add the following two script imports after jquery (you can also import them locally, if you want):
```html
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.6/hammer.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
```
- Add the following packages section to System.config:
```js
            packages: {
              "materialize-css": {
                    "main": "dist/js/materialize"
                },
                "materialize": {
                    "main": "dist/materialize-directive",
                    "defaultExtension": "js"
                }
            },
```
- Update your System.config mappings:
```js
            map: {
                "materialize-css": "node-modules/materialize-css",
                "materialize": "node_modules/angular2-materialize",
                "angular2-materialize": "node_modules/angular2-materialize"
            }
```

This should work. Here's the full index.html as I tried it and it worked:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Angular 2 Testing</title>

    <!-- Compiled and minified CSS -->
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css"> -->
    <link type="text/css" rel="stylesheet" href="node_modules/materialize-css/dist/css/materialize.css" media="screen,projection" />
    <!-- Import jQuery before materialize.js -->
    <!-- <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script> -->
    <script src="node_modules/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.6/hammer.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>

    <script src="node_modules/es6-shim/es6-shim.min.js"></script>
    <script src="node_modules/angular2/bundles/angular2-polyfills.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>

    <script>
        System.config({
            defaultJSExtensions: true,
            packages: {
              "materialize-css": {
                    "main": "dist/js/materialize"
                },
                "materialize": {
                    "main": "dist/materialize-directive",
                    "defaultExtension": "js"
                }
            },
            map: {
                "materialize-css": "node-modules/materialize-css",
                "materialize": "node_modules/angular2-materialize",
                "angular2-materialize": "node_modules/angular2-materialize"
            }
        });
    </script>

    <script src="node_modules/rxjs/bundles/Rx.js"></script>
    <script src="node_modules/angular2/bundles/angular2.dev.js"></script>
    <script src="node_modules/angular2/bundles/http.dev.js"></script>

    <script>
        System.import('dist/my-app').catch(console.log.bind(console));
    </script>

</head>
<body>

<my-app></my-app>

</body>
</html>
```

**Comment by JoostvdB94** [comment]
It seems to work! 
I guess i was not aware that the paths under "packages" were relative to the paths mentioned in the "map" section.

Thanks for the help
(PS: I also saw the updated README.md, thanks! :+1: )

**Comment by rubyboy** [comment]
No worries. Thanks for bringing up this issue.
Hopefully the new documentation will help others using similar setup :)

**Comment by rubyboy** [comment]
As per @brockklein 's note (https://github.com/InfomediaLtd/angular2-materialize/issues/115#issuecomment-280411833), here's a more up to date solution: https://github.com/InfomediaLtd/angular2-materialize/issues/115#issuecomment-254809673
