### ISSUE TITLE
Losing Materialize.js javascript functionality after router.navigate([]) call, routerLink or browser back button.

### ISSUE THREAD

**Issue by phixMe** [InfomediaLtd/angular2-materialize#182]
I am having a strange issue that seems to stop all Materialize javascript functionality. After I make a call `this.router.navigate([]);` call to any url in my application all materialize.js library javascript code doesn't run or show any kind of error in the console. Also of note, if I refresh the page (F5) that I have routed to the materialize javascript features are available once again.

code sample:

```typescript
import {ActivatedRoute, Router} from "@angular/router";
...
  constructor(private router: Router) {}
...
  // after this call is made, all materialize javascript features are lost on the resulting page
  this.router.navigate(['/add', add.id]);
```

routes.ts
```typescript
export const routes: Routes = [
  {
    path: '',
    component: MainComponent
  },
  {
    path: 'add/:id',
    component: AddComponent,
    children: [
      { path: '', redirectTo: 'first' },
      { path: 'first', component: FirstComponent },
      { path: 'second', component: SecondComponent },
    ]
  }
];
```

**Comment by akrepon** [comment]
Can you navigate to the component page via the browser url bar? If yes, are you still having the same issue? If you still have this problem, can you please check if the component encapsulation is modified on the decorator?

**Comment by phixMe** [comment]
Yes, if I navigate directive to the first (or second) url path from the url bar everything works fine and the materialize.js is available. This issue only occurs when:
```typescript
this.router.navigate(['xxx'] 
//or 
this.router.navigateByUrl(['xxx/xxx'];
```
is called from the backend

**Comment by phixMe** [comment]
It has come to my attention that I may be importing the Materialize module incorrectly into my angular application. I am using webpack. It seems like the documentation wants me to import MaterializeModule directly in index.ts, however this does not work. So I have imported it in a SharedModule which does work, but has this problem after `router.navigate([''])` is called.



index.ts
```typescript
//imports above

@NgModule({
  imports: [
    //other modules and routing
    ...
    SharedModule
  ],
  declarations: [
    ...
    //all modules
    ...
  ],
  providers: [
    ...
    //all providers
    ...
  ],
  bootstrap: [RootComponent]
})
export class AppModule {}
```

shared.ts
```typescript
//imports above
import 'materialize-css';
import 'angular2-materialize';
import {MaterializeModule} from 'angular2-materialize';

@NgModule({
  imports: [
    CommonModule
  ],
  declarations: [
   //other directives
  ],
  exports: [
    MaterializeModule
  ]
})
export class SharedModule {
}

**Comment by phixMe** [comment]
Another thought, my project is based on the angular 2 fountain generator. Does that have any deviations from the angular CLI webpack generator laid out in the README? https://github.com/FountainJS/generator-fountain-angular2

**Comment by phixMe** [comment]
Another update, I am also encountering this for any instances where I call `<a routerLink=""></a>`.
If anyone has any advice here, I'd really appreciate it, this issue is preventing me from shipping... and I have spent days trying various solutions with little fortune.

**Comment by phixMe** [comment]
Another update, I have spent most of the day trying to to get my application working, including rolling it over to a different starter platform, angular-cli, (which has a slightly newer version of this lib) but I still have the exact same issue. I have discovered the materialize javascript also gets lost upon pressing the back button in the browser. Surely, other people must have encountered this???

**Comment by rubyboy** [comment]
@phixMe I've added an example code to the repo that does what you're describing. I don't see any problems. Could you check if this is the exact use case you've got? https://github.com/InfomediaLtd/angular2-materialize/blob/master/app/components/buttons.ts#L35

You can try it here: http://angular2-materialize.surge.sh/#/Buttons
You can also clone the repo and check if it works for you locally.

Granted, it's not the same build system you're using (I'm using JSPM/system.js), but it may provide some insight if the problem is code or packaging related.

**Comment by phixMe** [comment]
I have solved it. Turns out I wasn't having just one issue. I had numerous throughout the application that made it seem like materialize.js was not working correctly.

I will try my best to describe each issue.

1. Dropdown Menu
Upon navigating to a new page I lost the ability to show the dropdown. To remedy this I imported jQuery into the navbarComponent and put the following as the ngOnInit.

```html
<a [ngClass]="{ 'url': url.path === '' }" class="dropdown-button" data-activates="dropdown-pro">
  Manage
  <i class="material-icons right">arrow_drop_down</i>
</a>
```

```typescript
import * as $ from 'jquery';

ngOnInit() {
  //note syntax to avoid typescript parse static parse errors
  (<any>$(".dropdown-button")).dropdown();
}
```

Thank you for your help! I really appreciate it.

2. Materialbox Images
Almost the same issue as the dropdown, needed to reissue the DOM element at ngOnInit time.
```html
  //note syntax to avoid typescript parse static parse errors
<img class="responsive-img materialboxed" src="../images/thing.jpg"/>
```

```typescript
import * as $ from 'jquery';

  ngOnInit() {
    (<any>$(".materialboxed")).materialbox();
  }
```

3. Tab Routing
I was using the dynamic routing tabs and have the tab name in the url. Before I had an issue where if I navigated to this page through any of the means in the bug, the underline wouldn't show at all, and the routing failed to work correctly. I placed the typescript below in the constructor of the component with the timeout wrapper. (for a reason I still don't understand, the timeout is mandatory)

```html
<ul materialize="tabs" [materializeParams]="tabSelectionParams" [materializeActions]="globalActions" class="tabs transparent-bg" style="max-width: 800px;">
  <li class="tab col s2" [class.disabled]="tab.disabled" *ngFor="let tab of tabs">
    <a [href]="'#'+tab.route" (click)="routeTo(tab.href)">{{tab.name}}</a>
  </li>
</ul>
```

```typescript
setTimeout(() => {
  this.tabSelectionParams = ['select_tab', tab.route];
},1);
```

**Comment by rubyboy** [comment]
Thanks for updating and providing your solutions.
Can this issue be closed?

**Comment by phixMe** [comment]
Yeah, I was just curious if something general needed to be added to the framework for reinitializing some of the materialize DOM elements on these routing changes.

**Comment by TerryMooreII** [comment]
@phixMe I had a very similar issue however the fix for me was to import MaterializeModule in every angular ngModel that was using Materialize JS components.

**Comment by Arkkraa** [comment]
While this is a solution to the problem, this defeats the purpose of having an angular2 module for Materialize. You should avoid using jquery directly in your angular 2 apps!

**Comment by biskazz** [comment]
Having the exact same issue as this. There is also issue #125 which is a similar situation. I'm kind of not OK with using jquery directly in angular.

**Comment by tramel-woodard** [comment]
I'm using the [angular-webpack-starter](https://github.com/AngularClass/angular-starter) project from AngularClass.

**Note:** I am using the materialize.css, materialize.js and the google-font reference code in my index.html page before adding any angular2-materialize functions.
`<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/js/materialize.min.js"></script>`
`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/css/materialize.min.css">`
`<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">`

Using only the standard Materialize CSS standup, my Angular2 application would not acknowledge the "materialboxed" classes.

After using the following steps, everything worked:

1. Navigate to the root directory of the project and run the following code
    **`npm install --save angular2-materialize`**
2. Open the 'src/app/app.module.ts file and insert the following import in bold:
    `import { NgModule, ApplicationRef } from '@angular/core';`
    **`import { MaterializeModule } from 'angular2-materialize';`**
3. Reference this module in your @NgModule imports object in the same 'src/app/app.module.ts' file:
    `@NgModule({`
    `    bootstrap: [ AppComponent ],`
    `    declarations: [`
    `        AppComponent, `
    `    ],`
    `    imports: [ // import Angular's modules`
    `        BrowserModule,`
    `        FormsModule, `
    `        HttpModule, `
    **`        MaterializeModule,`**
    `        ...`

I thought I also needed to refeference MaterializeMdoule from within every component that would be using Materialize code, but I ended up only modifying the app.module.ts from this project.

**Comment by rubyboy** [comment]
Related: https://github.com/InfomediaLtd/angular2-materialize/issues/338

**Comment by wnipper** [comment]
Update: on pages where `Materialize.updateTextFields();` is called in `ngAfterViewChecked()`, the client simply breaks if you refresh or navigate directly to the page.

**Comment by PiyushMishra** [comment]
Same issue I experienced with Collapsible. But when I used materialize= "collapsible"  I got JS functionality.

**Comment by dduft** [comment]
Same problem for me with dropdown. Issue was related to `*ngIf` in `<a>` tag. Using `[hidden]` instead of `*ngIf` solved the problem.
```html
<li [hidden]="!authService.currentUserData">
  <a
    materialize="dropdown"
    class="dropdown-button"
    data-activates="dropdown1"
    href='#'
  >{{authService.currentUserData?.name}}<i class="material-icons right">arrow_drop_down</i>
  </a>
</li>
```
