### ISSUE TITLE
MaterializeAction Error

### ISSUE THREAD

**Issue by AndrewKralovec** [InfomediaLtd/angular2-materialize#183]
I'm trying to add a Modal to my dashboard but when i follow the instructions online, it tells me MaterializeAction has no export member. 

Error
`node_modules/angular2-materialize/dist/index"' has no exported member 'MaterializeAction'.`
When i look at the index file i see no materialize action

index.d.ts
```
export { MaterializeDirective } from "./materialize-directive";
export { MaterializeModule } from "./materialize-module";
export declare function toast(...args: any[]): void;
```

Component.html 
```
        <!-- Modal Trigger -->
        <a class="waves-effect waves-light btn modal-trigger" (click)="openModal()">Modal</a>
        
        <!-- Modal Structure -->
        <div id="modal1" class="modal bottom-sheet" materialize="modal" [materializeParams]="[{dismissible: false}]" [materializeActions]="modalActions">
            <div class="modal-content">
                <h4>Modal Header</h4>
                <p>A bunch of text</p>
            </div>
            <div class="modal-footer">
                <a class="waves-effect waves-green btn-flat" (click)="closeModal()">Close</a>
                <a class="modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
            </div>
        </div>
```

Component.ts 
```

import { Component, EventEmitter, OnInit, AfterViewInit } from '@angular/core';
import { DashboardService } from './dashboard.service';
import 'rxjs/add/operator/map'; 
import {MaterializeAction} from 'angular2-materialize';

@Component({
    selector: 'dashboard-home',
    providers:[DashboardService],
    templateUrl: './dashboard.component.html',
    styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent implements OnInit {
    private user:any ; 
    constructor(private dds:DashboardService){
        
    }
    ngOnInit(){
        this.ds.getUserInfo()
        .subscribe((response:any) => {
            console.log("Response:");
            console.log(response);
            this.user = response ; 
        }, (error:any) => {
            console.log("Error:");
            console.log(error);
        },() => 
            console.log("Request Finished")
        );
    }
    modalActions = new EventEmitter<string|MaterializeAction>();
    openModal() {
        this.modalActions.emit({action:"modal",params:['open']});
    }
    closeModal() {
        this.modalActions.emit({action:"modal",params:['close']});
    }
}

```
package.json

```
    "angular2-materialize": "^5.2.1",
    "materialize-css": "^0.97.8",
    "jquery": "^2.2.4",
    "hammerjs": "^2.0.8",
```

**Comment by rubyboy** [comment]
@AndrewKralovec you are using an old version of angular2-materialize that didn't have this export. Please update your dependencies to use the latest (or at least 6.x) version.

**Comment by AndrewKralovec** [comment]
Thanks @rubyboy, i was hoping it was a version issue. I should have done a npm install from the Package manager instead of coping it from online. There is no longer that error, however the modal wont open when i click on it. Any ideas on how to debug this ?


```
        <div class="col s6">
            <!-- Modal Trigger -->
            <a class="waves-effect waves-light btn modal-trigger" (click)="openModal()">Modal</a>
            
            <!-- Modal Structure -->
            <div id="modal1" class="modal bottom-sheet" materialize="modal" [materializeParams]="[{dismissible: false}]" [materializeActions]="modalActions">
            <div class="modal-content">
                <h4>Modal Header</h4>
                <p>A bunch of text</p>
            </div>
            <div class="modal-footer">
                <a class="waves-effect waves-green btn-flat" (click)="closeModal()">Close</a>
                <a class="modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
            </div>
            </div>
        </div>
```
import { Component, EventEmitter, OnInit, AfterViewInit } from '@angular/core';
import { DashboardService } from './dashboard.service';
import 'rxjs/add/operator/map'; 
import {MaterializeAction} from 'angular2-materialize';

@Component({
    selector: 'dashboard-home',
    providers:[DashboardService],
    templateUrl: './dashboard.component.html',
    styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent implements OnInit {
    private user:any ; 
    modalActions = new EventEmitter<string|MaterializeAction>();
    constructor(private dds:DashboardService){
        
    }
    ngOnInit(){
        this.ds.getUserInfo()
        .subscribe((response:any) => {
            console.log("Response:");
            console.log(response);
            this.user = response ; 
        }, (error:any) => {
            console.log("Error:");
            console.log(error);
        },() => 
            console.log("Request Finished")
        );
    }
    openModal() {
        console.log("Open"); // See this in console 
        this.modalActions.emit({action:"modal",params:['open']});
    }
    closeModal() {
        console.log("Close"); // Dont see this or the modal 
        this.modalActions.emit({action:"modal",params:['close']});
    }
}

**Comment by rubyboy** [comment]
@AndrewKralovec you could start by putting a breakpoint in the MaterializeDirective code that performs the call to open the modal. If that doesn't work, then it's a problem with the angular binding or somewhere in between. If that works then you can follow the flow from there to see if it knows which modal to trigger.

**Comment by rubyboy** [comment]
@AndrewKralovec is this issue still relevant? Can we close it? Thanks.
