### ISSUE TITLE
sidenav

### ISSUE THREAD

**Issue by cesarmarroquin** [InfomediaLtd/angular2-materialize#184]
Is the materialize sidenav currently supported? I cant find any references to it, or instructions on how to use it with this library on my angular2 project.

**Comment by rubyboy** [comment]
Yes, it is. Use it like other MaterializeCSS classes - by adding it to the materialize="sideNav" etc.
You could also look at the issues to find people who used it (and had problems or questions): https://github.com/InfomediaLtd/angular2-materialize/issues?utf8=%E2%9C%93&q=side-nav%20
If you do create a sample, I'm more than happy to merge a PR to the main repo with it, or link to another repo with this sample.

**Comment by rubyboy** [comment]
Sample from today: https://github.com/InfomediaLtd/angular2-materialize/issues/129#issuecomment-263802923
