### ISSUE TITLE
select-wrapper validation not happens after first user selection

### ISSUE THREAD

**Issue by teufelmartin** [InfomediaLtd/angular2-materialize#187]
I'm using the current version of angular2-materialize.

If a user first choose an option, the select-wrapper validation don't happen.
After you select another options everything works as expected und the select-wrapper get  the ng-valid class.

I only add the required validator via formbuilder to my select.

Any ideas?

**Comment by gopchi** [comment]
Hi, I am also having trouble with the select directive. Could you show me some code if have a working solution?
Thanks in advance!

**Comment by Chipintoza** [comment]
it is materializecss 0.98.2 error - update to 0.99.0 and it will work
