### ISSUE TITLE
Apps breaks with Webpack Uglify

### ISSUE THREAD

**Issue by supertino7** [InfomediaLtd/angular2-materialize#188]
Hi there,

I try to launch the build of my application, but I have an error when I display my app on the browser

`materialize.js:235 Uncaught TypeError: Cannot convert undefined or null to object(…)`

I just read issue #42 and #40. The problem seemed to come from the fact that materialize.js is already minified. But I tried to include `exclude` and `except` instructions in my webpack.prod.js, without success...  I also tried to set `dead_code` to true, same thing. Here is my Uglify option : 

    new webpack.optimize.UglifyJsPlugin({ 
      mangle: {
        keep_fnames: true,
        except: ['Materialize'] 
      },
        exclude: ['/materialize.js/g'],
        dead_code: true
    })

Still this error...
I use Webpack **v1.13.3**. The build is ok when I don't use the Uglify plugin.

Thanks for help

**Comment by supertino7** [comment]
I just tried to copy the sample code from https://github.com/InfomediaLtd/angular2-webpack-starter/blob/master/config/webpack.prod.js

```
new UglifyJsPlugin({
      // beautify: true, //debug
      // mangle: false, //debug
      // dead_code: false, //debug
      // unused: false, //debug
      // deadCode: false, //debug
      // compress: {
      //   screw_ie8: true,
      //   keep_fnames: true,
      //   drop_debugger: false,
      //   dead_code: false,
      //   unused: false
      // }, // debug
      // comments: true, //debug


      beautify: false, //prod
      mangle: { screw_ie8 : true }, //prod
      compress: { screw_ie8: true }, //prod
      comments: false //prod
    })
```

And it works... 
The difference is the "keep_fnames" option of mangle. I'm not very familiar with Uglify, but setting it to true tells Uglify to not mangle function names. I don't get clearly why it could cause app to crash ?

**Comment by rubyboy** [comment]
@supertino7 is this still an issue with the latest versions?
