### ISSUE TITLE
Working example with angular2-webpack-starter

### ISSUE THREAD

**Issue by vesteraas** [InfomediaLtd/angular2-materialize#19]
Could you please update your fork of angular2-webpack-starter?  The project has undergone some major changes since your fork, so it would be nice to have an updated example.

**Comment by rubyboy** [comment]
Updated: https://github.com/InfomediaLtd/angular2-webpack-starter

You can see the applied changes in the following commit: https://github.com/InfomediaLtd/angular2-webpack-starter/commit/841121dae45f0bdcf3647803e994461bb6e1c9c6
