### ISSUE TITLE
Sidenav styling changed after v6.3.0 rollout 

### ISSUE THREAD

**Issue by movadee** [InfomediaLtd/angular2-materialize#192]
Hello! I updated our project to v6.3.0 and sidenav ALIGNMENT styling changed a bit. Thought you guys might want to know. The following are screenshots of the sidenav with a bug:

[Sidenav FIXED view (large screens)](https://drive.google.com/file/d/0B6fP2H1kzHK6UWJqNEFVNkx3QzA/view?usp=sharing)
[Sidenav MOBILE view ](https://drive.google.com/file/d/0B6fP2H1kzHK6U2oyUkFqU2dqSnc/view?usp=sharing)

So mobile view is properly alligned, but fixed view having some alignment differences, which it didn't have in the earlier version. Note: dashboard, news, technical docs and my profile are <a> tags; logs, policies, procedures are <a class="collapsible-header"> tags. Please let me know if you have questions. Alla

**Comment by rubyboy** [comment]
@lyalyaka thanks for the heads up. This sounds like a MaterializeCSS problem. Are you able to try it out with vanilla MaterializeCSS and if it indeed is a library problem open an issue on [its repository](https://github.com/Dogfalo/materialize)?
If you're not sure how to do that, you can paste here the HTML you're using and I'll give it a try. Thanks.
