### ISSUE TITLE
Unable to use collapsible when looping through an object array

### ISSUE THREAD

**Issue by crizzy9** [InfomediaLtd/angular2-materialize#193]
I tried looping through collapsible using two methods. when my data is taken from the component as shown in the comment it doesnt work and only yields an expanded list with no collapsible
but when i use an array declared inside the template it works just fine. please help! 

<div class="questions-container">
            <div *ngFor="let i of [{id:1, name: 'one'},{id:2, name: 'two'},{id:3, name:'three'}]">
                {{i.name}}
            
                <div class="collapsibe-container">
                    <ul materialize="collapsible" class="collapsible" data-collapsible="accordion">
                        <li *ngFor="let j of [1,2,3]">
                            <div class="collapsible-header"><i class="material-icons">filter_drama</i>First</div>
                            <div class="collapsible-body">
                                <p>Lorem ipsum dolor sit amet.</p>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

**Comment by rubyboy** [comment]
@crizzy9 this should work:
```html
<ul materialize="collapsible" class="collapsible" data-collapsible="accordion">
  <li *ngFor="let value of values">
    <div class="collapsible-header">{{value}}</div>
    <div class="collapsible-body"><p>{{value}}</p></div>
  </li>
</ul>
```
```js
values = ["First", "Second", "Third"];
```

Check out the example code: https://github.com/InfomediaLtd/angular2-materialize/blob/master/app/components/collapsible.ts#L22

**Comment by rubyboy** [comment]
Closing. Please let me know if there still are any issues.
