### ISSUE TITLE
Select chips event

### ISSUE THREAD

**Issue by bibislayer** [InfomediaLtd/angular2-materialize#195]
chips.select is not not integrate on angular2 directive ?
Using :
`<div class="chips" materialize="material_chip" (chip.add)="add($event.detail) (chip.delete)="delete($event.detail)" (chip.select)="selectChip($event.detail)"></div>`

Console.log work for add and delete event but doesn't work with select.

**Comment by rubyboy** [comment]
A PR would be highly appreciated :)

**Comment by rubyboy** [comment]
Does it work with MaterializeCSS? Seems like a bug there...
@bibislayer can you confirm?

**Comment by bibislayer** [comment]
Thx for your reply,
That work with MaterilizeCSS  width Jquery like this =>
`$('.chips').on('chip.select', function(e, chip){
    // you have the selected chip here
  });`
Actualy i don't use this fonctionnality.

**Comment by rubyboy** [comment]
@bibislayer thanks for the feedback. I'll happily fix that, if I can reproduce selecting chips with Materialize :)
Here's my HTML, using vanilla Materialize, but I can't see to get the "select" to work. Are you able to spot why?
```html
<html>
  <head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
  </head>
  <body>
      <div class="chips"></div>
      <div class="chips chips-initial"></div>
      <div class="chips chips-placeholder"></div>

      <script>
        $(document).ready(function() {
          $('.chips').material_chip();
          $('.chips-initial').material_chip({
            data: [{
              tag: 'Apple',
            }, {
              tag: 'Microsoft',
            }, {
              tag: 'Google',
            }],
          });
          $('.chips-placeholder').material_chip({
            placeholder: 'Enter a tag',
            secondaryPlaceholder: '+Tag',
          }); 
          $('.chips').on('chip.add', function(e, chip){
            console.log("Added",chip);
          });
          $('.chips').on('chip.delete', function(e, chip){
            console.log("Delete",chip);
          });
          $('.chips').on('chip.select', function(e, chip){
            console.log("Select",chip);
          });
        });
      </script>
  </body>
</html>
```

**Comment by bibislayer** [comment]
I'm using a custom extract based on event
https://plnkr.co/edit/SvxD1rxdSzdCPHnBO1B4?p=preview

**Comment by rubyboy** [comment]
But this is "click", and not "chip.select". Your example above is referring to the Materialize "chip.select" event that is not propagated via Angular.

**Comment by rubyboy** [comment]
BTW, the only way I manage to get the chip.select to work is by selecting one chip and then, using the keyboard, move left and right. I've replicated that with angular2-materialize and this does work. See here: http://angular2-materialize.surge.sh/#/Chips (add a few chips to the empty line and then select and move between them - it will print console logs, all coming from the Angular binding).

**Comment by bibislayer** [comment]
Oh yes my apology, so it's materializecss issue not really angular2-materialize

**Comment by rubyboy** [comment]
Cool, thanks for checking and the feedback. I'll close this issue now.
Cheers.

**Comment by bibislayer** [comment]
Just for info issue on materialize lib solved =>
https://github.com/Dogfalo/materialize/commit/84f204db03ab24024dfcff95203b7b234c6a811b
