### ISSUE TITLE
SideNav is not working

### ISSUE THREAD

**Issue by ssatz** [InfomediaLtd/angular2-materialize#196]
`` module: {
             loaders:[
                 {
                     test: /materialize-css\/dist\/js\/materialize\.js/,
                     loader: 'imports?materialize-css'
                 },
                 {
                     test: /\.ts$/,
                     loader: 'awesome-typescript-loader',
                     exclude: /node_modules/,
                     query: {
                         useForkChecker: true,
                         useBabel: true
                     }
                 },
                 {
                     test: /\.html$/,
                     loader: 'raw-loader'
                 },
                 {
                     test: /\.scss$/,
                     loaders: ["raw", "sass?sourceMap"]
                 },

                 {
                     test: /\.css$/,
                     loader: 'raw'
                 },
                 {
                     test: /.(png|woff(2)?|eot|ttf|svg)(\?[a-z0-9=\.]+)?$/,
                     loader: 'url-loader?limit=100000',
                 }
             ]
         },
         noParse: [ /.+zone\.js\/dist\/.+/, /.+angular2\/bundles\/.+/ ],
         plugins: [
             new webpack.optimize.CommonsChunkPlugin({
                 name: 'app',
                 filename: 'app.js',
                 minChunks: 5,
                 chunks: [
                     'app'
                 ]
             }),
             new webpack.optimize.CommonsChunkPlugin({
                 name: 'vendor',
                 filename: 'vendor.js',
                 minChunks: Infinity
             }),
             new webpack.ProvidePlugin({
                 '__decorate': 'typescript-decorate',
                 '__extends': 'typescript-extends',
                 '__param': 'typescript-param',
                 '__metadata': 'typescript-metadata',
                 $: "jquery",
                 jQuery: "jquery",
                 "window.jQuery": "jquery",
                 Hammer: "hammerjs/hammer"
             }),
             new webpack.ContextReplacementPlugin(
                 /angular(\\|\/)core(\\|\/)(esm(\\|\/)src|src)(\\|\/)linker/,
                 __dirname
             ),
         ],
         resolve: {
             extensions: ['', '.js', '.ts','.css']
         },
         debug: true,
         devtool: 'source-map'
``
SideNav is not working but Toast and collapsible are working. Even i have tried to inject jquery.

**Comment by ssatz** [comment]
Update:. I am not getting any error. But when I include materialize parameters, it throws error can't bind materialize params error. I have checked twice that I have included materialize directive in app.module.ts.

**Comment by ssatz** [comment]
Update : I resolved can't bind materialize params error. This issue is due to shared module. But now nothing happens when i click the humberger. No error produced.

**Comment by ssatz** [comment]
Update :  sideNav is working only if i add the class " fixed" in <ul>

**Comment by ssatz** [comment]
Issue has been fixed.  
I have set the  <ul> tag  as left;0px , it solved the issue. This is not an issue with Angular Materialize. 
Please close it.  Maybe a issue with our custom theme
Thanks :+1:

**Comment by rubyboy** [comment]
Thanks for letting us know.
