### ISSUE TITLE
open a modal from the code

### ISSUE THREAD

**Issue by ihabZhaika** [InfomediaLtd/angular2-materialize#198]
Hi,
i want to open the modal when certin condition on the code,
so i have the openModal as in the example code
`
  openModal() {
    this.modalActions.emit({action:"modal",params:['open']});
  }`
if i bind it to a button , the model do open , if i call it within a code it dose not
is there any way to do so ?

**Comment by rubyboy** [comment]
The following works for me. It's from the code, and not as a result of event. Is that what you're trying to do?
```js
constructor() {
    window.setTimeout(()=>{
      console.log("here");
      this.modalActions1.emit({action:"modal",params:['open']});
    },3000);
  }
```

**Comment by ihabZhaika** [comment]
seems the problem is related the the phaser library , that i am trying to open the model from its method
