### ISSUE TITLE
Uncaught Error: Couldn't find materialize function 

### ISSUE THREAD

**Issue by avuletica** [InfomediaLtd/angular2-materialize#199]
Hi I can't seem to figure out what is wrong with my setup of https://www.npmjs.com/package/angular2-materialize 
  
Uncaught Error: Couldn't find materialize function ''material_select' on element or the global Materialize object.

you can check it in my project https://github.com/atodoric/PCinstance.git at materialize-issue branch

I would appreciate any ideas.

**Comment by ssatz** [comment]
It seems you havent include materialize directive in your module. Pls check your installation guide

**Comment by avuletica** [comment]
Did you check materialize-issue branch

https://github.com/atodoric/PCinstance/blob/materialize-issue/src/app/app.module.ts

**Comment by ssatz** [comment]
I have checked below one. It's not included here. 

https://github.com/atodoric/PCinstance/blob/master/src/app/app.module.ts

**Comment by avuletica** [comment]
Yeah, it's not ready for master branch that's why I specified at open post specific branch

**Comment by ssatz** [comment]
Okay np:) I don't see importing of angular2 materialize in vendor.ts or main.ts

import "angular2-materialize";

Could you please check on that once ?

**Comment by avuletica** [comment]
I have tried importing to vendor.ts before posting here, didn't seem to do anything.

Now I've added import "angular2-materialize" on both main.ts and vendor.ts, still same error (now twice since I imported in both files)

**Comment by ssatz** [comment]
Paste below code in vendor.ts at last line

import 'materialize-css';
import 'angular2-materialize';

Remove  materialize-css in Ng module . Above code should be imported only once and don't change the order.

**Comment by avuletica** [comment]
Done, you can see pushed changes but still won't work :(

**Comment by avuletica** [comment]
I tried to make to make this work again by creating new branch from development (test2). By comparing branches test2 with materialize-issue I found out that if I don't include this line:

{ test: /.(png|woff(2)?|eot|ttf|svg)(\?[a-z0-9=\.]+)?$/, loader: 'url-loader?limit=100000' },

It will work normally.

**Comment by ssatz** [comment]
You can also include Jquery Manually and it seems to be working for me

Include Jquery in index.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>

and then in webpack config  add external 
 externals: {
        jquery: 'jQuery'
    },

**Comment by avuletica** [comment]
Reason for doing that is to be able to use  jquery 3 aswell via webpack  or ?

**Comment by ssatz** [comment]
Jquery Version 3.0 is still not yet supported by materializecss. SO,am afraid it will throw error even if you use it normally.

**Comment by avuletica** [comment]
What would be reason to include it manually from index.html?

**Comment by ssatz** [comment]
I don't know the real reason behind. But the error shows the materialize CSS  functions are loaded before jQuery.

**Comment by avuletica** [comment]
Ok, thanks for working with me on this matter, since this issue is solved I will close it.
