### ISSUE TITLE
Call toast without tying it to an element in DOM

### ISSUE THREAD

**Issue by Dillinjer** [InfomediaLtd/angular2-materialize#200]
Hi, I'd like to call a toast without tying it to a specific element in the DOM. I mean, I want to be able to call a toast with a dynamic text from inside the component class or from a service.

In MaterializeCSS I can just do: Materialize.toast('I am a toast!', 4000)

Is there a similar option in angular2-materialize?

**Comment by ssatz** [comment]
declare var Materialize:any;

In your component and use it like
Materialize.toast('I am a toast!', 4000)

**Comment by Dillinjer** [comment]
Nice, didn't know I could do that. Thanks!
