### ISSUE TITLE
Tabs displaying all div content on initial load

### ISSUE THREAD

**Issue by vdesai429** [InfomediaLtd/angular2-materialize#201]
For some reason when navigating from another component to the tab component, the div content from all of the divs is displayed and tabs are inactive -- it seems the tabs are not being initialized (localhost --> localhost/css)

However, when directly navigating to the component the tabs display correctly (localhost/css).

This was setup using  Angular 2 CLI and following the documentation. I've tried various settings changes but to no avail. Hopefully someone here can help! Thanks!

Tab HTML:
```html
 <div class="card">
  <div class="card-content">
    <span class="card-title activator grey-text text-darken-4">CSS</span>

 <div class="row">
    <div class="col s12">
      <ul class="tabs">
        <li class="tab col s3"><a href="#test1">Test 1</a></li>
        <li class="tab col s3"><a href="#test2">Test 2</a></li>
        <li class="tab col s3 disabled"><a href="#test3">Disabled Tab</a></li>
        <li class="tab col s3"><a href="#test4">Test 4</a></li>
      </ul>
    </div>
    <div id="test1" class="col s12">Test 1</div>
    <div id="test2" class="col s12">Test 2</div>
    <div id="test3" class="col s12">Test 3</div>
    <div id="test4" class="col s12">Test 4</div>
  </div>
  </div>
</div>
```

Tab TS: 
import { Component } from '@angular/core';

@Component({
  selector: 'app-pagecss',
  templateUrl: './pagecss.component.html',
  styleUrls: ['./pagecss.component.scss']
})

export class PagecssComponent {

}

Navigating from within app to page with tabs:
![capture](https://cloud.githubusercontent.com/assets/8772408/21575902/787da66a-ceec-11e6-876b-6940054cd63d.PNG)

Navigating directly to page:
![capture2](https://cloud.githubusercontent.com/assets/8772408/21575903/8515a0c6-ceec-11e6-933a-f74066dca94b.PNG)

**Comment by Slaskefar** [comment]
Is it possible that you could share what solved your problem? I think I'm having the same issue, and I feel like I've tried everything.
