### ISSUE TITLE
Typo in documentation?

### ISSUE THREAD

**Issue by avuletica** [InfomediaLtd/angular2-materialize#202]
https://www.npmjs.com/package/angular2-materialize#an-example-setup-with-systemjs-no-webpack-nor-jspm

map: {
        "materialize-css": "node-modules/materialize-css",
        "angular2-materialize": "node_modules/angular2-materialize"
    }

node-modules to node_modules?

**Comment by rubyboy** [comment]
@avuletica thanks!
