### ISSUE TITLE
collapsible issue

### ISSUE THREAD

**Issue by eamonnmag** [InfomediaLtd/angular2-materialize#206]
I'm having troubles with collapsible. The items are displayed, but the JS events are not being triggered. I've got modals etc. on the page already, so the assets are loaded correctly.

```
<ul materialize="collapsible" class="collapsible" data-collapsible="accordion">
    <li *ngFor="let topic of getEnrichedTopics(index)">
        <div class="collapsible-header">
            {{topic.name}}
            <span class="badge">{{topic.value | number : '1.4-4'}}</span>
        </div>
        <div class="collapsible-body">
            <p>details...</p></div>
    </li>
</ul>
```

<img width="620" alt="screen shot 2017-01-10 at 11 01 57" src="https://cloud.githubusercontent.com/assets/282396/21801977/3c634802-d724-11e6-9479-fc181cc304ee.png">

**Comment by rubyboy** [comment]
@eamonnmag what events are you referring to?
Is it different than the example here? http://angular2-materialize.surge.sh/#/Collapsible

**Comment by rubyboy** [comment]
No response. Closing.
