### ISSUE TITLE
Why does the openModal not work during OnInit?

### ISSUE THREAD

**Issue by kootenpv** [InfomediaLtd/angular2-materialize#209]
Does anyone have an idea why this is not working? Adapted the example code just to make this modal start. It seems connected to the html snipper required to make it start?

```
import {MaterializeAction} from 'angular2-materialize';
import {Component, OnChanges, EventEmitter, OnInit } from '@angular/core';

export class AppComponent implements OnInit {
// constructor etc
modalActions = new EventEmitter<string|MaterializeAction>();

  openModal() {
    this.modalActions.emit({action:"modal",params:['open']});
  }

  closeModal() {
    this.modalActions.emit({action:"modal",params:['close']});
  }

  ngOnInit() {
    this.openModal();
  }
}
```

Html stuff:

```html

<!-- Modal Trigger -->
<!-- <a class="waves-effect waves-light btn modal-trigger" (click)="openModal()">Modal</a> -->

<!-- Modal Structure -->
<div id="modal1" class="modal bottom-sheet" materialize="modal" [materializeParams]="[{dismissible: false}]" [materializeActions]="modalActions">
  <div class="modal-content">
    <h4>Modal Header</h4>
    <p>A bunch of text</p>
  </div>
  <div class="modal-footer">
    <a class="waves-effect waves-green btn-flat" (click)="closeModal()">Close</a>
    <a class="modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
  </div>
</div>
```

So, how can I start with an open modal?

**Comment by elwaxoro** [comment]
Try using ngAfterViewInit instead of ngOnInit. ngOnInit runs before child components are ready.

**Comment by kootenpv** [comment]
@elwaxoro Still it does not work. I can only getting it to work by pressing on the button, but I want to avoid that.

**Comment by elwaxoro** [comment]
Well crap. Right you are. I'm using this feature with the modal coming from a sub-component, but part of showing the modal involved making a http call first. The main difference seems to be waiting for the rest of the materialize init to complete.

This works, but it's not ideal:
`
import {Component, EventEmitter, AfterViewInit} from '@angular/core';
import {MaterializeAction} from "angular2-materialize";

@Component({
  selector: 'modal-demo',
  template: `
    <h3>Modal Demo</h3>
    <div class="modal" materialize="modal" [materializeParams]="[{dismissible: true}]" [materializeActions]="modalActions">
      <h1>I'm a modal!</h1>
    </div>
  `
})
export class LandingComponent implements AfterViewInit {
  modalActions = new EventEmitter<string|MaterializeAction>();
  ngAfterViewInit() {
    setTimeout(() => this.modalActions.emit({action: "modal", params: ["open"]}), 1);
  }
}
`

**Comment by kootenpv** [comment]
Thanks for the follow up! Yea indeed, I see what you mean with "not ideal", but actually it does get the job done. I thought I was doing something wrong.

It does make me wonder... how to make this work properly?

**Comment by rubyboy** [comment]
@kootenpv @elwaxoro I've just added a new feature - "init" event that gets called when the component has been initialized (when the Materialize function has been called).
So, now you can add ```(init)="this.openModal()"``` on the dialog div and it will open it when the component finishes rendering and calling the "modal" function.
Hopefully that provides what you were after.

**Comment by kootenpv** [comment]
Hi @rubyboy sounds great! I updated the npm package, I changed the top line to:

    <div id="modal1" class="modal bottom-sheet" materialize="modal" (init)="this.openModal()" [materializeParams]="[{dismissible: true}]" [materializeActions]="modalActions">

and I removed all traces of "AfterViewInit" (implements, import, as function).

But now it does not work? 

EDIT: I think it has not been updated on npm?

**Comment by rubyboy** [comment]
@kootenpv had some problems with the build. Should be OK now, with version 6.4.0

**Comment by kootenpv** [comment]
I tried again as mentioned in my post above, using 6.4.0, but it does not work for me...

Should I do anything else to make it work? I do not `implements ...` anything....

**Comment by rubyboy** [comment]
Nope. Should work.
See here an example of using it: https://github.com/InfomediaLtd/angular2-materialize/blob/init_example/app/components/dialogs.ts
It opens the modal dialog as soon as you go to the dialogs example page

**Comment by elwaxoro** [comment]
@rubyboy thanks, works great!

@kootenpv try this:
```

import {Component, EventEmitter} from '@angular/core';
import {MaterializeAction} from "angular2-materialize";

@Component({
  selector: 'modal-demo',
  template: `
    <h3>Modal Demo</h3>
    <div class="modal" materialize="modal" [materializeParams]="[{dismissible: true}]" [materializeActions]="modalActions" (init)="this.openModal()">
      <h1>I'm a modal!</h1>
    </div>
  `
})
export class DemoComponent {
  modalActions = new EventEmitter<string|MaterializeAction>();

  openModal() {
    this.modalActions.emit({action: "modal", params: ["open"]});
  }
}

```

**Comment by kootenpv** [comment]
So embarrassing, I indeed put (init) on a subelement, putting it on the right parent element solves it. Beautiful :) Thanks @rubyboy and @elwaxoro!

**Comment by tahajaha** [comment]
Hi @rubyboy, when i do as you showed, i get this error:
"Unhandled Promise rejection: Template parse errors:
Can't bind to 'materializeParams' since it isn't a known property of 'div'. "

**Comment by tahajaha** [comment]
Hi, for my case i want to display the modals with a button trigger, but when i start the application the modal pop-up directly and i want it to display only if i click on the button, here's my function: 
modalActions = new EventEmitter<string | MaterializeAction>();
**openModal() {
        this.modalActions.emit({ action: "modal", params: ['modal'] });
    }**
