### ISSUE TITLE
Not working with multiple select

### ISSUE THREAD

**Issue by devilsuraj** [InfomediaLtd/angular2-materialize#21]
Hi, it works for normal select but doesn't work when i add multiple attribute to select , it renders but not showing the values by the way i am fetching values from http request, haven't checked for static values.

**Comment by devilsuraj** [comment]
well it works for static values and it shows my dynamic values if i select any of the static value. i think function needs to call when values are added but it doesnt have any issue with normal select , i dont understand why its happening, is there any refresh event which i can call once the page load is done?

**Comment by rubyboy** [comment]
The ```performLocalElementUpdates``` does most of the required updates for select elements. Maybe there's an edge case where it's not called when needed and we need to call it manually.

If you manage to figure it out I'll be happy to assist you with a PR. If not, are you able to provide an example that reproduces the issue and I'll take a look?

Thanks.

**Comment by devilsuraj** [comment]
Thanks for reply .. here is my code 

```
<div class="form-group">
            <!--if i remoe multiple it works-->
            <select 
                    materialize="material_select"  
                    multiple 
                    (ngModelChange)="change($event)" 
                    [ngModel]="prodmodel.CategoryId"
                    ngControl="CategoryId" #catid="ngForm">
                <!--This options are not rendering-->
                <option *ngFor="#p of categories"
                        [value]="p.id">
                    {{p.CategoryTitle}}
                </option>
                <!--This option will render and if i click it above options will render too but not in oproper way-->
                <option value="0">chhose</option>
            </select>
            <label>select Category </label>
        </div>
```
**and my function to get categories which i am calling inside** `ngOnInit()`

```
getCategories() {
    this._Categories.getCategories()
        .subscribe(
        Categories=> this.Categories= Categories,
        error => this.errorMessage = <any>error);
  }
```
If  i dont get any solution sooner i will crate a repo or plunkr

**Comment by rubyboy** [comment]
Can you check if it's specifically happening when using an Observable?

I tried replicating it with a setTimeout, but it seems to work well. I used the example you provided and added it to the demo app inside this repository.
You check fork the repository and inside the example app (folder "app/components/model-bindings") update select.ts with the following contents:
```js
import {Component, EventEmitter, OnInit} from "angular2/core";
import {MaterializeDirective} from "../../../src/index";
import * as Materialize from "../../../src/index";
import {Option} from './option';

@Component({
    selector: "materialSelect",
    directives: [MaterializeDirective],
    inputs: ['model: model', 'options: options'],
    outputs: ['modelChange'],
    template: `
      <div class="row">
          <div class="input-field col s6">
                <select [ngModel]="model" (ngModelChange)="change($event)" id="selectExample" materialize="material_select">
                  <option value="" disabled selected>Select option ..</option>
                  <option *ngFor="#option of options" [value]="option.value">{{option.name}}</option>
              </select>
          </div>
      </div>

    <div class="form-group">
      <select materialize="material_select" multiple
              (ngModelChange)="change($event)"
              [ngModel]="modelCategoryId">
          <option value="0">choose one</option>
          <option *ngFor="#p of categories" [value]="p.id">{{p.CategoryTitle}}</option>
      </select>
      <label>select Category </label>
    </div>
`
})
export class MaterialSelect implements OnInit {
    model: string;
    modelChange = new EventEmitter();
    options: Array<Option>;

    categories = [];
    modelCategoryId=3;

    public ngOnInit() {
      window.setTimeout(() => {
        this.categories = [{id:1,CategoryTitle:"bla1"},{id:2,CategoryTitle:"bla2"},{id:3,CategoryTitle:"bla3"}];
      },1000);
    }

    change(newValue) {
      Materialize.toast('child select: '+newValue, 2000)
      this.model = newValue;
      this.modelChange.emit(newValue);
    }

}
```

**Comment by devilsuraj** [comment]
hi , it works if i set this value   `modelCategoryId=3;`

**Comment by rubyboy** [comment]
No, it's not.
I do see the problem when there is no initial model selection. Very weird. I tried with plain MaterialCSS (no Angular) and see a very similar behaviour, but I'm not sure if it's related. I'll try to take a look early next week, if you haven't figure it out by then :)

**Comment by devilsuraj** [comment]
cool not a problem will play around to see if i can do something or not ...

**Comment by rubyboy** [comment]
I've spent some time on this today. No solution yet, but now I know now that we definitely need to run updates (```performLocalElementUpdates```) when the component properties get updated (after the zone finishes).

Here's a plain HTML example that reproduces the problem. Uncommenting the ```material_select``` "fixes the problem".
```html
<html>
  <head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
  </head>
  <body>

    <div class="form-group">
      <select multiple>
          <option value="0">choose one</option>
          <option value="1">One</option>
          <option value="2">Two</option>
          <option value="3">Three</option>
      </select>
      <label>select Category </label>
    </div>

    <script>
      $(document).ready(function() {
        $('select').material_select();
        window.setTimeout(() => {
          $('select').append('<option value="4">Four</option>')
          $('select').append('<option value="5">Five</option>')
          $('select').append('<option value="6">Six</option>')
          // $('select').material_select();
        },1000);
      });
    </script>
  </body>
</html>
```

I've also upgraded the project to the latest Angular beta (17).

To reproduce the problem in the example app uncomment the "widnow.setTimeout" in the forms example. It will create an empty select dropdown.

**Comment by devilsuraj** [comment]
hi  , i found a workaround for it just to call   $('#select').material_select(); once all the obervables are loaded and i dont know whether its for everyone but with observables normal select is not rendering values in chrome , it works on firefox but if you call the above function it works everywhere.

i think for observables you will need to create a refresh function which can be called whenever new obervables are loaded.

**Comment by rubyboy** [comment]
I'm actually thinking there should be a way to hook into the zone.js change detection and know when to call this function. I assume it will be relevant for other widgets as well, so it will be good to implement it generically. I haven't yet figured out how to do that, though...

**Comment by devilsuraj** [comment]
ohk i am not familiar with zone.js and seriously a noob in ng2 but i think even if you want to implement something with zonejs you will need to add a listner or any event which will trigger the change detection, without any event you can not check for updated values unless its realtime with socket operations, anyways looking forward to your solution.

**Comment by rubyboy** [comment]
@devilsuraj @bliles this is now fixed. I've added a new attribute to trigger changes linked to the list. You set this attribute to the observable or other element that can change dynamically. It actually does nothing but trigger ngOnChanges for the directive, which kicks in the required Materialize style updates.

Here's an example
```html
<select materialize="material_select" [materializeSelectOptions]="selectOptions">
  <option *ngFor="let option of selectOptions" [value]="option.value">{{option.name}}</option>
</select>
```

Let me know what you think and if this works well for you.

**Comment by rubyboy** [comment]
Here's the code I used to test it (it now part of the model-binding example):
```js
        const options$ = Observable.create(observer => {
          window.setTimeout(()=> {
            observer.next([new Option("1", "Option 1"),new Option("2", "Option 2")]);
          },100);
        });
        options$.subscribe(options => {
          this.selectOptions = options;
        });
```

And a simpler example (using just window.setTimeout) on the forms example:
```js
  public ngOnInit() {
      window.setTimeout(()=>{
        this.selectOptions = [
          {value:1,name:"Option 1"},
          {value:2,name:"Option 2"},
          {value:3,name:"Option 3"}
        ]
      },100);
  }
```

**Comment by bliles** [comment]
👍  thank you

**Comment by maheshp212** [comment]
can this example work for the angular 4 ??

**Comment by rexsateesh** [comment]
**Its working for me**
```
<div class="input-field col s12">
                        <select formControlName="status" [(ngModel)]="selectedStatus" materialize="material_select">
                            <option [ngValue]="" disabled>Select</option>
                            <option [ngValue]="1">Enable</option>
                            <option [ngValue]="0">Disable</option>
                        </select>
                        <label>Status</label>
</div>
```
