### ISSUE TITLE
Parallax not working

### ISSUE THREAD

**Issue by avatsaev** [InfomediaLtd/angular2-materialize#211]
## Describe the error in 1 sentence

Parallax directive not working, skimmed though the source code, couldn't find parallax directive defined anywhere.

## Steps to reproduce

use parallax directive such as described in the documentation:

```

 <div class="parallax-container">
    <div  parallax><img src="/assets/images/banner.jpeg"></div>
  </div>

```

## What exactly is supposed to happen

parallax effect on the image when scrolling

## What exactly does happens

nothing

**Comment by rubyboy** [comment]
I remember trying Parallax a while ago and it worked well. Does this help? https://github.com/InfomediaLtd/angular2-materialize/issues/38#issuecomment-221880386

**Comment by joandvgv** [comment]
@rubyboy I came here to reference same issue, since it helped when it did not work.
In fact, it would be great to have a list of all directives supported and a code snippet implementing them. 
For example, I cound't find the directive for slider nor full-screen slider, so I had to get it to work manually.

**Comment by avatsaev** [comment]
Yes that was exactly my issue, lack of documentation, in order for parallax to work you need to use materiaze="parallax" directive, except it's not documented, and the sample website doesn't show that parallax feature is supported.

@rubyboy I'll finish my PR today for parallax example on the sample website

**Comment by rubyboy** [comment]
@avatsaev thanks for your contribution. For some reason I thought you'd finished the PR and merged it. I also added a bit of example of how to use it. Feel free to add anything additional you'd like to have there.

@joandvgv if there's anything you think is missing and you are happy to contribute a PR would be wonderful. Cheers.

**Comment by jomarbarnobal** [comment]
seem not work to me 
the image do not show, no error in console
im using angular cli

thanks in advance

**Comment by joandvgv** [comment]
Hello @jomarbarnobal Have you used other components? Did they work?
Please give us more information like logs or images of actual issue. 
Are you using angular cli webpack?

**Comment by jomarbarnobal** [comment]
yes sir im using angular clie webpack the latest one
i use it in my component like the example here

**Comment by joandvgv** [comment]
Perfect! 
Maybe you should take a look at a project I'm currently working on. 
https://github.com/joandvgv/angular2-express-starter

It has an example of parallax effect working perfectly on dashboard.component.ts

I can help you with your own project but you need to post some logs for me to get an idea on what's happening.

**Comment by jomarbarnobal** [comment]
@joandvgv  
this is my app https://jomarbarnobal.github.io/blog/home
my repo
https://github.com/jomarbarnobal/blog/blob/master/src/app/home/home.component.html

**Comment by avatsaev** [comment]
i made it work on my repo, see how it's done here: https://github.com/avatsaev/angular-cli-seed

**Comment by jomarbarnobal** [comment]
well ill try to look where did i go wrong

**Comment by jomarbarnobal** [comment]
Thanks @avatsaev and @joandvgv   
I made it work i updated my materialize package from    "angular2-materialize": "^6.3.0", to    "angular2-materialize": "^6.6.0",

**Comment by jomarbarnobal** [comment]
Actually it did work even in version 6.3.0, it was my mistake that i didnt notice, that i have a background css in my html 'body', so i make my body into relative and put z-index: -1, so that the parallax show before the body background
