### ISSUE TITLE
Material Select on Dialog (Modal) not show correctly (z-index)

### ISSUE THREAD

**Issue by WebDoin** [InfomediaLtd/angular2-materialize#213]
Hi, i have a modal with a material select but this not show correctly. ¿what happen? 

![error_modal](https://cloud.githubusercontent.com/assets/11144445/21985514/6042f282-dbfb-11e6-9fd8-83ddda4d509d.jpg)

Thanks

**Comment by rubyboy** [comment]
@WebDoin are you able to try this on vanilla MaterializeCSS? Is sounds like a problem in MaterializeCSS itself. If you could verify that it will help identify where the fix is required. Thanks.

**Comment by WebDoin** [comment]
@rubyboy yes, but is the same problem.

**Comment by WebDoin** [comment]
I need change the z-index property?

**Comment by rubyboy** [comment]
@WebDoin not really sure. If it's a MaterializeCSS problem, would you be able to open a bug in the MaterializeCSS Github repo (https://github.com/Dogfalo/materialize/issues) and close this one? They'll know much better what to fix. Probably some CSS, as you're suggesting.

**Comment by WebDoin** [comment]
Thanks!!
