### ISSUE TITLE
Date Range Picker Example

### ISSUE THREAD

**Issue by imdivakar** [InfomediaLtd/angular2-materialize#215]
Hi, I want to build a Date Range Picker in my application is there any sample code available?

**Comment by rubyboy** [comment]
@imdivakar I think this question should be asked here: https://github.com/Dogfalo/materialize
If you know how to do that with vanilla MaterializeCSS and it doesn't work with the angular2 bindings, let us know and we'll try to fix. Thanks.

**Comment by imdivakar** [comment]
@rubyboy ok i will check with [https://github.com/Dogfalo/materialize](url) thanks :)

**Comment by rubyboy** [comment]
No worries. I'll close the issue for now.

**Comment by imdivakar** [comment]
Hi Again,

I want to handle datepicker (open,close) from component using EventEmitter like how your implementing for modal. possible?
