### ISSUE TITLE
Carousel-Slider

### ISSUE THREAD

**Issue by silasbrasil** [InfomediaLtd/angular2-materialize#220]
Carousel-slider don't work. May you create a example how call carousel-slider?

**Comment by rubyboy** [comment]
Does this help? https://github.com/InfomediaLtd/angular2-materialize/issues/71#issuecomment-236899200

**Comment by silasbrasil** [comment]
Unfortunately not! 
I can initialize the corousel in mode default, but when a put the params "carousel-slider" don't work.

That's work:
`<div #carousel class="carousel" [ngClass]="{ 'initialized': showInitialized }" materialize="carousel" [materializeActions]="actions"></div>`

But that's don't work:
`<div #carousel class="carousel carousel-slider" [ngClass]="{ 'initialized': showInitialized }" materialize="carousel" [materializeActions]="actions"></div>`

**Comment by rubyboy** [comment]
I think we need to upgrade the angular2-materliaize to the latest MaterializeCSS for that (98.0). I'll create a separate issue for that.

This doesn't work (97.8):
```html
<html>
  <head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
  </head>
  <body>
        <div class="carousel carousel-slider">
          <a class="carousel-item" href="#one!"><img src="http://lorempixel.com/800/400/food/1"></a>
          <a class="carousel-item" href="#two!"><img src="http://lorempixel.com/800/400/food/2"></a>
          <a class="carousel-item" href="#three!"><img src="http://lorempixel.com/800/400/food/3"></a>
          <a class="carousel-item" href="#four!"><img src="http://lorempixel.com/800/400/food/4"></a>
        </div>

      <script>
        $(document).ready(function() {
          $('.carousel.carousel-slider').carousel({fullWidth: true});
        });
      </script>
  </body>
</html>

```

This works (98.0):
```html
<html>
  <head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>
  </head>
  <body>
        <div class="carousel carousel-slider">
          <a class="carousel-item" href="#one!"><img src="http://lorempixel.com/800/400/food/1"></a>
          <a class="carousel-item" href="#two!"><img src="http://lorempixel.com/800/400/food/2"></a>
          <a class="carousel-item" href="#three!"><img src="http://lorempixel.com/800/400/food/3"></a>
          <a class="carousel-item" href="#four!"><img src="http://lorempixel.com/800/400/food/4"></a>
        </div>

      <script>
        $(document).ready(function() {
          $('.carousel.carousel-slider').carousel({fullWidth: true});
        });
      </script>
  </body>
</html>
```

**Comment by silasbrasil** [comment]
I am using "angular2-materialize": "^6.6.0" and "materialize-css": "^0.98.0" but don't work. If possible, you may create a example with Angular 2?

Since now, thank you very much.

**Comment by rubyboy** [comment]
I've created this issue to solve it: https://github.com/InfomediaLtd/angular2-materialize/issues/221
I notice that there's some incompatibility related to "pick.js" that it can't find. Haven't explored further.
PR's are very welcome, if you'd like to contribute. Thanks.

**Comment by rubyboy** [comment]
I'll close this issue now. Keeping the other one open for the MaterializeCSS upgrade.
