### ISSUE TITLE
Upgrade to support MaterializeCSS 98.0

### ISSUE THREAD

**Issue by rubyboy** [InfomediaLtd/angular2-materialize#221]
Should also fix https://github.com/InfomediaLtd/angular2-materialize/issues/220

**Comment by jano42** [comment]
+1

**Comment by hugocalheira** [comment]
Do you have any idea when this will be available?

**Comment by rubyboy** [comment]
@hugocalheira sorry, no ETA. A PR would be awesome! :)

**Comment by moranil** [comment]
I also need this feature.

**Comment by imdivakar** [comment]
I also need this feature +1

**Comment by rubyboy** [comment]
Should be resolved with the latest v9 release of angular2-materialize
