### ISSUE TITLE
Injecting materialize only in one component

### ISSUE THREAD

**Issue by gastikirs** [InfomediaLtd/angular2-materialize#223]
Is it possible to inject materialize **only** in one component? I have another css framework running already and they collide. 
I tried removing `"../node_modules/materialize-css/dist/css/materialize.css"` from the angular-cli.json and importing it only in the styleUrl array within the component decorator, but styles are not loaded properly.

```
import { Component, OnInit, ElementRef } from '@angular/core';
declare var jQuery: any;


@Component({
  selector: 'kz-clean-form',
  templateUrl: './clean-form.component.html',
  styleUrls: ['../../../../../node_modules/materialize-css/dist/css/materialize.css', './clean-form.component.css']
})
export class CleanFormComponent implements OnInit {

  constructor(private _elRef: ElementRef) { }

  ngOnInit() {
  	jQuery(this._elRef.nativeElement).find('select').material_select();
  }
}
```

**Comment by rubyboy** [comment]
Unfortunately, MaterializeCSS itself is global. I remember seeing some issue on their repo to allow importing it locally to a component, but I can imagine it's a pretty massive effort on their part to redesign the library this way.
I suggest opening this issue in their github page (or finding an existing one and adding +1 on it). Not much we can do here on the angular bindings. Even though you can only import the directive into one component, the MaterializeCSS library itself is the challenge.
