### ISSUE TITLE
'modal' materializeParams  - ready: func() not working properly

### ISSUE THREAD

**Issue by webmatrixxxl** [InfomediaLtd/angular2-materialize#226]
```
<button class="btn" data-target="modal__new-folder">New Folder</button>

<div materialize="modal" id="my_modal" class="modal" [materializeParams]="[{dismissible: true, ready: log()}]"></div>
```

If sey only dismissible: true/false  there is no difference in modal behavior. If use ready: log(), log function is fired on mouse move over document and button.

Am I doing something wrong ?

Using angular-cli: 1.0.0-beta.24 and angular 2.3.1

Thank you!

**Edit**:  {dismissible: true/false} is working

**Comment by rubyboy** [comment]
The following works for me, when changing the value of dismissible. It allows clicking outside the dialog to close it (if set to "true") or not (in "false"):
```html
<button class="btn" data-target="modal__new-folder">New Folder</button>
<div materialize="modal" id="modal__new-folder" class="modal" [materializeParams]="[{dismissible: false}]">
  <div class="modal-content">
    <h4>Modal Header 1</h4>
    <p>A bunch of text</p>
  </div>
</div>
```

"log" indeed is weird. I've never used it, but it is called too many times. Need to check...

**Comment by webmatrixxxl** [comment]
When  I use it like this `[materializeParams]="[{ready: log}]"` it fires only once when I open the modal.

**Comment by rubyboy** [comment]
That's a very good point. The way you used it before was calling "log" every time it evaluates the param. So, supplying a function is the right way to use it.
I think this issue can be closed now, right?

**Comment by webmatrixxxl** [comment]
Ok, is there a way to pass parameters to log() func ?

**Comment by rubyboy** [comment]
Just like the example on the MaterializeCSS page:
```html
<div materialize="modal" id="modal__new-folder" class="modal" [materializeParams]="[{dismissible: false, ready:log}]">
```
```js
  log(modal, trigger) { // Callback for Modal open. Modal and trigger parameters available.
    alert("Ready");
    console.log(modal, trigger);
  }
```

**Comment by webmatrixxxl** [comment]
Ок, thank you.
