### ISSUE TITLE
Dropdown behaviour on form.disable() 

### ISSUE THREAD

**Issue by movadee** [InfomediaLtd/angular2-materialize#227]
Hello) I recently discovered that materialize dropdown is not responding to form.enable() or form.disable() methods. My project is using Angular 2.0.1 & angular2-materializecss. All forms are created dynamically. I am expecting to enable/disable form on enable/disable button clicks. As demonstrated in [this video](https://drive.google.com/file/d/0B6fP2H1kzHK6dWRWOXZDTVVBb2s/view) all form fields are behaving properly except the one that is using materialize="material_select". I found out that if I will use class="browser-default" on the dropdown fields, then everything is working well, but select field is obviously not materialized anymore... Please advice. Thank you

**Comment by rubyboy** [comment]
@movadee thanks for providing such a clear explanation and a demo of the problem.

I've fixed the inconsistent way "select" elements behaved when changing their "disabled" attribute.
I've also added a demo of disabling all form elements here: http://angular2-materialize.surge.sh/#/Forms (Code here: https://github.com/InfomediaLtd/angular2-materialize/blob/master/app/components/forms.ts).

Are you able to get latest build from npm and config this has fixed the problem for you?

**Comment by movadee** [comment]
Hello! Thank you so much for a quick reply! I've tested a demo and not sure
if it works quite right. When I am clicking on Disable Form "Select"
elements are appearing to be active until I click on them. When button
Enable Form clicked select elements are not active still, so I can't select
anything. Testing npm and updates you've made. Will reply to the second
question shortly :) Again, thank you so much for dealing with a problem so
quickly!

**Comment by rubyboy** [comment]
See below how it behaves. Is that now how you'd expect it to work?
![disablingformelements](https://cloud.githubusercontent.com/assets/1908166/22860619/1c122d64-f10c-11e6-9c20-2de6c30b7ed3.gif)

**Comment by movadee** [comment]
For some reason I see a different Select behaviour on this page:
http://angular2-materialize.surge.sh/#/Forms

<http://angular2-materialize.surge.sh/#/Forms>However, I got the latest
build from npm and tested select option in my project and it works
perfectly fine! Thank you very much again! :)

**Comment by rubyboy** [comment]
Maybe some caching of an older version?
No worries. Thanks for verifying the fix.
I'll close the issue now.
