### ISSUE TITLE
Unable to open modal on intialize

### ISSUE THREAD

**Issue by crizzy9** [InfomediaLtd/angular2-materialize#229]
While using **modal.actions.emit({ action: 'modal', params: ['open'] })** on component initialize the modal doesnt open since actions does not have any observers even after ngAfterViewInit. It only works once the page is completely loaded. Is there any workaround for this?

**Comment by rubyboy** [comment]
Use ```(init)="this.openModal()"```. See here: https://github.com/InfomediaLtd/angular2-materialize/issues/209#issuecomment-272687426
