### ISSUE TITLE
Tabs inside routing-outlet

### ISSUE THREAD

**Issue by Kravs** [InfomediaLtd/angular2-materialize#23]
Hello,
I want to use tabs inside routing outlet,and it is not working with following code:
` <li [class]="'tab col s3' + (tab.disabled?' disabled':'')" *ngFor="#tab of tabs">`

To fix it for myself I use following syntax:
`<li class="tab col s3" [class.disabled]="tab.disabled" *ngFor="#tab of tabs">`

**Comment by rubyboy** [comment]
Interesting. Both work for me, but I like your approach better :)
I'll update the demo application accordingly.

**Comment by rubyboy** [comment]
@Kravs thanks for your contribution!

**Comment by Kravs** [comment]
I think it's recommended way from angular docs...
And I'm really surprised that both ways works for you :)
