### ISSUE TITLE
Chips Autocomplete

### ISSUE THREAD

**Issue by RadouaneRoufid** [InfomediaLtd/angular2-materialize#230]
I tried to use Materialize chips with aucomplete functionality as show in [http://materializecss.com/chips.html](http://materializecss.com). 

I tried : 

`<div class="chips chips-autocomplete" materialize="material_chip" [materializeParams]="[autocompleteData]"></div>`

But autocomplete does not work. I didn't found any documentation for this. Is this provided by the actual version ?

Thank you for your great job.

**Comment by rubyboy** [comment]
This feature is only available in the latest version (98): https://github.com/Dogfalo/materialize#changelog ( committed here - https://github.com/Dogfalo/materialize/commit/83e6ba03487c8ad3d7aefb32af3a6beee725a29b)

Currently, angular2-materialize only supports 97. The upgrade to v98 is tracked here: https://github.com/InfomediaLtd/angular2-materialize/issues/221

**Comment by RadouaneRoufid** [comment]
Okay. Thank you very much !

**Comment by rubyboy** [comment]
@RadouaneRoufid the latest version now uses v0.98 of Materialize and you can find there a sample of using chips autocomplete:
```js
@Component({
    selector: "chips",
    template: `
        <div class="chips" materialize="material_chip" [materializeParams]="[autocompleteInit]"></div>
    `
})
export class Chips {

  autocompleteInit = {
    autocompleteOptions: {
      data: {
        'Apple': null,
        'Microsoft': null,
        'Google': null
      },
      limit: Infinity,
      minLength: 1
    }
  };
```

**Comment by carol-braileanu** [comment]
Hello,

I, too am using this control, but I cannot see an example of how to get the values from it. I tried:

```
  public personInit = {
    placeholder: '+Tag',
    autocompleteOptions: {
      data: { 'Apple': null },
      onAutocomplete: (val) => {
        console.log(val);
      },
      limit: Infinity,
      minLength: 1
    },
   
  };
```
However, the Autocomplete event is never fired.

**Comment by rubyboy** [comment]
@carol-braileanu you can find the available events here: http://materializecss.com/chips.html

Sample code:
```html
        <div class="chips" materialize="material_chip" [materializeParams]="[autocompleteInit]" (chip.add)="add($event.detail)" (chip.delete)="delete($event.detail)" (chip.select)="select($event.detail)"></div>
```
```js
autocompleteInit = {
    autocompleteOptions: {
      data: {
        'Apple': null,
        'Microsoft': null,
        'Google': null
      },
      limit: Infinity,
      minLength: 1
    }
  };  

  add(chip) {
    console.log("Chip added: " + chip.tag);
  }

  delete(chip) {
    console.log("Chip deleted: " + chip.tag);
  }

  select(chip) {
    console.log("Chip selected: " + chip.tag);
  }
```

**Comment by carol-braileanu** [comment]
Thank you for your info. Is it also possible to set IDs for the autocomplete items? At this moment the only solution I see is to get the names and match them in the database by name.
