### ISSUE TITLE
Definitely, angular2-materialize ignores angular-cli@webpack

### ISSUE THREAD

**Issue by wgbn** [InfomediaLtd/angular2-materialize#235]
The biggest problem of angular-2-materialize library is that it does not support and completely ignores the angular-cli@webpack installations.

It is a fact that today almost all  angular 2+ projects are created through the angular command line tool, which encapsulates the webpack making it easy to configure, but all the issues open here that refer to errors with angular-cli@webpack are ignored and closed pointing to a solution that is not feasible for everyone, which is the manual configuration of the webpack.

Please @rubyboy  please look more closely for this integration, and do not prioritize only the vanilla webpack

**Comment by rubyboy** [comment]
@wgbn do you think the code in the repo needs to change?
I think it's mainly just the instructions of how to bring it in. If you would like to contribute I'd love to approve a PR that fixes all the issues around the configs you're referring to. Is that something you could do?

**Comment by rubyboy** [comment]
@luketn has just set up this repo to use https://github.com/angular/angular-cli . I've confirmed and the instructions seem correct. Closing this issue. @wgbn please let us know if there's any open issues in relation to angular2-materialize and the cli.
