### ISSUE TITLE
 Override colors theme

### ISSUE THREAD

**Issue by marciomsm** [InfomediaLtd/angular2-materialize#236]
Does anyone know how to override the colors to create a custom theme? 

I am using /assets/css/styles.scss. I tried adding the following lines:

@import '~materialize-css/sass/components/variables';
$secundary-color: #FF0000;
@import '~materialize-css/sass/materialize';

I get these errors:

$primary-color-light: lighten($primary-color, 15%) !default;                                            
                     ^                                                                                  
      Argument `$color` of `lighten($color, $amount)` must be a color                                   
                                                                                                        
Backtrace:                                                                                              
        node_modules/materialize-css/sass/components/_variables.scss:37, in function `lighten`          
        node_modules/materialize-css/sass/components/_variables.scss:37                                 
      in /src/webResources/node_modules/materialize-css/
sass/components/_variables.scss (line 37, column 23)                                                    
 @ ./src/assets/css/styles.scss 4:14-193                                                                
 @ multi ./~/materialize-css/dist/css/materialize.css ./src/assets/css/styles.scss                      
webpack: Failed to compile.

Thanks.

**Comment by rubyboy** [comment]
@marciomsm is this a duplicate of https://github.com/InfomediaLtd/angular2-materialize/issues/205 ?

**Comment by marciomsm** [comment]
Yes, it is. I am closing this.
Thanks.
