### ISSUE TITLE
sideNav with fixed desktop nav

### ISSUE THREAD

**Issue by evanhdc** [InfomediaLtd/angular2-materialize#238]
I'd like to make a fixed Navbar for desktop view, as well as navbar for mobile view. This is what I did
```html
<div class="navbar-fixed">
    <!--desktop-->
    <nav>
      <div class="nav-wrapper">
        <ul class="right hide-on-med-and-down">
            ...
        </ul>
      </div>
    </nav>

    <!--mobile-->
    <nav>
      <a href="#" data-activates="nav-mobile" class="button-collapse" materialize="sideNav" [materializeParams]="[{edge:'left',closeOnClick:true}]"><i class="material-icons grey-text">menu</i></a>
        <ul id="nav-mobile" class="side-nav">
            ...
        </ul>
    </nav>
</div>
```
Note that I put both nav inside the same outer <div class="navbar-fixed">. Problem is that in mobile view, when I clicked the menu button, sideNav shows up with a sidenav-overlay that covers the entire page including the sideNav so I can't click any option.

I tried to move mobile nav out of the outer div and of course I got two nav show up at the same time.

Looks like for sidenav-overlay to cover only the correct portion of the page, I have to remove the outer div but this way, the desktop navbar is not fixed anymore. Is there a way to make it work correctly?

**Comment by rubyboy** [comment]
@evanhdc is this a problem only in angular2-materialize or also when using vanilla MaterializeCSS?
If it's a MaterializeCSS problem I suggest opening this issue on their repo: https://github.com/Dogfalo/materialize

**Comment by evanhdc** [comment]
You are right, it's their issue which works fine with materializecss ver 0.97.7 but starts from v0.97.8, and is still happening in the latest v0.98.0. I opened an issue on their repo. Thanks!

**Comment by rubyboy** [comment]
Cool, thanks for checking. I'll close this issue now.
