### ISSUE TITLE
Form validation

### ISSUE THREAD

**Issue by IvannaBabchanik** [InfomediaLtd/angular2-materialize#24]
Hi!
I'm trying to figure out how to work with validation. You provide simple seamless with inputs. What about validation for select? I did following : 

`<select  materialize="material_select" [(ngModel)]="model.requested"
    class="validate" required>
    <option value disabled selected> </option>
    <option *ngFor="#requested of reguestFrom" [value]="requested">{{requested}}</option>
</select>
<label>Request from*</label>`

but it doesn't work. Actually I have found workaround but it's not better solution:
`<select  materialize="material_select" [(ngModel)]="model.requested"
    class="validate" required>` 
It's add ng-valid class and I can use it.

Could you please explain me how to use validation for select and how to write custom validation function?

thanks for advance!

**Comment by rubyboy** [comment]
@IvannaBabchanik thanks for posting this question.
angular2-materialize is a simple wrapper around the [Materialize](http://materializecss.com/) framework and is supposed to support everything that Materialize does.
Could you provide an example of how you would do that with plain Materialize and I'll check how to support that in angular2-materialize? I'd expect the syntax to be very similar, where the dynamic nature would be provided by native angular directives or any required additions by the angular2-materialize directive.
Thanks.

**Comment by rubyboy** [comment]
No answer. Closing.

**Comment by rubyboy** [comment]
To add to this, the following works and validates as expected:
```html
<div class="input-field col s6">
    <input materialize="characterCounter" length="5" [(ngModel)]="firstName" placeholder="Placeholder" id="first_name" type="text" class="validate">
    <label for="first_name">First Name</label>
</div>
```
