### ISSUE TITLE
package.json still use materialize-css@0.97.8 ?

### ISSUE THREAD

**Issue by rainstormza** [InfomediaLtd/angular2-materialize#240]
Supakorns-MacBook-Pro:portfolio ARM$ npm install angular2-materialize --save
portfolio@0.0.0 /Users/ARM/Desktop/portfolio
├── angular2-materialize@6.7.1
└── UNMET PEER DEPENDENCY materialize-css@0.98.0

angular2-materialize version 6.7.1 in pacjage.json still use materialize-css@0.97.8

**Comment by eforblue** [comment]
I was trying to install angular2-materialize today and got the same warning message. Shall I just ignore it?

**Comment by rubyboy** [comment]
Should be good now, with the latest v10 version.
