### ISSUE TITLE
Type definition for MaterializeAction

### ISSUE THREAD

**Issue by snarum** [InfomediaLtd/angular2-materialize#241]
I just wonder why MaterializeAction is not defined in the type definition file. Is there a good reason for this?

**Comment by rubyboy** [comment]
Isn't it? I can see it when importing this project from another project:
![image](https://cloud.githubusercontent.com/assets/1908166/23860639/35751e4a-0810-11e7-816e-0bc7519b5a00.png)

**Comment by snarum** [comment]
sorry, my bad. was using 6.3.0.
