### ISSUE TITLE
$event.stopPropagation prevents modal form opening.

### ISSUE THREAD

**Issue by webmatrixxxl** [InfomediaLtd/angular2-materialize#244]
Hello. This is very strange problem for me. Modal is working, but if I set $event.stopPropagetion(), it can't be opened any more.

`<a data-target="modal__folder" (click)="$event.stopPropagation()" title="New Folder">Add new folder</a>`

Other strage thing is if modal's link parent element has (click)="$event.stopPropagation()" modal can't be opened too:

`<div (click)="$event.stopPropagation()"><a data-target="modal__folder"  title="New Folder">Add new folder</a></div>`

Any idea how to fix this or some kind of workaround ?

**Comment by rubyboy** [comment]
You can use MaterializeActions to force opening the modal. Does that work for you?

**Comment by webmatrixxxl** [comment]
Yes, this will do the job, but i prefer not to do it this way.

**Comment by rubyboy** [comment]
This is kind of the design of this library - actions are performed once via the template, or if you want to dynamically to things then MaterializeActions. Happy if you propose a new one with a PR :)
I'll close this issue for now, unless you think there's something to be done here.
Thanks.
