### ISSUE TITLE
how to bind onAutocomplete on materializeParams ?

### ISSUE THREAD

**Issue by raiden0610** [InfomediaLtd/angular2-materialize#245]
Hello,

I tried to bind the onAutocomplete method like this but it didn't work :

`<input type="text" id="diettype" materialize="autocomplete" [materializeParams]="[{'data': locations, 'onAutocomplete' : onSelectDietTypes($val)}]">`

I want to do something when the user click on the autocomplete suggestion ?

Can you help me ?

Thanks for the awesome work

Cheers,

**Comment by aguilarguisado** [comment]
Have we got any notices about this?

**Comment by raiden0610** [comment]
Maybe I didn't find it but I don't think so

**Comment by rubyboy** [comment]
Here's some sample code (complete code here: https://github.com/InfomediaLtd/angular2-materialize/blob/master/sample/src/app/components/forms.ts):
```html
<input type="text" materialize="autocomplete" [materializeParams]="[autocompleteInit]">
```
```js
  autocompleteInit = {
    'data': {'Apple': null, 'Google': null},
    onAutocomplete: (val) => {
      console.log(val);
    },
  };
```
