### ISSUE TITLE
Uncaught Error: Couldn't find materialize function ''modal' on element or the global Materialize object.

### ISSUE THREAD

**Issue by Smitjohn** [InfomediaLtd/angular2-materialize#247]
I am facing same issue in 'angular2-materialize'

Tooltip is working fine. but Model could not open. 

![image](https://cloud.githubusercontent.com/assets/26926265/24705404/620625a0-1a29-11e7-8ab9-661dc85da379.png)

webpack.config.js : 
`var webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {

    entry: {
        'app': './src/main.ts',
        'polyfills': [
            'core-js/es6',
            'core-js/es7/reflect',
            'zone.js/dist/zone',
        ]
    },
    output: {
        path: './dist',
        filename: '[name].[hash].js'
    },
    resolve: {
        alias: {
            "materialize-css": 'node_modules/materialize-css/dist/css/materialize.css',
            'materialize': 'node_modules/materialize-css/dist/js/materialize.js',
        },
        extensions: ['', '.js', '.ts', '.html', '.css']
    },
    externals: {
        jquery: 'jQuery'
    },
    module: {
        loaders: [
            { test: /\.component.ts$/, loader: 'ts!angular2-template' },
            { test: /\.ts$/, exclude: /\.component.ts$/, loader: 'ts' },
            { test: /\.html$/, loader: 'raw' },
            { test: /\.css$/, loader: 'raw' },
            
            { test: /\.css$/, loader: 'style-loader!css-loader' },
            { test: /.(png|woff(2)?|eot|ttf|svg)(\?[a-z0-9=\.]+)?$/, loader: 'url-loader?limit=100000' }
        ]
    },
    plugins: [
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery",
            "window.jQuery": "jquery",
            Hammer: "hammerjs/hammer"
        }),
        new webpack.optimize.CommonsChunkPlugin({
            name: 'polyfills'
        }),
        new HtmlWebpackPlugin({
            template: './src/index.html'
        }),
        new webpack.DefinePlugin({
            app: {
                environment: JSON.stringify(process.env.APP_ENVIRONMENT || 'development')
            }
        })
    ]

};`

======================================================

app.module.ts

`import { MaterializeDirective } from "angular2-materialize";
import { MaterializeModule } from "./src/index";

imports: [ MaterializeModule]
declarations: [MaterializeDirective]`

**Comment by rubyboy** [comment]
@Smitjohn try with the latest version of angular2-materialize. If it's still not working for you, after following the setup instructions, let us know and if you cold provide a reproducible repository that would be great. Thanks.
