### ISSUE TITLE
Angular 4 compatibility

### ISSUE THREAD

**Issue by ninjah187** [InfomediaLtd/angular2-materialize#249]
Hi. Is there Angular 4 compatibility predicted?

**Comment by kinoxhio** [comment]
I have it in a test project, it works fine, but it has an error in materialize="dropdown"  button

**Comment by maheshp212** [comment]
I am also searching for the angular 4 compatibility please let me know the possiblity

**Comment by kinoxhio** [comment]
I update a proyect since angular2 to angular4 with angular2-materialize, works fine

**Comment by nelsonmorais** [comment]
@kinoxhio Can you share how do you have it working? After updating to Angular 4 (4.0.2) and angular2-materiazlize to 6.7.2 I have the following messages:
+-- UNMET PEER DEPENDENCY @angular/common@4.0.2
+-- UNMET PEER DEPENDENCY @angular/core@4.0.2
`-- UNMET PEER DEPENDENCY materialize-css@0.98.2

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
**npm WARN angular2-materialize@6.7.2 requires a peer of @angular/common@^2.1.2 but none was installed.
npm WARN angular2-materialize@6.7.2 requires a peer of @angular/core@^2.1.2 but none was installed.
npm WARN angular2-materialize@6.7.2 requires a peer of materialize-css@^0.97.8 but none was installed.
npm WARN @angular/forms@2.4.10 requires a peer of @angular/common@2.4.10 but none was installed.
npm WARN @angular/forms@2.4.10 requires a peer of @angular/core@2.4.10 but none was installed.**
npm ERR! code 1

**Comment by rubyboy** [comment]
Angular 4 update is coming. If you check out the master branch on the repo you'll see some changes to align to the Angular CLI and upgrade of various libraries. We'll publish once it's been properly tested. Soon... :)

**Comment by kinoxhio** [comment]
@nelsonmorais in my case ..
1. update angular-cli to 1.0
2. create new angular 4 proyect
3. Install the last version angular2-materialize
4. copy and paste components since angular 2 proyect

that all, I had some warnings about dependencies but works fine

**Comment by nelsonmorais** [comment]
@rubyboy & @kinoxhio Thanks for the quick responses!

**Comment by rubyboy** [comment]
Should be resolved with the latest v9 release of angular2-materialize
@ninjah187 @maheshp212 @kinoxhio @nelsonmorais  can you confirm this issue can be resolved.

**Comment by kinoxhio** [comment]
@rubyboy in my case , i had some warning when installed again
<img width="1193" alt="screen shot 2017-04-27 at 11 42 53" src="https://cloud.githubusercontent.com/assets/10503998/25490256/a1a9fa40-2b42-11e7-8129-ebb73e7b8f83.png">

**Comment by rubyboy** [comment]
@kinoxhio looking at the screenshot above you are still using an old version of angular2-materialize (6.7.2).
Please update to the latest version I mentioned - v9:
![image](https://cloud.githubusercontent.com/assets/1908166/25515237/d926e3e4-2beb-11e7-9d2f-c87b8d40abe0.png)
Thanks.

**Comment by kinoxhio** [comment]
You were right @rubyboy , after than , works fine. Thanks!

**Comment by rubyboy** [comment]
Cool, thanks for checking. Closing this issue now.
