### ISSUE TITLE
Search option in select

### ISSUE THREAD

**Issue by akshath4u** [InfomediaLtd/angular2-materialize#25]
Is there any option to add search field for select form control?

**Comment by Kravs** [comment]
I think it is not present even in original materialize-css project :(

**Comment by rubyboy** [comment]
Thanks @Kravs for this input.
@akshath4u , I suggest opening this issue in the https://github.com/Dogfalo/materialize repository.
I'll close this one for now, until it's implemented in the materialize-css project.
