### ISSUE TITLE
Wave effect on button

### ISSUE THREAD

**Issue by MihailoVasovic** [InfomediaLtd/angular2-materialize#250]
Hey, i have issue with wave effect on button. Problem is that each time i click on button it's lighter util its all white. I'm using Angular 4

**Comment by rubyboy** [comment]
Sounds very cool. How did you manage to get that effect? :)
Does it also happen in the example app? http://angular2-materialize.surge.sh/#/Buttons

**Comment by MihailoVasovic** [comment]
No, on this example it is working just fine, but in my application when i click button, that light color doesn't disappear, instead it is still there, and by each new click on button it's lighter and lighter until it get total white

**Comment by MihailoVasovic** [comment]
OK i solved it, my imports were wrong. Sorry for this, you can close issue now.

**Comment by michaelspeed** [comment]
can you tell me what wast the import? facing same issue

**Comment by MihailoVasovic** [comment]
Same as in example here

**Comment by yume117** [comment]
I have the same issue and can't fix it :/ can we have more detail ?
