### ISSUE TITLE
Modal options is not working

### ISSUE THREAD

**Issue by juankmarin** [InfomediaLtd/angular2-materialize#254]
The modal options is not working, apparently just work the "ready" function, opacity, dismissible, startingTop, etc., is not working

**Comment by rubyboy** [comment]
Can you try the sample project and see if that is working for you?
We've used dismissible there and it works quite well: http://angular2-materialize.surge.sh/#/Dialogs (try "MODAL 1").
Here's the code: https://github.com/InfomediaLtd/angular2-materialize/blob/master/sample/src/app/components/dialogs.ts#L13
