### ISSUE TITLE
Materialize character counter - taking length input from a variable name

### ISSUE THREAD

**Issue by govindrrathi** [InfomediaLtd/angular2-materialize#255]
I am trying to show character counters for my forms where the data for length needs to come from a variable, as below

```
<input
      [type]="field.metaData.type"
      [id]="field.metaData.name"
      [formControl]="field.formControl"
      class="form-control"
      materialize="characterCounter"
      [length]="field.metaData.maxLength"
      [maxlength]="field.metaData.maxLength"
      />
```

I am seeing following error in browser developer console.
Can't bind to 'length' since it isn't a known property of 'input'. ("
      class="form-control"
      materialize="characterCounter"
      [ERROR ->][length]="field.metaData.maxLength"
      [maxlength]="field.metaData.maxLength"
      />

Can I get some help?

**Comment by rubyboy** [comment]
Replace ```[length]``` with ```[attr.length]```

**Comment by govindrrathi** [comment]
@rubyboy, thank you!!
