### ISSUE TITLE
k.velocity is not a function

### ISSUE THREAD

**Issue by akashbiz** [InfomediaLtd/angular2-materialize#256]
ERROR TypeError: k.velocity is not a function
    at h (materialize.js:3)
    at HTMLDivElement.<anonymous> (materialize.js:3)
    at HTMLDivElement.dispatch (jquery.js:4737)
    at HTMLDivElement.elemData.handle (jquery.js:4549)
    at Object.trigger (jquery.js:7807)
    at HTMLDivElement.<anonymous> (jquery.js:7875)
    at Function.each (jquery.js:365)
    at jQuery.fn.init.each (jquery.js:137)
    at jQuery.fn.init.trigger (jquery.js:7874)
    at jQuery.fn.init.open (materialize.js:3)
    at jQuery.fn.init.a.fn.modal (materialize.js:3)
    at HTMLDocument.<anonymous> (materialize-directive.js:185)
    at fire (jquery.js:3187)
    at Object.add [as done] (jquery.js:3246)
    at jQuery.fn.init.jQuery.fn.ready (jquery.js:3496)
View_OperationalComponent_1 @ OperationalComponent.html:6
DebugContext_.logError @ core.es5.js:13000
ErrorHandler.handleError @ core.es5.js:1145
next @ core.es5.js:4774
schedulerFn @ core.es5.js:3848
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ core.es5.js:3834
NgZone.triggerError @ core.es5.js:4205
onHandleError @ core.es5.js:4166
ZoneDelegate.handleError @ zone.js:369
Zone.runTask @ zone.js:168
ZoneTask.invoke @ zone.js:460

ERROR CONTEXT DebugContext_ {view: Object, nodeIndex: 13, nodeDef: Object, elDef: Object, elView: Object}

I am using [Angular2 Cognito Quickstart](https://github.com/awslabs/aws-cognito-angular2-quickstart) with Materializecss. I am trying to open modal but I  am facing the above issue. I have tried many issue related to this but many solutions includes webpack plugin addition or defining externals in webpack.config.js. I don't contain webpack.config.js file in my folder structure created by this quickstart. 
Please help.

**Comment by n0mid** [comment]
Try to add in app.component constructor next line: 
(<any>window).$ = (<any>window).jQuery;

Maybe it will help you.

**Comment by rubyboy** [comment]
In addition to what @n0mid said, please make sure you've followed the instructions for adding angular2-materialize to the Angular CLI.

**Comment by rubyboy** [comment]
Should be good in the latest release of angular2-materialize, following the CLI instructions

**Comment by guibot17** [comment]
@rubyboy well, it looks like it's not good yet. I followed the guide but I'm still getting the same error.
Any help will be appreciated

**Comment by rubyboy** [comment]
@guibot17 share a repo and someone may be able to help. With the CLI it's very important to make sure you've made all changes to the angular-cli.json properly

**Comment by guibot17** [comment]
@rubyboy this is what I have:

package.json:
"dependencies": {
    "@angular/animations": "^4.2.2",
    "@angular/common": "^4.2.2",
    "@angular/compiler": "^4.2.2",
    "@angular/compiler-cli": "^4.2.2",
    "@angular/core": "^4.2.2",
    "@angular/forms": "^4.2.2",
    "@angular/http": "^4.2.2",
    "@angular/material": "^2.0.0-beta.6",
    "@angular/platform-browser": "^4.2.2",
    "@angular/platform-browser-dynamic": "^4.2.2",
    "@angular/platform-server": "^4.2.2",
    "@angular/router": "^4.2.2",
    "angular-in-memory-web-api": "^0.3.2",
    "angular2-materialize": "^15.0.4",
    "angularfire2": "^4.0.0-rc.1",
    "core-js": "^2.4.1",
    "firebase": "^4.1.2",
    "hammerjs": "^2.0.8",
    "jquery": "^2.2.4",
    "materialize-css": "^0.98.2",
    "rxjs": "^5.1.0",
    "typescript": "^2.3.4",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.1.1",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "2.5.45",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "node-sass": "^4.5.3",
    "protractor": "~5.1.2",
    "raw-loader": "^0.5.1",
    "sass-loader": "^6.0.6",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }

angular-cli:
"styles": [
        "../node_modules/materialize-css/dist/css/materialize.css",
        "styles.sass",
        "_theme.sass"
      ],
      "scripts": [
        "../node_modules/hammerjs/hammer.js",
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/materialize-css/dist/js/materialize.js"
      ]

app.module:
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { ReactiveFormsModule, FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { MaterialModule } from '@angular/material';
import { AngularFireModule } from 'angularfire2';
import { AngularFireDatabaseModule } from 'angularfire2/database';
import { AngularFireAuthModule, AngularFireAuth } from 'angularfire2/auth';
import { environment } from '../environments/environment';

import 'hammerjs';
import 'materialize-css';
import { MaterializeModule } from 'angular2-materialize';

import { AppRoutingModule }     from './app-routing.module';
import { AppComponent } from './app.component';
import { HomeComponent } from './home/home.component';
import { HeaderComponent } from './header/header.component';
import { FooterComponent } from './footer/footer.component';
import { AuthService } from './auth/auth.service';
import { UserService } from './auth/user.service';

@NgModule({
  declarations: [
    AppComponent,
    HomeComponent,
    HeaderComponent,
    FooterComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    ReactiveFormsModule,
    FormsModule,
    HttpModule,
    MaterialModule,
    AngularFireModule.initializeApp(environment.firebase, 'bzh-header'),
    AngularFireDatabaseModule,
    AngularFireAuthModule,
    AppRoutingModule,
    MaterializeModule
  ],
  providers: [
    AuthService,
    UserService
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }

As you may see, I'm using Angular 4.2.2 along with materialize-css 0.98.2, jquery ^2.2.4, hammer.js ^2.0.8.
I'm facing this issue when trying to open a modal.

Your help is greatly appreciated.

**Comment by akashbiz** [comment]
Still not resolved. @rubyboy . Any update @guibot17 ?

**Comment by akashbiz** [comment]
Hello, I am using angular2 with webpack and I am trying to open a modal but getting an below error:
`ERROR TypeError: k.velocity is not a function
    at h (materialize.js:3)
    at HTMLDivElement.<anonymous> (materialize.js:3)
    at HTMLDivElement.dispatch (jquery.js:4737)
    at HTMLDivElement.elemData.handle (jquery.js:4549)
    at Object.trigger (jquery.js:7807)
    at HTMLDivElement.<anonymous> (jquery.js:7875)
    at Function.each (jquery.js:365)
    at jQuery.fn.init.each (jquery.js:137)
    at jQuery.fn.init.trigger (jquery.js:7874)
    at jQuery.fn.init.open (materialize.js:3)
    at jQuery.fn.init.a.fn.modal (materialize.js:3)
    at HTMLDocument.<anonymous> (materialize-directive.js:213)
    at fire (jquery.js:3187)
    at Object.add [as done] (jquery.js:3246)
    at jQuery.fn.init.jQuery.fn.ready (jquery.js:3496)`

I tried all the solutions mentioned above but nothing worked for me. Can anyone share the webpack.conf.js and list the settings which perfectly worked.

**Its urgent, please help**. Thanks in advance.

**Comment by guibot17** [comment]
@akashbiz , yes! It was due to the fact that I was importing materialze-css in my `app.module.ts` as such:
`import "materialize-css"`
`import { MaterializeModule } from 'angular2-materialize'`

You may just remove it because it's not needed in this case; leave the`'angular2-materialize'` import: 
`import { MaterializeModule } from 'angular2-materialize'`

I hope this helps.
#256

**Comment by akashbiz** [comment]
Hey Thanks a lot @guibot17 , It solved my issue.

**Comment by SPradnya** [comment]
@guibot17 @rubyboy @akashbiz 
I tried your solution to remove import statement **import "materialize-css"**. It does not work for me.

Also I followed the instruction provided on link [angular2-materialize](https://github.com/InfomediaLtd/angular2-materialize).
I tried both ways given on link but nothing works for me.
1) Installing and configuring angular2-materialize with webpack
2) Installing & configuring angular2-materialize in projects created with the Angular CLI

Following are some details for **2nd** option and I get error like:
ERROR TypeError: k.velocity is not a function
    at h (materialize.js:3)
    at HTMLDivElement.<anonymous> (materialize.js:3)
    at HTMLDivElement.dispatch (jquery.js:4737)
    at HTMLDivElement.elemData.handle (jquery.js:4549)
    at Object.trigger (jquery.js:7807)
    at HTMLDivElement.<anonymous> (jquery.js:7875)
    at Function.each (jquery.js:365)
    at jQuery.fn.init.each (jquery.js:137)
    at jQuery.fn.init.trigger (jquery.js:7874)
    at jQuery.fn.init.open (materialize.js:3)
    at jQuery.fn.init.a.fn.modal (materialize.js:3)
    at HTMLDocument.<anonymous> (materialize-directive.js:185)
    at fire (jquery.js:3187)
    at Object.add [as done] (jquery.js:3246)
    at jQuery.fn.init.jQuery.fn.ready (jquery.js:3496)

Following is my configuration in files:
for **angular-cli.json**  
"styles": [
      	"../node_modules/materialize-css/dist/css/materialize.css",
      	"styles.css"
      ],
      "scripts": [
		"../node_modules/jquery/dist/jquery.js",
  		"../node_modules/hammerjs/hammer.js",
  		"../node_modules/materialize-css/dist/js/materialize.js"
	  ],

for **app.module.ts** - Added import statement
import { MaterializeModule } from 'angular2-materialize';

Please help.
Thanks in advance.

**Comment by guibot17** [comment]
@SPradnya 
If I understand correctly, you tried the following:

**1. Project created by Angular-CLI**:

**app.module.ts** file

import { MaterializeModule } from "angular2-materialize";

@NgModule({
   imports: [
     //...
     MaterializeModule,
   ],
   //...
})
Along with the settings that you posted for the **angular-cli.json**

**2. Project configured with webpack**:

**app.module.ts** file

import 'materialize-css';
import { MaterializeModule } from "angular2-materialize";

@NgModule({
  imports: [
    //...
    MaterializeModule,
  ],
  //...
})

**index.html** file

`<head>`
`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">`
`</head>`

And in your **webpack config** file:

const ProvidePlugin = require('webpack/lib/ProvidePlugin');
module.exports = {
  //...
  plugins: [
      new ProvidePlugin({
          "window.jQuery": "jquery",
          Hammer: "hammerjs/hammer"
      })
  ]
  //...
};

Please confirm.
Thanks

**Comment by SPradnya** [comment]
@guibot17 
Yes. Done the same thing.
