### ISSUE TITLE
Feature Discovery

### ISSUE THREAD

**Issue by aguilarguisado** [InfomediaLtd/angular2-materialize#257]
Amazing work with this project.

Have you thought (or planned) the development of "Fetaure Discovery" feature? Will you? Was it already developed?

Here is the link: http://materializecss.com/feature-discovery.html

**Comment by rubyboy** [comment]
Cool feature. I didn't know about it. Is that a new one?
Does it work with the MaterializeAction?

**Comment by aguilarguisado** [comment]
I 'm totally new with Materialize so I can't tell you if it is new or not.
I could tell you after working more on angular2-materialize.

I saw this feature in a plain html-css project that I'm migrating to Angular2 and I missed it here.

**Comment by rubyboy** [comment]
I think it's part of the latest version (98). We can add a sample of using it after the upgrade: https://github.com/InfomediaLtd/angular2-materialize/issues/221

**Comment by aguilarguisado** [comment]
Thank you very much @rubyboy for your fast responses! ;)

**Comment by rubyboy** [comment]
@aguilarguisado I've added sample code in https://github.com/InfomediaLtd/angular2-materialize/blob/master/sample/src/app/buttons/buttons.component.html :
```html
<div class="fixed-action-btn horizontal click-to-toggle">
  <a id="menu" class="btn-floating btn-large red">
    <i class="material-icons">menu</i>
  </a>
  <ul>
    <li><a class="btn-floating red"><i class="material-icons">insert_chart</i></a></li>
    <li><a class="btn-floating yellow darken-1"><i class="material-icons">format_quote</i></a></li>
    <li><a class="btn-floating green"><i class="material-icons">publish</i></a></li>
    <li><a class="btn-floating blue"><i class="material-icons">attach_file</i></a></li>
  </ul>
</div>
<!-- Tap Target Structure -->
<div class="tap-target" data-activates="menu" materialize [materializeActions]="tapTargetActions">
  <div class="tap-target-content">
    <h5>Title</h5>
    <p>A bunch of text</p>
  </div>
</div>
```
```js
openTapTarget() {
    this.tapTargetActions.emit({action:"tapTarget",params:["open"]});
  }
  closeTapTarget() {
    this.tapTargetActions.emit({action:"tapTarget",params:["close"]});
  }
```

![image](https://cloud.githubusercontent.com/assets/1908166/25553466/4cd378fe-2cbc-11e7-8e2d-303dd597e5f5.png)
