### ISSUE TITLE
Resolving MaterializeModule

### ISSUE THREAD

**Issue by Stilos** [InfomediaLtd/angular2-materialize#259]
Hi,

I have created new project wit "ng new" and after that added angular2-materialize following your instructions for angular CLI. I had several issues but after updating to typescript 2.2.2 i am left with this one and can't handle it.
```
ERROR in Error encountered resolving symbol values statically. Calling function
'?makeDecorator', function calls are not supported. Consider replacing the funct
ion or lambda with a reference to an exported function, resolving symbol NgModul
e in E:/Stuff/Projects/KosCen/CustomersCards/customers-app/node_modules/angular2
-materialize/node_modules/@angular/core/core.d.ts, resolving symbol MaterializeM
odule in E:/Stuff/Projects/KosCen/CustomersCards/customers-app/node_modules/angu
lar2-materialize/materialize-module.d.ts, resolving symbol MaterializeModule in
E:/Stuff/Projects/KosCen/CustomersCards/customers-app/node_modules/angular2-mate
rialize/materialize-module.d.ts
```

Could you please help?

**Comment by rubyboy** [comment]
You could try comparing your project to the sample here: https://github.com/InfomediaLtd/angular2-materialize/tree/master/sample
It's also typescript 2.2.2 and built from the Angular CLI, so it should work the same way.
If it's still not working for you, please share a repo that reproduces the problem and someone could take a look and help out.

**Comment by pain0486** [comment]
I'm getting this issue too. It was working fine, the it just started throwing the error. My Environment is Angluar Cli 1.0, Typescript 2.2.2, Angular 4.1.0-rc.0, angular2-materialize: 9.0.1

**Comment by rubyboy** [comment]
@Stilos @pain0486 see attached a zipped folder of a fresh new "ng new" with the CLI with the addition of angular2-materialize following the steps described in the README of this repo. Worked well for me, so I'm wondering what is the difference between this and your use case.
[test-cli.zip](https://github.com/InfomediaLtd/angular2-materialize/files/963514/test-cli.zip)

**Comment by rubyboy** [comment]
@Stilos @pain0486 give the latest 9.0.2 fix a try - I made some changes that could fix the AOT problems you're experiencing.
If it's still failing, are you able to point me to a repository with a reproducible error that I can look at?
Thanks.

**Comment by pain0486** [comment]
I rolled back to 6.7.2 so I could keep working yesterday. Will tey again this moring with changes.

**Comment by pain0486** [comment]
@rubyboy So far so good this morning. I have been able to upgrade and run. Build and rebuild. Thanks!
