### ISSUE TITLE
material select incorrect binding

### ISSUE THREAD

**Issue by pandazzurro** [InfomediaLtd/angular2-materialize#260]
Hi, I have problem with two combo box.
First combo update second data source combo box.
Second combo must have 2 result but I can see only one. Html result is:
![image](https://cloud.githubusercontent.com/assets/7531792/25518438/12def0ce-2bf4-11e7-87dc-1dc954089461.png)
View resut is:
![image](https://cloud.githubusercontent.com/assets/7531792/25518471/2d1ad002-2bf4-11e7-8fec-3e5369b4c696.png)

Section with attribute "_ngcontent-bnu-2" is correct data source but html is incorrect. 
I must have "DDT" and "Documento Semplice".

Datasource is correct but html non show me correct result.
My code:
```html
<form materialize class="col s12" #rapportiniForm="ngForm" (ngSubmit)="onSubmit(rapportiniForm.value)">    
    <div class="row">
      <div class="input-field col s6">        
        <select materialize="material_select" name="dittaOption" id="dittaOption" [(ngModel)]="dittaOption" #dittaRef required 
                [ngClass]="{'validate valid' : dittaRef.valid, 'validate invalid': !dittaRef.valid }"
                (change)="this.getTipiDocumentoUI(dittaOption)" [materializeSelectOptions]="dittaOption">
          <option value="" disabled selected>Seleziona Ditta</option>
          <option *ngFor="let d of ditte">{{d.RagioneSociale}}</option>
        </select>
        <label for="dittaOption">Inserire una ditta</label>      
      </div>     
      <div class="input-field col s6">          
        <select materialize="material_select" name="tipologiaOption" id="tipologiaOption" [(ngModel)]="tipologiaOption" #tipologiaRef required 
                [ngClass]="{'validate valid' : tipologiaRef.valid, 'validate invalid': !tipologiaRef.valid }"
                [materializeSelectOptions]="tipologiaOption">
          <option value="" disabled selected>Seleziona Tipologia</option>
          <option *ngFor="let td of tipiDocumento">{{td.Nome}}</option>
        </select>
        <label for="tipologiaOption">Inserire una tipologia</label>
      </div>      
    </div>
</form>
```

**Comment by rubyboy** [comment]
Not sure I understand the problem.
Here's a plunker with your example: https://embed.plnkr.co/ebNCT1xs63uoo9XVnv9C/
Could you point out the issue or create a plunker that reproduces it?
Thanks.

**Comment by pandazzurro** [comment]
Base example:
https://plnkr.co/edit/hwahys

Materialize example:
1) not work properly 2 combo
https://plnkr.co/edit/UMp5Nq 

2) value and ngValue not work properly:
https://plnkr.co/edit/4b0r5Q


Mock rest api: https://demo8023482.mockable.io/DittaTipoDocumenti

Thanks

**Comment by rubyboy** [comment]
@pandazzurro for example #1, correct me if I'm wrong, but it seems the problem is related to the fact you're changing the 2nd dropdown every time you change your selection in the first one.

If you remove the ```(change)="this.getTipiDocumentoUI(dittaOption)"``` then it works as expected ( you can kick off the retrieval inside ngOnInit ```this.getTipiDocumento(this.ditte``` ):
![image](https://cloud.githubusercontent.com/assets/1908166/25574215/fb2971f8-2e54-11e7-9435-e9053be7bf96.png)

**Comment by pandazzurro** [comment]
You're right @rubyboy.
I try ChangeDetectorRef but not work. 
**However data is present in DOM**!

**Comment by rubyboy** [comment]
Can you try creating a simpler example, where you don't recreate the data again on every change? That would be a lot easier to understand and debug when it's not tied to other functionality and services that are in the way, making it difficult for me to isolate the issue.
Something like what I sent before. If you could try taking that one and changing it to create the problem that would be great.

**Comment by pandazzurro** [comment]
Like this: https://plnkr.co/edit/xlE0PT?
This example work properly. I had already tried.

**Comment by rubyboy** [comment]
Yes, exactly.
Try to make it fail, so someone could help you out and check if it's a problem in your code or in the library. Otherwise, it's very difficult to reproduce in the angular2-materialize codebase.

**Comment by pandazzurro** [comment]
My base example work well without styles: https://plnkr.co/edit/hwahys 
The problem should be in Materialize?

**Comment by rubyboy** [comment]
If you try using it without angular2-materialize and it's still happening then yes.
Either way, a clean example would make it easy to whoever is trying to fix it (in any of the libraries) much easier.
