### ISSUE TITLE
Errors when building for production with Angular 4.1.0 and angular2-materialize 9.0.1

### ISSUE THREAD

**Issue by biskazz** [InfomediaLtd/angular2-materialize#261]
I get the following errors when using `build --prod` after updating to 9.0.1
I can't figure out what the issue is. It works fine with 6.7.2.
TS version: 2.2.2

`ERROR in ./src/$$_gendir/app/app.module.ngfactory.ts
Module not found: Error: Can't resolve 'angular2-materialize/materialize-module' in '/Users/biskazz/Programming/DronexerDev/DronexerClient/src/$$_gendir/app'
 @ ./src/$$_gendir/app/app.module.ngfactory.ts 20:0-67
 @ ./src/main.ts
 @ multi ./src/main.ts`

`ERROR in ./src/$$_gendir/app/components/home/home.component.ngfactory.ts
Module not found: Error: Can't resolve 'angular2-materialize/materialize-directive' in '/Users/biskazz/Programming/DronexerDev/DronexerClient/src/$$_gendir/app/components/home'
 @ ./src/$$_gendir/app/components/home/home.component.ngfactory.ts 11:0-70
 @ ./src/$$_gendir/app/app.module.ngfactory.ts
 @ ./src/main.ts
 @ multi ./src/main.ts`

`ERROR in ./src/$$_gendir/app/components/register/register.component.ngfactory.ts
Module not found: Error: Can't resolve 'angular2-materialize/materialize-directive' in '/Users/biskazz/Programming/DronexerDev/DronexerClient/src/$$_gendir/app/components/register'
 @ ./src/$$_gendir/app/components/register/register.component.ngfactory.ts 11:0-70
 @ ./src/$$_gendir/app/app.module.ngfactory.ts
 @ ./src/main.ts
 @ multi ./src/main.ts`

`ERROR in ./src/$$_gendir/app/components/upload/upload.component.ngfactory.ts
Module not found: Error: Can't resolve 'angular2-materialize/materialize-directive' in '/Users/biskazz/Programming/DronexerDev/DronexerClient/src/$$_gendir/app/components/upload'
 @ ./src/$$_gendir/app/components/upload/upload.component.ngfactory.ts 10:0-70
 @ ./src/$$_gendir/app/app.module.ngfactory.ts
 @ ./src/main.ts
 @ multi ./src/main.ts`

`ERROR in ./src/$$_gendir/app/components/profile/profile.component.ngfactory.ts
Module not found: Error: Can't resolve 'angular2-materialize/materialize-directive' in '/Users/biskazz/Programming/DronexerDev/DronexerClient/src/$$_gendir/app/components/profile'
 @ ./src/$$_gendir/app/components/profile/profile.component.ngfactory.ts 9:0-70
 @ ./src/$$_gendir/app/app.module.ngfactory.ts
 @ ./src/main.ts
 @ multi ./src/main.ts`

`ERROR in ./src/$$_gendir/app/components/navbar/navbar.component.ngfactory.ts
Module not found: Error: Can't resolve 'angular2-materialize/materialize-directive' in '/Users/biskazz/Programming/DronexerDev/DronexerClient/src/$$_gendir/app/components/navbar'
 @ ./src/$$_gendir/app/components/navbar/navbar.component.ngfactory.ts 11:0-70
 @ ./src/$$_gendir/app/app.component.ngfactory.ts
 @ ./src/$$_gendir/app/app.module.ngfactory.ts
 @ ./src/main.ts
 @ multi ./src/main.ts`

`ERROR in ./src/$$_gendir/app/components/post/post.component.ngfactory.ts
Module not found: Error: Can't resolve 'angular2-materialize/materialize-directive' in '/Users/biskazz/Programming/DronexerDev/DronexerClient/src/$$_gendir/app/components/post'
 @ ./src/$$_gendir/app/components/post/post.component.ngfactory.ts 9:0-70
 @ ./src/$$_gendir/app/components/profile/profile.component.ngfactory.ts
 @ ./src/$$_gendir/app/app.module.ngfactory.ts
 @ ./src/main.ts
 @ multi ./src/main.ts`

`ERROR in ./src/$$_gendir/app/components/modal-delete/modal-delete.component.ngfactory.ts
Module not found: Error: Can't resolve 'angular2-materialize/materialize-directive' in '/Users/biskazz/Programming/DronexerDev/DronexerClient/src/$$_gendir/app/components/modal-delete'
 @ ./src/$$_gendir/app/components/modal-delete/modal-delete.component.ngfactory.ts 9:0-70
 @ ./src/$$_gendir/app/components/post/post.component.ngfactory.ts
 @ ./src/$$_gendir/app/components/profile/profile.component.ngfactory.ts
 @ ./src/$$_gendir/app/app.module.ngfactory.ts
 @ ./src/main.ts
 @ multi ./src/main.ts`

**Comment by rubyboy** [comment]
I think it's related to AOT.
Are you able to check if this works? ```ng build --prod --aot false```
Might be a good temp workaround, until we figure out how to fix this.
Thanks.

**Comment by kinoxhio** [comment]
First, @biskazz check if module is imported 
<img width="495" alt="screen shot 2017-04-28 at 09 17 52" src="https://cloud.githubusercontent.com/assets/10503998/25528342/b6f3043a-2bf3-11e7-8360-b7ded24ec93b.png">

**Comment by kinoxhio** [comment]
@biskazz I had the same problem , but works with @rubyboy ng build --prod --aot false
<img width="1888" alt="screen shot 2017-04-28 at 09 36 09" src="https://cloud.githubusercontent.com/assets/10503998/25528913/4dea1a7a-2bf6-11e7-8ee4-bc29d8ddc30c.png">

**Comment by biskazz** [comment]
@rubyboy Yes, it works w/o AOT. 
@kinoxhio It is imported, without it being imported it wouldn't have worked at all. :)

**Comment by luketn** [comment]
This issue is resolved in version 10.0.0. Please update and confirm.
![image](https://cloud.githubusercontent.com/assets/1756555/25552213/36f958ee-2cd7-11e7-8658-b9beb01ffdb9.png)

**Comment by kinoxhio** [comment]
@luketn yes, it works! Thanks.

**Comment by biskazz** [comment]
Totally works. Thanks for the amazing support.
