### ISSUE TITLE
Picktime initialize

### ISSUE THREAD

**Issue by AlejandroPeralTaboada** [InfomediaLtd/angular2-materialize#267]
Hi, When I try to use the time picker like this
`<input type="text" class="timepicker" materialize="pickatime">`
The browser shows on console.
`Couldn't find materialize function ''pickatime' on element or the global Materialize object`

It works for materialize="pickadate".

My versions for materialize-css and angular2-materialize are those:

"angular2-materialize": "^15.0.1"
"materialize-css": "^0.98.2"

Am I using the wrong word or  is it not implemented yet?

Thanks for all

**Comment by rubyboy** [comment]
Does MaterializeCSS (http://materializecss.com/forms.html) support ```pickatime```?

**Comment by AlejandroPeralTaboada** [comment]
working codepen
https://codepen.io/anon/pen/evQxPy

**Comment by rubyboy** [comment]
@AlejandroPeralTaboada what version of MaterializeCSS are you using? It's not 0.98.2
If you update your pen to bring in the official version ```https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js``` then it doesn't work anymore. I can see a request to add this feature to MaterializeCSS (https://github.com/Dogfalo/materialize/issues/473), but it's not in the master branch. Maybe you've forked a branch that has it and are using it?

**Comment by AlejandroPeralTaboada** [comment]
Oh, sry, my fault. 
I thought it could be implemented because in the materialize-directive.ts there is some references to timePicker like line 255
` private isTimePicker() {
      return (this._functionName && this._functionName === "pickatime");
    }`
Thanks  for everything. Great job

**Comment by rubyboy** [comment]
I should probably clean up that code :)
Thanks!

**Comment by biggiesmallsAG** [comment]
Hey rubyboy,

is this actually working or not? Im looking to implement a time picker for a view im working on.

**Comment by jacgec** [comment]
There is a Time Picker example on that page (http://materializecss.com/forms.html) that references pickatime.  Current version in their download link is 0.99.0, maybe they just added it?
