### ISSUE TITLE
Select element options from Observable

### ISSUE THREAD

**Issue by bliles** [InfomediaLtd/angular2-materialize#27]
I tried to populate the options of a select element using an Observable. The options are populated into the select element as can be seen by inspecting the DOM, but the materialize version of the select is empty. Using class='browser-default' allows me to have a functional select box, but obviously is visually undesirable. Any guidance?

Another dev with a similar issue:
http://stackoverflow.com/questions/36887895/multiple-select-in-materialize-css-with-angular2-not-rendering-dynamic-values

**Comment by rubyboy** [comment]
@bliles thanks for reporting this problem.
Are you happy to close this one as duplicate of https://github.com/InfomediaLtd/angular2-materialize/issues/21 and track the fix in the other issue? Hopefully we can figure it out soon.

**Comment by bliles** [comment]
Absolutely @rubyboy, sorry I didn't noticed this was the same core problem as #21.
