### ISSUE TITLE
Materialize.toast is not a function

### ISSUE THREAD

**Issue by jano42** [InfomediaLtd/angular2-materialize#270]
I forked the [Angular2-Webpack-Starter by InfomediaLts](https://github.com/InfomediaLtd/angular2-webpack-starter) to highlight this issue (and another one).

![image](https://cloud.githubusercontent.com/assets/3135683/26093939/2a2a2438-3a18-11e7-923f-979d5a6d4819.png)

https://github.com/jano42/angular2-webpack-starter

When launching app, going to "detail" menu, the error could be highlight by three ways:

1. click button "Toast1"
2. click button "Toast2"
3. select a dropdown option

![issue](https://cloud.githubusercontent.com/assets/3135683/26094579/c70d2730-3a1a-11e7-9784-370fa153e010.gif)

See detail.component.ts for code:
https://github.com/jano42/angular2-webpack-starter/blob/master/src/app/%2Bdetail/detail.component.ts

**Comment by rubyboy** [comment]
@jano42 thanks for the repo. I think I've got a solution. Are you able to verify it?

Update your webpack config to only have jQuery and Hammer provided:
```js
new ProvidePlugin({
    "window.jQuery": "jquery",
    Hammer: "hammerjs/hammer",
}),
```

Then, where you import angualr2-materialize (```shared.module.ts```), also import materialize-css explicitly:
```js
import 'materialize-css';
import { MaterializeModule } from 'angular2-materialize';
```

**Comment by jano42** [comment]
@rubyboy thanks it works with your workaround !!

**Comment by rubyboy** [comment]
Cool, I'll make that part of the official documentation then. Thanks for helping make this library better! :)
