### ISSUE TITLE
Unexpected behavior when adding <option></option> dynamically

### ISSUE THREAD

**Issue by LS8** [InfomediaLtd/angular2-materialize#273]
*I'm submitting a ...*

[X] bug report
[ ] feature request
[ ] support request

**Current behavior**
When pushing (a string) to an array, that is used inside of a select form element via \<option ngFor=...>. The list of options doesn't update immediately, even though it is re-assigned (this.array = this.array.slice()). However it re-renders **after** interaction (e.g selecting an option and re-open)  with the select form element happened and displays correctly.

**Expected behavior**
As soon as the array that is bound to the \<options> is re-assigned, the select form element should update and display any options, that have been added in the meantime.

**Minimal reproduction of the problem with instructions**

Expected behaviour using **vanilla** Angular only: http://plnkr.co/edit/ZiNi8y21fGJa0jUMmIj6?p=preview

Current behavior using angular2-materialize: https://plnkr.co/edit/vzuWR6s1KSPCdhadBScJ?p=preview

**Comment by criticalbh** [comment]
I am afraid that is not the part of angular2-materialize, it is rather materializecss issue. As you can see from [official documentation](http://materializecss.com/forms.html#select):

> ## Updating/Destroying Select
>If you want to update the items inside the select, just rerun the initialization code from above after editing the original select. Or you can destroy the material select with this function below, and create a new select altogether
>
>`$('select').material_select('destroy');`
>` $(document).ready(function() {
    $('select').material_select();
  });`

**Comment by LS8** [comment]
> so instead of using myArray.push(newValue) use myArray = [...myArray, newValue]

Didn't change the outcome for me. I think eventually reassigning the array should trigger an update of the values, regardless of reassigning using the spread operator or reassigning using `myArray = myArray.slice()`.

> I forked your plnkr, here is working example:
https://plnkr.co/edit/q8iDG029ZpS2VimmAbtr?p=preview

Whoops, I might have linked to a wrong plnkr (found it in another issue) or didn't save my fork correctly, because I don't see how your plnkr relates to this. I created a new one at: https://plnkr.co/edit/QwDqqLOGQYhRbbDOZFEP?p=preview and used your suggestion without success.

I also emitted the materialize_select Event to destroy and re-create the material select (in my local project) as suggested by the materializecss docs  but that didn't help neither.

**Comment by criticalbh** [comment]
In the previous plunker when you select value from first dropdown it will be appended in second one.

But here is another fork of plunker from your last comment and it is adding options: https://plnkr.co/edit/yCxoDDqRrrNMlxG0SIzI?p=preview

you forgot to specify `[materializeSelectOptions]="options"`

**Comment by LS8** [comment]
> But here is another fork of plunker from your last comment and it is adding options: https://plnkr.co/edit/yCxoDDqRrrNMlxG0SIzI?p=preview

> you forgot to specify [materializeSelectOptions]="options"

That's it, thank you very much! Problem solved. 👍
