### ISSUE TITLE
Couldn't find Materialize object on window. It is created by the materialize-css library. Please import materialize-css before importing angular2-materialize."

### ISSUE THREAD

**Issue by megetron** [InfomediaLtd/angular2-materialize#274]
I keep getting this error after followed  "Installing & configuring angular2-materialize in projects created with the Angular CLI" section.

```
index.js:4 Uncaught Error: Couldn't find Materialize object on window. It is created by the materialize-css library. Please import materialize-css before importing angular2-materialize.
    at Object.<anonymous> (index.js:4)
    at __webpack_require__ (bootstrap 4d052ca…:52)
    at Object.143 (app.component.ts:10)
    at __webpack_require__ (bootstrap 4d052ca…:52)
    at Object.135 (src async:7)
    at __webpack_require__ (bootstrap 4d052ca…:52)
    at Object.304 (main.bundle.js:208)
    at __webpack_require__ (bootstrap 4d052ca…:52)
    at webpackJsonpCallback (bootstrap 4d052ca…:23)
    at main.bundle.js:1
(anonymous) @ index.js:4
__webpack_require__ @ bootstrap 4d052ca…:52
143 @ app.component.ts:10
__webpack_require__ @ bootstrap 4d052ca…:52
135 @ src async:7
__webpack_require__ @ bootstrap 4d052ca…:52
304 @ main.bundle.js:208
__webpack_require__ @ bootstrap 4d052ca…:52
webpackJsonpCallback @ bootstrap 4d052ca…:23
(anonymous) @ main.bundle.js:1
```

**Comment by rubyboy** [comment]
This usually happens when materialize-css has not been imported correctly. Are you able to share a repo with this problem?

**Comment by megetron** [comment]
thank you for your quick response:
https://github.com/megetron/angular_test.git

**Comment by rubyboy** [comment]
@megetron you said you followed the instructions (https://github.com/InfomediaLtd/angular2-materialize#installing--configuring-angular2-materialize-in-projects-created-with-the-angular-cli) but I don't see the CLI changes in the cli.json (https://github.com/megetron/angular_test/blob/master/.angular-cli.json) :
![image](https://cloud.githubusercontent.com/assets/1908166/26307819/330b4b40-3eff-11e7-9d9d-20353429ef19.png)

**Comment by megetron** [comment]
seems like there are a file in node_modiles called "angular-cli.json" and there is the file called ".angular-cli.json" in the root of the project which is the one I was supposed to edit.

Thanks you so much for the quick response. this is definitely not an issue. closing it.

**Comment by akashbiz** [comment]
Facing this issue when using with webpack. Followed angular2-webpack-starter provided by you too. still getting same issue.
Also I want to know why we need to add materializecss manually when we import materialize-css in main module?
