### ISSUE TITLE
Dropdown not opened on click

### ISSUE THREAD

**Issue by RadouaneRoufid** [InfomediaLtd/angular2-materialize#275]
I used the same code as your demo 

```
     <!-- Dropdown Trigger -->
     <a materialize="dropdown" class='dropdown-button btn' href='#' data-activates='dropdown1'>Drop Me!</a>
     <!-- Dropdown Structure -->
     <ul id='dropdown1' class='dropdown-content'>
       <li><a>one</a></li>
       <li><a>two</a></li>
       <li class="divider"></li>
       <li><a>three</a></li>
     </ul>
```

When I click on the button, the dropdown does not open. But I add the attribute ```data-hover="true"``` it shows on hover. 

I'm using : 

-  "angular2-materialize": "^15.0.3",
- "materialize-css": "^0.98",
- "@angular": "^4.0.3",

jquery.js, hammer.js and materialize.min.js are all added correctly.

**Comment by rubyboy** [comment]
@RadouaneRoufid if you could share a repo (or plunker) that would be best to help out.
Otherwise, it's difficult to figure out any differences (which, as you pointed, there aren't any).

**Comment by RadouaneRoufid** [comment]
Trying to reproduce it on plunker showed me that I had a JQuery conflict which prevent the dropdown to work correctly.  Thank you very much and I'm very sorry @rubyboy, I waste your time.
