### ISSUE TITLE
How to make a carousel autoplay 

### ISSUE THREAD

**Issue by ssatz** [InfomediaLtd/angular2-materialize#277]
Hello, 

How to  make carousel autoplay using next method? 
Any example? I have tried using Materialize Actions passing as a parms. This didn't work out for me.

**Comment by rubyboy** [comment]
@ssatz I don't think Materialize supports autoplay for carousel.
I found this issue, related to autoplay, suggesting programmatic play: https://github.com/Dogfalo/materialize/issues/4523
If there is a way to do that via Materialize params or events, you should be able to use the MaterializeParams for that.
