### ISSUE TITLE
Tabs and routerLink

### ISSUE THREAD

**Issue by j-ibarra** [InfomediaLtd/angular2-materialize#278]
Hello i need some help, I'm trying to change tabs with the routes

`<div class="row">

      <div class="col s12">

        <ul class="tabs" materialize="tabs">

          <li class="tab col s3"><a href="#test1">Test 1</a></li>

          <li class="tab col s3"><a href="#test2">Test 2</a></li>

          <li class="tab col s3"><a href="#test3">Test 3</a></li>

          <li class="tab col s3"><a href="#test4">Test 4</a></li>

        </ul>

      </div>

      <div id="test1" class="col s12">Test 1</div>

      <div id="test2" class="col s12">Test 2</div>

      <div id="test3" class="col s12">Test 3</div>

      <div id="test4" class="col s12">Test 4</div>

    </div>`

this work fine

but when y try insert routerLink to use  <router-outlet></router-outlet> this render the components fine in <router-outlet></router-outlet>, but alwais render all div for test1 test2 test3 test4

`<div class="row">

      <div class="col s12">

        <ul class="tabs" materialize="tabs">

          <li class="tab col s3"><a href="#test1" routerLink="test1">Test 1</a></li>

          <li class="tab col s3"><a href="#test2" routerLink="test2">Test 2</a></li>

          <li class="tab col s3"><a href="#test3" routerLink="test3">Test 3</a></li>

          <li class="tab col s3"><a href="#test4" routerLink="test4">Test 4</a></li>

        </ul>

      </div>

      <div id="test1" class="col s12">Test 1</div>

      <div id="test2" class="col s12">Test 2</div>

      <div id="test3" class="col s12">Test 3</div>

      <div id="test4" class="col s12">Test 4</div>

    </div>

    <router-outlet></router-outlet>
`

some tips?

thanks!

**Comment by AlejandroPeralTaboada** [comment]
It's a bit chaotic, however i tried to make a small workaround, this is the [plunker ](https://embed.plnkr.co/LbTzo7gbzmgYbLlt4Rdr/)with my propose.
Hope it helps

**Comment by J-Ibarra** [comment]
@AlejandroPeralTaboada thanks very much this work fine in plunker, now I try to run in my project! Anything I do a feedback
