### ISSUE TITLE
DatePicker year value isn't set correctly

### ISSUE THREAD

**Issue by levitatejay** [InfomediaLtd/angular2-materialize#28]
I've found that when initializing the datepicker with a starting value it seems to init with the correct day & month but not year.

You can see this in the current model binding example:
http://angular2-materialize.surge.sh/#/modelbindings

**Comment by rubyboy** [comment]
Thanks for reporting this issue.

This was actually a problem in the example code. It wasn't setting the format properly, so datepicker couldn't pick up the year.
Here's the updated binding code:
```html
<input type="text" [(ngModel)]="datepicker" materialize="pickadate" [materializeParams]="[{format:'dd/mm/yyyy'}]" />
```

The example now works as expected: http://angular2-materialize.surge.sh/#/modelbindings
