### ISSUE TITLE
Is there any way to close the datepicker?

### ISSUE THREAD

**Issue by marciomsm** [InfomediaLtd/angular2-materialize#283]
@rubyboy is there any way to close the datepicker? How can I use callback events like onClose? Can I close datepicker calling some function or somenting like?

I am using a datepicker and when I select a date, I need to close and call a method.

Thanks.

**Comment by rubyboy** [comment]
Here's how you can do that:
```html
<input materialize="pickadate" [materializeActions]="actions" type="text" />
```
```js
this.actions.emit({action:"pickadate",params:["close"]});
```

**Comment by marciomsm** [comment]
@rubyboy thank you!
