### ISSUE TITLE
Modal - Center Space bugs at the modal footer

### ISSUE THREAD

**Issue by dreweird** [InfomediaLtd/angular2-materialize#284]
![image](https://cloud.githubusercontent.com/assets/16024897/26569858/f4b923a8-44c1-11e7-98b0-6decf8364ebb.png)

**Comment by RadouaneRoufid** [comment]
Same problem. I think it's due to  the property `max-height` applied to `.moda`l class.

```
.modal {
max-height: 70%;
}
```

**Comment by dreweird** [comment]
yeah it works using !important....the author should fix this issue

**Comment by rubyboy** [comment]
@dreweird @RadouaneRoufid is that a problem with MaterializeCSS or with the angular binding (angular2-materialize) ? Just trying to figure out if we need to fix anything, or needs to be pushed back to the CSS library.
Thanks.

**Comment by malorus** [comment]
@dreweird @RadouaneRoufid I had the same problem when using materialize in conjunction with bootstrap. When removed bootstrap everything worked fine. This conflict might appear as bootstrap uses the very same classes to style the component as materialize.
