### ISSUE TITLE
Materialize toast problem

### ISSUE THREAD

**Issue by luandr** [InfomediaLtd/angular2-materialize#285]
Hey, I tried this code from `http://angular2-materialize.surge.sh/#/Dialogs` to put in my study app. `<a class="btn" materialize="" ng-reflect-materialize-params="I am also a toast, 4000" ng-reflect-materialize-actions="[object Object]">Toast 2!</a>` but, nope... nada... nop... nothing...
Then i tried `<a class="btn" (click)="Materialize.toast('I am a toast', 4000)">Toast!</a>`
I had this amazing console error:
`TypeError: Cannot read property 'toast' of undefined at Object.eval [as handleEvent]`
Then "let me see tooltip":
`<a materialize="tooltip" class="btn tooltipped" data-position="bottom" data-delay="50" data-tooltip="I am tooltip">Hover me!</a>` works...

I import properly 'cause input work e.g.:
```<div class="row">
    <div class="input-field">
      <input id="text" type="text" class="validate" #nm>
      <label for="text">Cabeça de gelo</label>
    </div>
  </div>
```
[imgur](http://i.imgur.com/aQE9sEH.png)
I use 
``` angular2-materialize: ^15.0.4
    hammerjs: ^2.0.8
    jquery: ^2.2.4
    materialize-css: ^0.98.2
    @angular/cli: 1.0.4
     node: 6.10.3
     os: win32 x64
```
My importation follow this: [npmjs](https://www.npmjs.com/package/angular2-materialize#installing--configuring-angular2-materialize-in-projects-created-with-the-angular-cli) 
Someone can help me? I'm learning, so take it easy :) thx

**Comment by rubyboy** [comment]
@luandr this looks like a wrong config of the angular2-materialize. Maybe share the repo and someone could help.
I'd also check out the sample in the angular2-materialize repo - compare that with your setup of the angular-cli.

**Comment by luandr** [comment]
@rubyboy do you have any example how to use toast? Sorry but now i can't create an example and create a repo 'cause my internet connection Is insanely unstable. Can I comment here when I create? probably mid-week. Thanks for understanding.

**Comment by rubyboy** [comment]
Yes, here sample code for toast: https://github.com/InfomediaLtd/angular2-materialize/blob/master/sample/src/app/components/dialogs.ts
