### ISSUE TITLE
Facing non smooth transform.

### ISSUE THREAD

**Issue by roxcity** [InfomediaLtd/angular2-materialize#289]
The transform is not smooth for modal or slideable tabs. Is it just me or others also facing this problem? Did I do something wrong?

**Comment by rubyboy** [comment]
@roxcity I'm not seeing that in my projects. If there is any, I'd assume it's related to the animation implementation and not NG binding. Probably better to raise an issue here: https://github.com/Dogfalo/materialize/issues
