### ISSUE TITLE
Can't bind to 'materializeActions' since it isn't a known property of 'div'

### ISSUE THREAD

**Issue by rvgarimrj** [InfomediaLtd/angular2-materialize#291]
Hi, I just tried this example [here](http://materializecss.com/modals.html#!) but I get this error:
`Can't bind to 'materializeActions' since it isn't a known property of 'div'`

I have imported on app.module 
`imports [MaterializeModule]`

And on my supplier.ts:

    import {MaterializeAction} from 'angular2-materialize';
    import { Subscription } from 'rxjs/Subscription';
    import { Component, OnInit, OnDestroy, EventEmitter } from '@angular/core';

    import { SupplierService } from './../supplier.service';
    import { ActivatedRoute, Router } from '@angular/router';
    import { UsersService } from './../../shared/users.service';

    @Component({
      selector: 'app-supplier-detail',
      templateUrl: './supplier-detail.component.html',
      styleUrls: ['./supplier-detail.component.scss']
    })
    export class SupplierDetailComponent implements OnInit,OnDestroy {
      supplier: any;
      inscricao: Subscription;
      public hasCompany: boolean = false;
      public companyClass: string = "";
      public isOwner: boolean = false;
      modalActions = new EventEmitter<string|MaterializeAction>();
      
      constructor(
          private route: ActivatedRoute,
          private suppliersService: SupplierService,
          private UserService: UsersService,
          private router: Router
      ) { }

    ngOnInit() {
      
      this.UserService.show().subscribe();
        this.inscricao = this.route.params.subscribe(
          (params: any) => {
            let id = params['id'];
            this.supplier = this.suppliersService.getSupplier(id);
          }

        );
        this.UserService.userhasCompany$
        .takeWhile(() => !this.hasCompany)
        .subscribe(
          company => {
            this.hasCompany = company
          }
        );
        this.UserService.userisOwner$
        .takeWhile(() => !this.isOwner)
        .subscribe(
          isOwner => {
            this.isOwner = isOwner
          }
        );
      }
      openModal() {
        this.modalActions.emit({action:"modal",params:['open']});
      }
      closeModal() {
        this.modalActions.emit({action:"modal",params:['close']});
      }
      editSupplier(){
        this.router.navigate(['/fornecedor',this.supplier.id, 'editar']);
      } 
      deleteSupplier(property)
      {
        if (confirm("Você tem certeza que quer deletar o fornecedor " + this.supplier.name + " e todos os produtos relacionados a ele ?")) {
          // this.ReservationService.cancel(property.reservation.id)
          //   .subscribe(data => {
          //     var index = this.pending.indexOf(property.id);
          //     this.pending.splice(index, 1);
          //   }
          // );
        }
        return false;
      }
      ngOnDestroy(){
        this.inscricao.unsubscribe();
      }

    }

and on my supplier.html:

         `<div id="modal1" class="modal bottom-sheet" materialize="modal" [materializeActions]="modalActions">
        <div class="modal-content">
          <h4>Modal Header</h4>
          <p>A bunch of text</p>
        </div>
        <div class="modal-footer">
          <a class="waves-effect waves-green btn-flat" (click)="closeModal()">Close</a>
          <a class="modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
        </div>
      </div>`

but I cant find the error.

**Comment by rubyboy** [comment]
This usually happens when MaterializeModule wasn't added to the NgModule imports:
```js
import { MaterializeModule } from "angular2-materialize";

@NgModule({
  imports: [
    //...
    MaterializeModule,
  ],
  //...
})
```

If that's not the case, care to share your repo and we'll take a look?

**Comment by rvgarimrj** [comment]
I have made this but still does not work.
My repo is [here](https://github.com/rvgarimrj/jolet-angular)
Can you take a look and help me please ?
tks

**Comment by rubyboy** [comment]
@rvgarimrj from a brief look the repo you've linked is missing a few things:
1. jQuery is not installed
2. ```"../node_modules/materialize-css/dist/css/materialize.css"``` is not in the angular-cli.json

I suggest following the instructions here: https://github.com/InfomediaLtd/angular2-materialize#installing--configuring-angular2-materialize-in-projects-created-with-the-angular-cli

If it's still not working afterwards let me know and I'll pull the code and check. Thanks.

**Comment by rubyboy** [comment]
No response here, so I assume it's all good now? Closing.

**Comment by chiranjevik** [comment]
for me, I am getting the same error, Please help me to resolve the issue

compiler.js:215 Uncaught Error: Template parse errors:
Can't bind to 'materializeActions' since it isn't a known property of 'div'. ("
</div>

<div class="tap-target" data-activates="menu" materialize [ERROR ->][materializeActions]="tapTargetActions">
  <div class="tap-target-content">
    <h5>Title</h5>
