### ISSUE TITLE
Pull request #272 broke initial datepicker binding

### ISSUE THREAD

**Issue by ctytgat** [InfomediaLtd/angular2-materialize#292]
See https://github.com/InfomediaLtd/angular2-materialize/pull/272

This seems to have broken something in the datepicker... When the datepicker is bound with a FormControl, the initial value is not displayed anymore. Works fine up to version 15.0.2.

For example:

    <div class="input-field col s4">
        <input materialize="pickadate" [materializeParams]="[dateOptions]"
               id="activeFrom" type="text" formControlName="from"/>
        <label for="activeFrom">Actief van</label>
      </div>

and

    this.form = fb.group({
      'from': new FormControl('06/07/2017'),
    });

**Comment by rubyboy** [comment]
@criticalbh are you able to help with this? Thanks!

**Comment by rubyboy** [comment]
I've merged the PR from  @criticalbh  . @ctytgat are you able to confirm this is now fixed? Thanks.

**Comment by bop10** [comment]
@rubyboy Is this fixed on 15.0.4? Or this is going to be fixed in 15.0.5? Thanks

**Comment by rubyboy** [comment]
@bop10 thanks heaps for checking on this. It helps me identify that the original PR was merged but no version was released due to some build issues. I've now fixed that and a new version (15.1.1) is available with this fix.
