### ISSUE TITLE
Implementing chips with angular2-materialize

### ISSUE THREAD

**Issue by Neoflash1979** [InfomediaLtd/angular2-materialize#293]
I'm trying to implement the examples of materialize-css chips found [here][1], under the "Javascript Plugin Usage" heading, with angular2-materialze. I have followed the instructions for angular-cli installation found in the [docs][2]. I'm especially interested in the following implementation:

HTML

    <div class="chips chips-placeholder"></div>

JavaScript/JQuery

    $('.chips').material_chip();
    $('.chips-placeholder').material_chip({
        placeholder: 'Enter a tag',
        secondaryPlaceholder: '+Tag',
      });

How do I convert that to Angular code? What does my template and component need to have for this to work?

I have tried changing the HTML to both of these, 

    <div materialize class="chips chips-placeholder"></div>
    <div materialize="chips" class="chips chips-placeholder"></div>

but it didn't work and I get an error 'Couldn't find materialize function ''chips' on element or the global Materialize object.'

  [1]: http://materializecss.com/chips.html
  [2]: https://github.com/InfomediaLtd/angular2-materialize

**Comment by rubyboy** [comment]
See example code here: https://github.com/InfomediaLtd/angular2-materialize/blob/master/sample/src/app/components/chips.ts
This is the demo: http://angular2-materialize.surge.sh/#/Chips

In your code, you should use ```material_chip``` instead of ```chip```:
```html
<div class="chips" materialize="material_chip" [materializeParams]="[chipsPlaceholder]"></div>
```
