### ISSUE TITLE
Modal Popups not showing up

### ISSUE THREAD

**Issue by akashbiz** [InfomediaLtd/angular2-materialize#295]
Hello @rubyboy , I am trying to create a modal pop-ups but its not showing up on screen, when I inspect the html view from browser I see the modal has been created but due to some css issue its not showing on the screen. Also **do we have any feature to pass the result of one confirm pop-up(either clicked YES or NO) to the previous pop-up**?

**Comment by akashbiz** [comment]
Hey @rubyboy , can you tell me whether we have implemented the two way binding for modal or no? Can I pass some value from second level modal to first level modal before closing the second level modal. Please reply ASAP, its urgent.
It will be great if you could provide an example to open modals and pass data between the modals.

Thanks in advance

**Comment by akashbiz** [comment]
@allahbaksh @hendrikschneider @pawelhertman @counsellorben @feisel @criticalbh @strickos @rubyboy @CFisher11235

**Comment by rubyboy** [comment]
@akashbiz look at the sample code here: https://github.com/InfomediaLtd/angular2-materialize/blob/master/sample/src/app/components/dialogs.ts
You can use the button (click) to trigger your own action that keeps track of what's been clicked (YES/NO).
![image](https://user-images.githubusercontent.com/1908166/27479711-b4453996-581d-11e7-910d-770cb6f2b171.png)

**Comment by akashbiz** [comment]
Hey @rubyboy , Thanks for responding. Can you tell me, what if I have form on modal and I want to return the form-data back to component while closing this modal or on-click of submit button.

**Comment by akashbiz** [comment]
Also, I am not able to open a modal with code you just share. Its giving me an error saying **k.velocity is not a function**.  Please have a look at [256](https://github.com/InfomediaLtd/angular2-materialize/issues/256#issuecomment-310574684)

**Comment by rubyboy** [comment]
@akashbiz this error means you have not configured the project properly. Please follow the instructions here: https://github.com/InfomediaLtd/angular2-materialize#installing-and-configuring-angular2-materialize-with-webpack
You can also check out the example config here: https://github.com/InfomediaLtd/angular2-webpack-starter

**Comment by akashbiz** [comment]
Hello @rubyboy , One small query, how I can provide a complete different component as a modal? Here I mean I have **Component1** and it has button which should open modal which complete different component with different processing and different dependencies say **Component2**. So how I can I include that as a modal in **Component1**?

**Comment by akashbiz** [comment]
Hey @rubyboy, any update on this?

**Comment by rubyboy** [comment]
I'd pass an attribute to the component2 and then trigger an action in it when the button in component1 is clicked.
