### ISSUE TITLE
Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by Tbull187** [InfomediaLtd/angular2-materialize#299]
I'm receiving this error in my angular/webpack app. This issue started while migrating from webpack 1.x to 2.x. Materialize was working in my app with webpack 1.13.2.
![screen shot 2017-06-21 at 4 25 46 pm](https://user-images.githubusercontent.com/11916888/27411136-b1532212-56a0-11e7-80af-b81b1baea8d1.png)

I've gone over the angular2-materialize docs as well as rubyboy's angular2-webpack-starter fork with a fine toothed comb. The places where materialize code is imported in my app is almost identical to what's in the angular2-webpack-starter.
![screen shot 2017-06-21 at 4 27 16 pm](https://user-images.githubusercontent.com/11916888/27411288-906143c6-56a1-11e7-9e1d-7d5389f8e62e.png)

![screen shot 2017-06-21 at 4 28 39 pm](https://user-images.githubusercontent.com/11916888/27411291-97b6450e-56a1-11e7-90ad-f662ec4140cd.png)

I'm adding `import 'materialize-css';` and `import { MaterializeModule } from 'angular2-materialize';` in the top of my `app.module.ts` and I'm adding `materialize.min.css` in the head of my index.html. Let me know what else is needed from me to further troubleshoot this.

**Comment by rubyboy** [comment]
@Tbull187 maybe share a repo for someone to help out. Given that there's a working project example (angular2-webpack-starter) I'd say you can try starting with it (check that it works before adding any code) and then start modifying the code slowly to how it looks for you and see when it breaks.

**Comment by rubyboy** [comment]
No response. Closing.
