### ISSUE TITLE
Cannot use ngModel with material_select

### ISSUE THREAD

**Issue by jseriff** [InfomediaLtd/angular2-materialize#3]
When using material_select, ngModel no longer works for binding the value

**Comment by rubyboy** [comment]
@jseriff thanks for reporting this problem. Appreciate it.
This is fixed now. Could you please confirm?
I've also added usage of [(ngModel)] to the example app to illustrate how that would work.

**Comment by jseriff** [comment]
@rubyboy Seems to work now, thanks.  However, the typescript compiler is complaining because ngDoCheck and ngAfterViewInit should not be private (their corrosponding interfaces have them public).

**Comment by rubyboy** [comment]
Oh, thanks. I was under the impression omitting the modifier would default it to public.
Anyhow, I've fixed that as well. Thanks!
