### ISSUE TITLE
pickadate value not showing.

### ISSUE THREAD

**Issue by roxcity** [InfomediaLtd/angular2-materialize#304]
The date shows when selecting a new date but not showing during editing. But the value is still in there because when I submit the form the date has value. Its just not showing in the form's input. I am binding using formControlName of reactive form. By the way, the date value appears for a very short period of time and disappears again.

Thanks in advance.

**Comment by rubyboy** [comment]
+ @criticalbh

**Comment by criticalbh** [comment]
I would like to help, but it would be nice to see plunker?

**Comment by kjakub** [comment]
@roxcity 

this issue occurs when having reactive form and` <input type="date" formControlName="date"/> `just encountered with issue as you. I think related to the format of the date perhaps ? `<input type="text" formControlName="date"/>` works just fine
