### ISSUE TITLE
Materialize Select rendering issues with attr.disabled

### ISSUE THREAD

**Issue by Ramasubramanian** [InfomediaLtd/angular2-materialize#306]
**Issue**
When using attr.disabled is used on a materialize select component the disabled attribute is not applied for the first time or is applied only when the component is redrawn. 

**Steps to reproduce:**
1. Hit  http://angular2-materialize.surge.sh/#/Forms directly on the browser
2. Click on disable form button 
3. _Expected:_ The select drop down should be disabled immediately. 
_Actual:_ The Materialize Select (Choose your option) dropdown is not disabled immediately, when the component is clicked with the mouse it is disabled. 
 
However the same works perfectly when we access http://angular2-materialize.surge.sh first and go to the Forms page by clicking on the left side menu. Not sure what is the link with router changes and binding events to this component. Any help is highly appreciated.

**Comment by Ramasubramanian** [comment]
@rubyboy Any pointers on what could be the root cause will also be helpful for us to fix.

**Comment by Azunyth** [comment]
Just ran into the same issue, and I admit it's quite embarassing !

Here is my solution : 
(FYI I have a custom attribute directive to disable input, but it should work with `[attr.disabled]="myVar?true:null"`)

Create a variable that will handle your disable attribute with getter/setter
```typescript
actions: EventEmitter<string|MaterialActions> // do not forget to init !
private _myVar: boolean;

set myVar(value: boolean) {
    this._myVar = value;
    setTimeout(() => {
        this.actions.emit('material_select');
    }, 10);
}

get myVar() {
    return this._myVar;
}
```
And in your html : 
```html
<select materialize="material_select" [attr.disabled]="myVar?true:null">
    <option value="">Your option</option>
</select>
````

**Comment by rubyboy** [comment]
@Ramasubramanian @Azunyth 
Looking at our sample code, I now realize that ```attr``` not required. We could find directly to [disabled]. When you do that, all events are propagated properly and even the "select" elements are disabled on time.
Could you try replacing the disabling HTML code with ```[disabled]="isDisabled?true:null"``` and check if this works as expected?
If it also works well for you then I'll update the sample code and we can close this issue.

**Comment by Azunyth** [comment]
@rubyboy Ok, just made some test and it's quite weird...

First try : 
Change HTML to `[diabled]="myVar?true:null"`
Results : 
* Attribute `ng-reflect-is-disabled` is correctly set to `true` 
* Attribute `disabled` isn't present on select
* select **isn't** disabled

Second try : 
Change HTML to `[attr.disabled]="myVar?true:null"`
Results : 
* Attribute `disabled` is set to `true`
* select **is** disabled

Hope I didn't misunderstood your request

**Comment by rubyboy** [comment]
@Azunyth are you able to check if this is happening on the demo page as well? https://infomedialtd.github.io/angular2-materialize

**Comment by Azunyth** [comment]
@rubyboy Seems to work well on the demo 👍

**Comment by rubyboy** [comment]
Cool, thanks. Closing this issue then.
