### ISSUE TITLE
Is pushpin supported ?

### ISSUE THREAD

**Issue by ArThoX** [InfomediaLtd/angular2-materialize#307]
Hi

From materialize official page:
```
  $('.pushpin-demo-nav').each(function() {
    var $this = $(this);
    var $target = $('#' + $(this).attr('data-target'));
    $this.pushpin({
      top: $target.offset().top,
      bottom: $target.offset().top + $target.outerHeight() - $this.height()
    });
  });
```

Is such logic possible right now with the `[materialize]` and `[materializeParams]` inputs ?

More precisely, is that possible to pass  `bottom: $target.offset().top + $target.outerHeight() - $this.height()` in the materializeParams ? 

Regards

**Comment by ArThoX** [comment]
The obvious answer is, yes.
Using `#` to name `this` and `target` elements from the template and then pass the values to `materializeParams`.

**Comment by jaimeplier** [comment]
Hi, would you mind showing that last part? I didn't get the `Using # to name this`
