### ISSUE TITLE
pickadate min and max paremeter does not work with ng build

### ISSUE THREAD

**Issue by Pearseak** [InfomediaLtd/angular2-materialize#311]
pickadate min and max paremeter does not work with 'ng build' but work with 'ng serve'
(cli 1.2,angular 4.2.5)

update : it's work when build with --no-aot

**Comment by rubyboy** [comment]
@Pearseak are you able to check if this is still a problem with the latest build? Thanks.

**Comment by Pearseak** [comment]
It have been fix.
It now work on default build command.
built with cli 1.4.6 angular 4.4.5
