### ISSUE TITLE
Variable binding is not working after web service response

### ISSUE THREAD

**Issue by SPradnya** [InfomediaLtd/angular2-materialize#312]
I am using Materialize Modal. I have opened a modal and in same function of openModal I have called a web service. After web service response I have assigned that to a variable which is related to modal component. But that variable is not shown and data is not assigned to same when modal is opened. Following is my code content:

Component file for a modal: 

import { Component, EventEmitter, Output, NgZone } from "@angular/core";
import { MaterializeDirective, MaterializeAction } from "angular2-materialize";

import { exampleService } from "../services/manager.service";

@Component( {
    selector: 'device-manager-modal',
    templateUrl: './device-manager-modal.html'
})
export class DeviceManagerComponent {

    public devicesList: any;

    @Output() deviceManagerModalActions = new EventEmitter<string | MaterializeAction>();

    constructor( protected exServ: exampleService, public _ngZone: NgZone ) {
    }

    protected openModal() {
		this.deviceManagerModalActions.emit( { action: "modal", params: ['open'] });
		this.getDeviceDataList();        
    }

    protected closeModal() {
        this.deviceManagerModalActions.emit( { action: "modal", params: ['close'] });
    }
    getDeviceDataList() {
        this.exServ.getDeviceList()
            .then( deviceData => {				
                this.devicesList = deviceData;                                     
            }).catch( error => {
            });
    }
}

HTML file for a modal: 
<div id="device-manager-modal" class="modal bottom-sheet"
	materialize="modal" [materializeActions]="deviceManagerModalActions">

	<div class="modal-content">
		<div class="device-manager-popup">
			<div class="container row">
				<div class="devicesList">
					<h5>Your Devices List</h5>
					<ul class="col s12 m12 l12 xl12">
						<li *ngFor="let device of devicesList;">{{device?.DeviceID}}							
						</li> 
					</ul>
				</div>

			</div>
		</div>
	</div>
</div>

When I give a web service function call in a constructor, it works for me.

**Comment by rubyboy** [comment]
@SPradnya are you sure the server returns valid data and that your service is a part of the Zone?
Here's a working example that simulates server using timeout of 1 second. Try replacing your server call with a timeout. If that works for you (like the example below) then I'll look for the issue in the server call and if the return value is valid and part of the angular change detection.
```js
import {MaterializeDirective,MaterializeAction} from "angular2-materialize";
import {Component,EventEmitter} from "@angular/core"

@Component({
    selector: "dialogs",
    template: `
      <a class="waves-effect waves-light btn modal-trigger" (click)="openModal1()">Modal 1</a>

      <div id="modal1" class="modal bottom-sheet" materialize="modal" [materializeActions]="modalActions1">
        <div class="modal-content">
          <div class="device-manager-popup">
            <div class="container row">
              <div class="devicesList">
                <h5>Your Devices List</h5>
                <ul class="col s12 m12 l12 xl12">
                  <li *ngFor="let device of devicesList;">{{device?.DeviceID}}							
                  </li> 
                </ul>
              </div>

            </div>
          </div>
        </div>
      </div>
    `
})
export class Dialogs {
  modalActions1 = new EventEmitter<string|MaterializeAction>();

  devicesList = [];

  openModal1() {
    this.modalActions1.emit({action:"modal",params:['open']});
    window.setTimeout(()=>this.populateDeviceList(),1000);
  }

  populateDeviceList() {
    this.devicesList = [{DeviceID:"1"},{DeviceID:"2"},{DeviceID:"3"}]
  }
}
```

**Comment by rubyboy** [comment]
No response. Closing.
