### ISSUE TITLE
Modal ngfor

### ISSUE THREAD

**Issue by sggonzalezg** [InfomediaLtd/angular2-materialize#315]
How to get multiples modal?

html:
<a class="waves-effect waves-light btn modal-trigger" (click)="openModal(modal.id)">Modal</a>
 
<div *ngfor="let modal of modals" id="modal{{modal.id}}" class="modal bottom-sheet" materialize="modal" [materializeParams]="[{dismissible: false}]" [materializeActions]="modalActions">
  <div class="modal-content">
    <h4>Modal Header</h4>
    <p>A bunch of text</p>
  </div>
  <div class="modal-footer">
    <a class="waves-effect waves-green btn-flat" (click)="closeModal()">Close</a>
    <a class="modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
  </div>
</div>

Thanks

**Comment by rubyboy** [comment]
Is this what you're looking for?
```html
      <div *ngFor="let i of [1,2,3,4,5]">
        <a class="waves-effect waves-light btn modal-trigger" [attr.data-target]="'modal'+i">Open Modal {{i}}</a><br/><br/>
      </div>


      <div *ngFor="let i of [1,2,3,4,5]" [id]="'modal'+i" class="modal bottom-sheet" materialize="modal">
        <div class="modal-content">
          <h4>Modal Header {{i}}</h4>
          <p>A bunch of text</p>
        </div>
      </div>
```

**Comment by GlennVanSchil** [comment]
@rubyboy I've copy pasted this example and it indeed generates the correct amount of modals, but the attr.data-target does not trigger my modals. doesn't it require a ModalAction?
