### ISSUE TITLE
Materialize Dropdown Rendering issue / mousevent

### ISSUE THREAD

**Issue by gags88** [InfomediaLtd/angular2-materialize#318]
Issue
Materialize dropdown component not select on mousevent.

Steps to reproduce:

1. Hit http://angular2-materialize.surge.sh/#/Dropdown directly on the browser or from the left menu. 
2. Try to change dropdown value and you will not see update value in dropdown 'DROP ME' area.

Expected: The select drop down value should be updated immediately.

Any help is highly appreciated.
Same behavior is happening with select on my local app.

**Comment by rubyboy** [comment]
Can't reproduce
