### ISSUE TITLE
Error modal

### ISSUE THREAD

**Issue by sggonzalezg** [InfomediaLtd/angular2-materialize#319]
` <button data-target="modal{{employee.id}}" class="btn"> text </button>`

This is the error
Uncaught Error: Template parse errors:
Can't bind to 'target' since it isn't a known property of 'button'.

**Comment by sggonzalezg** [comment]
I found the solution

[attr.data-target]="'modal' + employee.id"

**Comment by hanighulam** [comment]
I was looking for a fix for this problem for sometime now! 
Thanks for sharing!
