### ISSUE TITLE
Angular CLI

### ISSUE THREAD

**Issue by JoshuaNovak919** [InfomediaLtd/angular2-materialize#32]
I'm a bit confused on how to set this up. I'm using Angular CLI, so I know it's a bit different, but nothing i've tried works. Anyone have get this to work with Angular CLI or have suggestions?

**Comment by rubyboy** [comment]
Maybe you can share your repository to check it out?
It's difficult without the context of how the project is set up, dependency-wise - e.g. transpiling with webpack or SystemJS, local or CDN dependencies, etc.

**Comment by JoshuaNovak919** [comment]
@rubyboy Here is a zip of the project. It looks like they are using SystemJS, but the configuration is quite odd. I couldn't figure it out based on your docs and the craziness the generator made.

https://drive.google.com/file/d/0B68aZqcn2sxXMUlpRmxMeGFXdEU/view?usp=sharing

Here is what I used to generate the project if it helps:
https://github.com/angular/angular-cli

**Comment by chinchalupa** [comment]
+1 Having the same issue with figuring out how to set up angular-cli with angular2-materialize.

I threw the System.config files where I thought they went, called "ng build" and "ng serve", but no materialize unfortunately.

I am no expert to angular2 or angular-cli, so any sort of hint / help would be very much appreciated.

The Github repo can be found [here](https://github.com/chinchalupa/angular-ng-test)

**Comment by rubyboy** [comment]
Can you try this?

index.html:
```html
<link type="text/css" rel="stylesheet" href="vendor/materialize-css/dist/css/materialize.css"/>
<script type="text/javascript" src="vendor/jquery/dist/jquery.min.js"></script>
<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
```

angular-cli-build.js :
```js
module.exports = function(defaults) {
  return new Angular2App(defaults, {
    vendorNpmFiles: [
      // ...
      "jquery/dist/*",
      "angular2-materialize/dist/*",
      "materialize-css/dist/**/*"
    ]
  });
};
```

system-config.ts :
```js
cliSystemConfigPackages["materialize"] = {
  "format": "global",
  "main": "dist/js/materialize",
  "defaultExtension": "js"
};
cliSystemConfigPackages["angular2-materialize"] = {
  "main": "dist/index",
  "defaultExtension": "js"
};
// ...
System.config({
  map: {
    // ...
    "materialize": "vendor/materialize-css",
    "angular2-materialize": "vendor/angular2-materialize",
    "jquery": "vendor/jquery"    
  },
  packages: cliSystemConfigPackages
});
```

If this works then the only open issue above is the jQuery&CSS dependencies that are specified in the HTML. Need to find a nice way to configure SystemJS to bring them in automatically. I tried using "meta" and "deps" in the config, but that didn't works. Not sure why, though as this is exactly how it's done with JSPM ([JSPM SystemJS override for MaterializeCSS](https://github.com/jspm/registry/blob/801e37953830bb38536dbca267174c4771fc0c8a/package-overrides/npm/materialize-css%400.97.5.json))

**Comment by chinchalupa** [comment]
I tried the above changes, but am still having problems getting the javascript for materialize to work properly. However, the links do work properly for the CSS, so all the CSS elements are loading in correctly.

The repo posted before has my updated code with the fixes you recommended.

Thanks for your help so far.

**Comment by JoshuaNovak919** [comment]
@rubyboy I tried the code you suggested and it worked great. Thanks!! I cannot attest to all the JS code working, but I added the accordion example and had no issues.

**Comment by rubyboy** [comment]
@JoshuaNovak919 glad it worked for you.

@chinchalupa is there a specific component that doesn't work or is it the loading of JS files the problem?
If your repo has it reproduced let me know and I'll check that out.

I'll add the config with CLI notes to the README later this week. Probably could use a demo repo for all variants of build systems. Help welcome :)

**Comment by chinchalupa** [comment]
Yes, the repo I posted before has the issue. To run it, just clone it, npm install, ng build, and ng serve. I am using a Windows machine.

I have been trying to get the list accordion to work that should display at the base route. I have not tested other components yet.

Thanks for taking the time to check out the repo.

**Comment by chinchalupa** [comment]
Fixed the issue!

It was on my end because I forgot to include the MaterializeDirective in the directives.

So I too can confirm that this configuration works for the accordion example (and most likely other examples).

@rubyboy thanks for your help!

**Comment by JoshuaNovak919** [comment]
@rubyboy I'll make a demo repo if you'd like. Still a bit new to Angular2 etc, so you'd wanna check it. If you want me to, just let me know what you want in the demo.

**Comment by rubyboy** [comment]
@JoshuaNovak919 thanks for offering to create a demo repo. That would be awesome!
I think it can have a small collection of two or three MaterializeCSS components (buttons, accordion, etc.). The main thing to demo is the configuration so the rest should be minimal.
If there's a popular starter repo for the CLI you could take that and fork it to be a starter+Materialize. I did a similar thing for Webpack with the [angular2-webpack-starter](https://github.com/InfomediaLtd/angular2-webpack-starter) (although I didn't really document it. I should!).
Let me know when you've got it and I'll review and add a link to it from this repo, for people to follow when they have a similar setup.
Again, thanks heaps for contributing.
