### ISSUE TITLE
Video on modal

### ISSUE THREAD

**Issue by sggonzalezg** [InfomediaLtd/angular2-materialize#321]
How to stop a youtube video on modal, when the modal is closed?

Thanks

**Comment by rubyboy** [comment]
The model is still there, even after you close it. It's just hidden (check the inspection tab using Chrome). I guess you could give your element an ID (or set it as an Angular variable) and then reach out to it and stop the video, just like you would with any other element that is on the screen, shown or not. Not sure it's related to MaterializeCSS, though....
