### ISSUE TITLE
initialize tabs inside a component

### ISSUE THREAD

**Issue by malorus** [InfomediaLtd/angular2-materialize#322]
Hi, initializing tabs inside a template is straight forward, using 
`<ul materialize="tabs" class="tabs tabs-fixed-width">`

But how to initialize tabs inside a ts-file (component)? I'm asking because I'm using tabs inside a modal. For this reason you have to initialize the tabs within the ready function of the modal to make it work properly. 

Right now I'm using a jquery-selector to make it work. But I'd like to use an angular approach. Here is the code I'm using:

```typescript 
       this.modalActions.emit({action:"modal",params:['open', {
            dismissible: false,
            opacity: .6,
            ready: (modal, trigger) => {
                $('.modal.login-register .tabs').tabs();
            }
        }]});
``` 

In the ready-function I need to initialize the tabs without using jquery. Any idea how to achieve that?

regards,
malorus

**Comment by yoannpicquenot** [comment]
Hey @malorus! How did you manage to have `.tabs()` in the loaded jQuery?

**Comment by malorus** [comment]
Hi @yoannpicquenot, in my app.module I import materialize-css, which includes all the materialize functions. Simply add `import 'materialize-css'`

**Comment by rubyboy** [comment]
@malorus is this issue still relevant?

**Comment by malorus** [comment]
@rubyboy In my use-case it seems there is no obvious way of avoiding the jquery-initialization. If you use tabs inside a modal, you will have to initialize it with jquery. The core-project of materializecss was written in jquery, it's a pitty. I hope in a future version the team will offer this framework in pure javascript. So that there is no need for jquery. 

As it seems, there is no solution to my question, I will close it now.

**Comment by antl3x** [comment]
Looks like that we can now use M.initialize(), but angular2-materialize seems to not support this.
