### ISSUE TITLE
Proper way to update chips data?

### ISSUE THREAD

**Issue by westwick** [InfomediaLtd/angular2-materialize#327]
I can't find this in the docs or examples or after playing around with it, but what's the best way to update chips data programmatically? In my case I want to have a button that loads previously saved values from localStorage, but it seems like the `[materializeParams]="[chipsInit]"` is only evaluated on load, as when I try to add data to `chipsInit.data` after the component is loaded, nothing happens. Any suggestions?

**Comment by rubyboy** [comment]
I'd use the MaterializeActions for that.
Here's an example, which I've also added to the sample code:
```html
<div class="chips" materialize="material_chip" [materializeParams]="[chipsInit]" [materializeActions]="chipsActions"></div>
<a class="waves-effect waves-light btn" (click)="updateChips()">Update Chips</a>
```
```js
  chipsActions = new EventEmitter<string|MaterializeAction>();
  updateChips() {
    const newChipsInit = {
      data: [{
        tag: 'Apple2',
      }, {
        tag: 'Google2',
      }],
    }
    this.chipsActions.emit({action:"material_chip",params:[newChipsInit]});
  }
```

**Comment by westwick** [comment]
thanks!!
