### ISSUE TITLE
TimePicker solution! (code in post)

### ISSUE THREAD

**Issue by WillNye** [InfomediaLtd/angular2-materialize#328]
I'm a huge fan of materialize and the directive you've created so I wanted to try and help out. I saw how you were setting pickadate so I added support for pickatime in a similar way.

`Prereq: npm install materialize-css@0.99.0 --save`

All there is to do is replace your current if (this.isTimePicker())

```
      if (this.isTimePicker()) {
        const nativeElement = this._el.nativeElement;
        const jqueryPickerElement = $(nativeElement);

        const timePicker = jqueryPickerElement[this._functionName](...this._params);
        const picker = timePicker.pickatime('picker');
        setTimeout(() => {
          if (this.ngModel) {
            picker.set('select', this.ngModel);
          } else {
            picker.set('select', jqueryPickerElement.val());
          }
          jqueryPickerElement.on('change', e => nativeElement.dispatchEvent(new Event('input')));
        });
      }
```

And voila. I've done some brief testing and the upgrade to materialize doesn't SEEM to have broken anything.

**Comment by rubyboy** [comment]
@WillNye thanks so much for your contribution!!
Would you like to post a PR so this code gets linked to your name? I'm more than happy to help you out if you've never done that before, and explain exactly what needs to be done and get this PR approved and the code merged into our library open source.
