### ISSUE TITLE
Character counter

### ISSUE THREAD

**Issue by JoostvdB94** [InfomediaLtd/angular2-materialize#33]
Is it possible to add the character counter to the list of possibilities? Adding `materialize` to the input-field does not add a counter when a `length="20"` is specified

**Comment by rubyboy** [comment]
Try adding ```materialize="characterCounter"```

**Comment by rubyboy** [comment]
@JoostvdB94 did the suggestion above work for you?

**Comment by JoostvdB94** [comment]
Looks like that worked, thanks! 
Perhaps you could add it to the demo?

**Comment by rubyboy** [comment]
Good idea. Want to send me a PR?

**Comment by cristianurbano** [comment]
The materialize="characterCounter" is not working for me, any idea?

**Comment by rubyboy** [comment]
I've added an example here: https://github.com/InfomediaLtd/angular2-materialize/blob/master/app/components/forms.ts#L59
```html
<textarea id="textarea1" class="materialize-textarea" materialize="characterCounter" length="120"></textarea>
```

**Comment by cristianurbano** [comment]
it works for me, thanks!
