### ISSUE TITLE
Carousel and parallax not working

### ISSUE THREAD

**Issue by Stefaneek** [InfomediaLtd/angular2-materialize#333]
Like in title I have problem with this two components, both of them not working correctly. I have everything done like it is shows in samples. With Carousel problem is that the photos move around slow and random, with parallax situtation looks diffrent becouse photos dont even show.
Its my component
```
import { Component, ElementRef, EventEmitter, ViewChild } from '@angular/core';
import { Router } from '@angular/router';
import { MaterializeDirective } from "angular2-materialize";

@Component({
  selector: "content",
  styles: [`
      .no-upper-case {
        text-transform: none
      }
    `],
  templateUrl: "content.component.html"
})

export class ContentComponent {
   @ViewChild('carousel') carouselElement; 
  actions = new EventEmitter<string>();

  imageURLs = [
    "https://image.shutterstock.com/display_pic_with_logo/1264645/364153082/stock-photo-asian-girl-in-sunflower-field-364153082.jpg",
    "https://image.shutterstock.com/display_pic_with_logo/1264645/298927574/stock-photo-a-young-traveler-girl-sit-on-the-wooden-bridge-in-halong-bay-and-enjoy-the-beauty-of-seascape-298927574.jpg",
    "https://image.shutterstock.com/display_pic_with_logo/1264645/298757792/stock-photo-a-young-traveler-girl-sit-on-the-top-of-mountain-in-halong-bay-and-enjoy-the-beauty-of-seascape-298757792.jpg",
    "https://image.shutterstock.com/display_pic_with_logo/2565601/411902890/stock-photo-ha-long-bay-scenic-view-hanoi-vietnam-411902890.jpg",
    "https://image.shutterstock.com/display_pic_with_logo/2565601/413207668/stock-photo-the-temple-of-literature-in-hanoi-vietnam-the-chinese-words-is-poem-of-thie-temple-and-templs-s-413207668.jpg"
  ];

  showInitialized = false;

  constructor() {
    // example of a hacky way to add an image to the carousel dynamically
    window.setTimeout(() => {
      this.imageURLs = [this.imageURLs[0], ...this.imageURLs]; // duplicate the first iamge
      this.carouselElement.nativeElement.classList.toggle("initialized")
      this.actions.emit("carousel");
    },1000);
  }
}
```

and my template 
`        <div #carousel class="carousel" [ngClass]="{ 'initialized': showInitialized }" materialize="carousel" [materializeActions]="actions">
          <a *ngFor="let url of imageURLs" class="carousel-item"><img [src]="url"></a>
        </div>`

**Comment by luketn** [comment]
Would you mind sharing your source for the parallax too? I've just implemented that on a site and there are a couple of little tricks to it I can share.

**Comment by luketn** [comment]
Re: the carousel, I've found that loading up images remotely like that was fairly inefficient, particularly if they are large. What size are the images? Perhaps try loading up the same size they will display from your site?

**Comment by Stefaneek** [comment]
Now its hard to say because I start working with materialize via angular cli not with webpack. Here everything works greate.

**Comment by rubyboy** [comment]
Closing. Please reopen if this issue is still reproducible with an example repo/plunker.
