### ISSUE TITLE
Breaks external JQuery Plugins

### ISSUE THREAD

**Issue by mohinithorat** [InfomediaLtd/angular2-materialize#334]
If I import material-css into my component, it breaks down other external jquery plugins used. Which is the best way to include css and support other jquery plugins too.

Thanks in advance.

**Comment by rubyboy** [comment]
I think it may be best to add this issue to the https://github.com/dogfalo/materialize repo as it seems related to MaterializeCSS and not the Angular bindings. If I'm wrong, please reopen this issue and we can explore together where it breaks.
