### ISSUE TITLE
Uncaught TypeError: Cannot read property 'M_Modal' of null

### ISSUE THREAD

**Issue by malorus** [InfomediaLtd/angular2-materialize#335]
Hi guys,
 the most recent angular2-materialize still depends on materialize-css@0.98.2
In the most recent version of materialize-css@0.100.1 there are some bugs fixed. Therefore I wanted to use it. But unfortunately there seems to be an incompatibility with angular2-materialize as I get the following error when opening a modal. The modal itself shows up without any problem. Everything seems to work. Does anyone know how to deal with this error?

```
zone.js?fad3:195 Uncaught TypeError: Cannot read property 'M_Modal' of null
    at HTMLDocument.handleTriggerClick (eval at <anonymous> (bundle.js:2558), <anonymous>:1998:63)
    at ZoneDelegate.invokeTask (eval at <anonymous> (bundle.js:4479), <anonymous>:424:31)
    at Zone.runTask (eval at <anonymous> (bundle.js:4479), <anonymous>:191:47)
    at ZoneTask.invokeTask [as invoke] (eval at <anonymous> (bundle.js:4479), <anonymous>:498:34)
    at invokeTask (eval at <anonymous> (bundle.js:4479), <anonymous>:1364:14)
    at HTMLDocument.globalZoneAwareCallback (eval at <anonymous> (bundle.js:4479), <anonymous>:1390:21)
```

**Comment by rubyboy** [comment]
@malorus try out the latest fix version 15.0.4 - it points to the latest materialize-css

**Comment by malorus** [comment]
@rubyboy thanks for the hint mate. I immediately tried it out. The warning concerning the version disappears now. However, the `Uncaught TypeError` I postet above persists. Do you experience the same error too when opening a modal? The error appears in the browser console after clicking a button to open the modal. Or am I the only one having this issue? In [version 0.100.0 of materialize-css](https://github.com/Dogfalo/materialize/releases/tag/v0.100.0) they rewrote the code for the modal. Therefore I thought that this might be the cause for this error.

**Comment by rubyboy** [comment]
@malorus you're right. I see the same error. Not sure where it's coming from - looks like it's outside of our code, but needs more investigation. Will try to find time to check soon.

**Comment by bop10** [comment]
Same error here

**Comment by rubyboy** [comment]
I noticed that in the new version, the modal requires the href="#modal1" on the button for it to be active. Are you able to check if you have this attribute, and does that help isolate the problem?

**Comment by bop10** [comment]
@rubyboy You are right, if you set the href="#modal_id" on the modal-trigger the problem dissapears!
Thanks!

**Comment by rubyboy** [comment]
Cool, closing then. Thanks for confirming.

**Comment by malorus** [comment]
@rubyboy I was unavailable the last days, so here is my belated response. Instead of using `<a>` elements as buttons I use the `<button>` element. So I have no href attribute. But I simply removed the `modal-trigger` class from the button element and everything worked fine for me. The error disappeared. I actually don't know what the class is for (I suppose a class for a jquery-function but I have not looked into it) but apparently it is not neccessary for opening the modal... at least in the newest release of materialize-css as the modal was completely rewritten. Thanks for your effort mate and best regards...

**Comment by rubyboy** [comment]
Referencing my previous comment (https://github.com/InfomediaLtd/angular2-materialize/issues/335#issuecomment-320423742), you don't have to put a "href", but then you need the "modal-trigger" class on the button.

**Comment by diandsonc** [comment]
For me, it worked removing `modal-trigger` class on the button.

**Comment by mjarpitanand** [comment]
Cool ! REMOVING MODAL-TRIGGER CLASS WORKED FOR ME !! Thnks mate!

**Comment by inunotaisho** [comment]
@rubyboy Removing `modal-trigger` class doesn't work in our case. We are trying to upgrade to Angular 6 and removing the `modal-trigger` causes our app to redirect to our home page
