### ISSUE TITLE
Multiple Select out of sync and closing prematurely

### ISSUE THREAD

**Issue by pain0486** [InfomediaLtd/angular2-materialize#337]
This is something that broke around 15.0.3. Last checked against 6.7.2 but tried 15.0.2 in the demo and the drop down at least stayed open.

The multi-select does not stay open when selecting items and when items are selected the UI show different items than what were selected. 
NgModel seems to always put in null for some reason. But this seems to be broke across versions

[Example on plunker](http://plnkr.co/edit/vAd72srNT6P8vXWik6Eg?p=preview)

**Comment by pain0486** [comment]
@rubyboy, I updated the plunker to delve further into the issue. It now uses the latest version 15.1.8.  It seams the ngModel is out of sync with the selected items when using optgroup and multiselect. Also using disabled default option always seems to show as selected (checked) or the first item

**Comment by westwick** [comment]
Just chiming in, I have this same problem. What confuses me is why it still works in the demo though?

**Comment by pain0486** [comment]
I have messed with this in other libs... I think this is an issue with MaterializeCSS.
