### ISSUE TITLE
The npm lite server change the address when I import angular2-materilize

### ISSUE THREAD

**Issue by clust3rsekt0r** [InfomediaLtd/angular2-materialize#34]
Hi the problem That i have everything install fine, but when I put this line in main.ts

import "angular2-materialize";

The lite server redirect me on this address all the time giving me an error 

 http://localhost:3000/angular2-materialize 404 (Not Found)

angular2-materialize:23 Error: Error: XHR error (404 Not Found) loading http://localhost:3000/angular2-materialize(…)

**Comment by rubyboy** [comment]
What module loader are you using?
Notice that your server needs to serve angular2-materialize from the root. That means you should have it in your node_modules and your modules loader should know about it and what file to load from it.

**Comment by rubyboy** [comment]
@clust3rsekt0r please let me know if this issue is still relevant. I'd like to close it if it's not. Thanks.

**Comment by rubyboy** [comment]
Closing.
