### ISSUE TITLE
Materialize.Toast.removeAll() is undefined

### ISSUE THREAD

**Issue by manuel-di-iorio** [InfomediaLtd/angular2-materialize#345]
I used `declare var Materialize:any;` at the start of the file, in order to use Materialize directly from the component.

`Materialize.toast()` method works well, but now I would like to dismiss any toast on the ngOnDestroy() event.
Is there a way to get access to the **Materialize.Toast** class ?

**Comment by rubyboy** [comment]
Sounds more like a MaterializeCSS question, and not Angular specific.
I think this is related and may provide a way to hide the toast in JS: https://github.com/Dogfalo/materialize/issues/1317

**Comment by manuel-di-iorio** [comment]
Thank you, will try by using the selector
