### ISSUE TITLE
SideNav strange behavior

### ISSUE THREAD

**Issue by moumoune** [InfomediaLtd/angular2-materialize#35]
Hi, 
I try to install the materialize mobile nabar.
I get a strange behavior: on large screen, menu is above the container of my page. On smaller screen, sideNav mobile menu disappears. Here my code for a web mobile app:

**home.component.html**
`<nav>
    <ul id="slide-out" class="side-nav fixed">
        <li class="orange center">
            <i class="material-icons md-48">face</i>
            Simon DIENY
        </li>
        <li><a href="#">Accueil</a></li>
        <li><a href="#">Mes favoris</a></li>
        <li><a href="#">Paramètres</a></li>
        <li><a href="#">Se déconnecter</a></li>
    </ul>
    <a materialize="sideNav" href="#" data-activates="slide-out" class="button-collapse show-on-large"><i class="mdi-navigation-menu"></i></a>
</nav>`

**home.component.ts**
`import { Component } from '@angular/core';
import { ROUTER_DIRECTIVES } from '@angular/router';
import {MaterializeDirective} from "angular2-materialize";

@Component({
    selector: 'swp-home',
    templateUrl: 'app/memberarea/home.component.html',
    directives: [MaterializeDirective],
    styles: [`
      li.active {
        background-color: #ee6e73
      }
    `]
})
export class SwpHomeComponent {

}`
 
I want to say that Angular2 directive are well integrated in the project.

Thank you for any help.

**Comment by rubyboy** [comment]
@moumoune thanks for reporting this issue.
Could you confirm if this is a MaterializeCSS issue or a problem with the directive?
You can do that by creating the same HTML with simple MaterializeCSS base HTML imports. Here's a small boilerplate that may help:
```html
<html>
  <head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
  </head>
  <body>
  </body>
</html>
```

**Comment by moumoune** [comment]
OK, sry for this useless issue. 
There is no problem in directives, it's just a different configuration for mobile app behavior.

Thx you for your time.

**Comment by rubyboy** [comment]
No worries. Thanks for checking and cleaning up! :)
