### ISSUE TITLE
autocomplete with remote data?

### ISSUE THREAD

**Issue by kootenpv** [InfomediaLtd/angular2-materialize#350]
Is this possible, it does not seem obvious from the raised issues / examples related to autocomplete.

**Comment by rubyboy** [comment]
Does this help? https://github.com/InfomediaLtd/angular2-materialize/issues/189#issuecomment-299208483

**Comment by rubyboy** [comment]
@kootenpv is this issue still relevant?

**Comment by kootenpv** [comment]
Thanks for your reply! Yea, I'm using it like that, thanks again!
