### ISSUE TITLE
Multi Autocomplete

### ISSUE THREAD

**Issue by SerdarN92** [InfomediaLtd/angular2-materialize#352]
Hi could you give me an example how Multi Autocomplete works on Angular2? I googled a lot and there are just examples for jquery.

**Comment by SerdarN92** [comment]
Tried this but its not working:

`
HTML:

<div class="col s12 m9">
     <div class="autocomplete">
          <div class="ac-input input-field">
                <input type="text" id="multipleInput" placeholder="Technologien, Skills, Fertigkeiten, ..."
                       materialize="autocomplete" [materializeParams]="materializeParams" />
          </div>
          <ul id="multipleDropdown" class="dropdown-content ac-dropdown"></ul>
          <input type="hidden" name="multipleHidden"/>
    </div>
</div>

Typescript:

this.materializeParams = [
      {
        'multiple' :
          {
            enable: true,
            maxSize: 5,
            onExist: function (item) {
              console.log(item.text + ' already added.');
            }
          },
        apprender :
          {
            el: '#multipleDropdown',
            tagTemplate: '<div class="chip" data-id="<%= item.id %>" ' +
            'data-text="<%= item.text %>"><%= item.text %>' +
            '<i class="material-icons close">close</i></div>'
          },
        dropdown : {
          el: '#multipleDropdown'
        },
        data :
          {
            'apple': null,
            'google': null,
          }
      }
];
`

**Comment by SerdarN92** [comment]
The solution i get from the code above is this: https://picload.org/view/rwowdowl/a.png.html

But i want it like this: https://picload.org/view/rwowdowi/b.png.html (this is with JQuery)

**Comment by rubyboy** [comment]
@SerdarN92 is this supported in MaterializeCSS? (http://materializecss.com/)
If you provide an example of vanilla MaterializeCSS that works, we could maybe check why it's not working in Angluar2.

**Comment by SerdarN92** [comment]
What is the difference of MaterializeCSS and vanilla MaterializeCSS?

**Comment by rubyboy** [comment]
None. I was just referring to a clean MaterializeCSS implementation without Angular. The angular2-materialize is only an Angular wrapper for MaterializeCSS. If something is not supported in MaterializeCSS then the right place to discuss or open an issue for it is the MaterializeCSS repo.
On the other hand, if it works with plain MaterializeCSS then we should also support it with Angular.

**Comment by SerdarN92** [comment]
Its not working with plain MaterializeCSS. Had to use another way. But thanks for trying to help.
