### ISSUE TITLE
Datepicker re-opening

### ISSUE THREAD

**Issue by jasperSpeicher** [InfomediaLtd/angular2-materialize#353]
In Chrome on mac: When I open the picker modal, then close it, then switch out of chrome, and then switch back, the datepicker has re-opened.

Happens in this sample app as well as in my own.
https://infomedialtd.github.io/angular2-materialize/#/DatePicker

**Comment by rubyboy** [comment]
Thanks for reporting this issue. Unfortunately, it's a bug in the original library, as suggested here: https://github.com/Dogfalo/materialize/issues/4700

Here's the original bug with a suggested workaround: https://github.com/amsul/pickadate.js/issues/160

I'll close the issue, for now, to keep it consistent with the MaterlializeCSS library.

**Comment by samber** [comment]
These few lines worked for me:

```
  private datePickerOptions = {
    onClose: () => {
      $(":focus").blur();
    },
  };
```

```
<input type="text"materialize="pickadate" [materializeParams]="[datePickerOptions]" />
```
