### ISSUE TITLE
Add installation guide for a project created with angular-cli

### ISSUE THREAD

**Issue by hendrik91** [InfomediaLtd/angular2-materialize#36]
Hi, I read your suggestions and saw your suggestions how setup projects, generated with angular-cli and would suggest some changes to the setup. 

In your solution you modify the configuration in system-config.ts directly but this part in the file is handled by angular-cli. Therefore we should configure it in the user configuration part in the top.

```
/** Map relative paths to URLs. */
const map: any = {
   "materialize": "vendor/materialize-css",
   "angular2-materialize": "vendor/angular2-materialize",
   "jquery": "vendor/jquery"
};

/** User packages configuration. */
const packages: any = {
  'materialize': {
    "format": "global",
    "main": "dist/js/materialize",
    "defaultExtension": "js"
  },
  'angular2-materialize': {
    "main": "dist/index",
    "defaultExtension": "js"
  }
};
```

**Comment by hendrik91** [comment]
I just discovered that there is a closed issue regarding this topic.

**Comment by rubyboy** [comment]
@hendrik91 thanks heaps for your contribution and the Pull Request. Much appreciated!
