### ISSUE TITLE
data-target='modal2' button not working in demo

### ISSUE THREAD

**Issue by Matthew-Myers-Aveniros** [InfomediaLtd/angular2-materialize#363]
`<button data-target="modal2" href='#modal2'class="btn" (click)='openModal2()'>Modal 2 (2)</button>`

button 2 (2) not opening modal 2 in the [Demo](https://infomedialtd.github.io/angular2-materialize/#/Dialogs)

Is this intended?

**Comment by rubyboy** [comment]
@Matthew-Myers-Aveniros thanks heaps for pointing this out. The demo was missing the ```modal-trigger``` class on the button (https://github.com/InfomediaLtd/angular2-materialize/issues/335#issuecomment-326726104). This is fixed now.
