### ISSUE TITLE
Using autocomplete with array of objects

### ISSUE THREAD

**Issue by renanmoraes** [InfomediaLtd/angular2-materialize#364]
I have the following array objects:

![captura de tela de 2017-09-01 08-31-39](https://user-images.githubusercontent.com/12611706/29968010-10a3ff7a-8ef0-11e7-8a41-7b360813625e.png)

I need when typing the name of the city it will offer me the ones that correspond with the typed one. With standard array ``{"Mines": null, "River": null}`` works perfectly.

I try to do it that way but it really does not work.
```
  private FindaAllCities() {
    this._user
      .getToken()
      .subscribe(res => {
        this._cities
          .findAll(res.data.token)
          .subscribe(response => {
            this.autocompleteInit = {
              'data': response.data,
              onAutocomplete: (val) => {
                console.log(val);
              },
            };
            console.log(this.autocompleteInit);
            this.cities = response.data;
          });
      });
  }
```

In reality, if I can get the id informed when it passes data `` {"Mines": "123456"}`` would serve me. When I do this, it returns me an error because I think I'm sending an image. I need to know when I clicked the _id of the clicked face.

**Comment by rubyboy** [comment]
@renanmoraes , unfortunately the MaterializeCSS framework only supports passing the text and getting it back in the ```onAutocomplete``` callback: http://materializecss.com/forms.html#autocomplete.
What I suggest you do is map your id (or original object) to the name, and get it using the value. Something like this:
```js
const nameToObject = {};
this.autocompleteInit = {
  'data': {},
  onAutocomplete: (val) => {
    console.log(nameToObject[val]);
  },
};
data.forEach(o => this.autocompleteInit.data[o.name]=null);
data.forEach(o => nameToObject[o.name]=o);
```
