### ISSUE TITLE
Tooltip is not showing up.

### ISSUE THREAD

**Issue by mbusbyHub** [InfomediaLtd/angular2-materialize#366]
I'm trying to get tooltips to show but I'm not having any luck. I even just tried copying and pasting from the sample page.

      <a materialize="tooltip" (click)="printSomething()" class="btn tooltipped" data-position="bottom" data-delay="10" data-tooltip="I am tooltip">Hover me!</a>

No tooltip shows up

**Comment by tramel-woodard** [comment]
@mbusbyHub I just imported your materialize anchor into a project of mine and rebuilt it. Works perfectly on my end. Are all of your other material directives working fine?

**Comment by mbusbyHub** [comment]
The other components I've been using are working. This tooltip just doesn't want to budge. I made a fresh angular app and tried it and it wont pop up:
https://github.com/mbusbyHub/tooltest

**Comment by tramel-woodard** [comment]
@mbusbyHub I noticed you're still referencing the **materialize.min.js** from your **src/index.html** file. If you need to reference this on your index.html for it to work, this usually means your angular2-materialize **MaterializeModule** is not properly configured.

I know you stated that the other components you're using are working. In Materialize, components can loosely reference 1) class styles (`<img class="img-responsive" />`), or 2) actual Materialize directives (`<a materialize="tooltip"></a>`). Are the other components you're using so far (that work) classes or actual directives?

If they're classes, then it's just a matter of property configuring Materialize for your angular-cli project. If you're already successfully using other Material directives (like materialize="tooltip") and this particular one is just not working, then we'll need to figure out something else.

In the meantime, maybe you can go down a checklist I wrote for angular-cli when it was called **angular2-webpack-starter**: #338 . If you've never used a Materialize directive (and just classes) so far, then I'd definitely be interested in seeing this work also, as most of my MEAN projects are using the older version.

Let us know how it goes.

**Comment by mbusbyHub** [comment]
Thank you! I'm new to angular, and web dev in general so I've been completely baffled by all the issues I'm having. I removed the min.js an min.css from index and the tooltip is now working, as well as a couple other strange issues being resolved .

**Comment by rubyboy** [comment]
@tramel-woodard thanks heaps for helping out here!

**Comment by tramel-woodard** [comment]
@rubyboy my pleasure, this module is a lifesaver for several of my projects. I hope more Angular devs start modularizing and encapsulating their Materialize code also.
