### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by kamalkech** [InfomediaLtd/angular2-materialize#373]
when can i found documentation of navbar ?!!

**Comment by rubyboy** [comment]
There's some sample code here: https://github.com/InfomediaLtd/angular2-materialize/blob/master/sample/src/app/components/side-nav.ts
Other then that, use the MaterliazeCSS documentation with the wrappers from angular2-materialize

**Comment by SujitSingh** [comment]
@kamalkech you can use something like below. This one has navigation both for desktop and mobile view.

    <nav>
      <div class="nav-wrapper">
        <a href="#!" class="brand-logo">Logo</a>
        <a materialize="sideNav" href="#" data-activates="slide-navigation" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <li routeLinkActive="active"><a routerLink="/">Home</a></li>
          <li routeLinkActive="active"><a routerLink="/other">Others</a></li>
        </ul>
        
        <ul id="slide-navigation" class="side-nav sidenav">
          <li routeLinkActive="active"><a routerLink="/">Home</a></li>
          <li routeLinkActive="active"><a routerLink="/other">Other</a></li>
        </ul>
      </div>
    </nav>

**Comment by kamalkech** [comment]
@rubyboy @SujitSingh, thank you and may be must to add that here https://infomedialtd.github.io/angular2-materialize
