### ISSUE TITLE
Importing materialize.css breaks all my styles

### ISSUE THREAD

**Issue by carol-braileanu** [InfomediaLtd/angular2-materialize#375]
I only use  the Autocomplete feature in Materialize in my application. I installed angular2-materialize and I added materialize-css references for the js and css files. I noticed however that all the styles in my app have been overwritten by the materialize-css styles. Is there a way to prevent this from happening and only apply materialize styles to the controls I need?

**Comment by rubyboy** [comment]
Unfortunately, the MaterializeCSS itself is global, thus applying all styles globally.
But, MaterializeCSS provides a way to override its own SCSS. You can find a small example here: https://github.com/InfomediaLtd/angular2-materialize/blob/master/sample/src/styles.scss
