### ISSUE TITLE
Can't get Materialize to work in Angular 2 with Web Pack

### ISSUE THREAD

**Issue by krsrk** [InfomediaLtd/angular2-materialize#39]
I have a problem at time i install materialize with web pack  it throws this exception:
ORIGINAL EXCEPTION: Error: Couldn't find materialize function ''tabs' on element or the global Materialize object.

Its in all the functions of materialize, i made the installation by webpack. and this is my webpack configuration:

var sliceArgs = Function.prototype.call.bind(Array.prototype.slice);
var toString  = Function.prototype.call.bind(Object.prototype.toString);
var path = require('path');
var webpack = require('webpack');
// Webpack Plugins
var CommonsChunkPlugin = webpack.optimize.CommonsChunkPlugin;

module.exports = {
  devtool: 'source-map',
  // devtool: 'eval',

  //
  entry: {
    'vendor': [
      // Polyfills
      'core-js/es6',
      'core-js/es7/reflect',
      'zone.js/dist/zone',
      'zone.js/dist/long-stack-trace-zone',
      // Angular2
      '@angular/common',
      '@angular/platform-browser',
      '@angular/platform-browser-dynamic',
      '@angular/core',
      '@angular/router',
      '@angular/router-deprecated',
      '@angular/http',
      // RxJS
      'rxjs',
      // Other
      'angular2-jwt'
    ],
    'app': [
      './src/index'
    ]
  },

  // Config for our build files
  output: {
    path: root('build'),
    filename: '[name].js',
    // filename: '[name].[hash].js',
    sourceMapFilename: '[name].js.map',
    chunkFilename: '[id].chunk.js'
    // publicPath: 'http://mycdn.com/'
  },

  resolve: {
    root: __dirname,
    alias: {
      materializecss: 'node_modules/materialize-css/dist/css/materialize.css',
      materialize: 'node_modules/materialize-css/dist/js/materialize.js'
    },
    extensions: [
      '',
      '.ts',
      '.js',
      '.json',
      '.css',
      '.html'
    ]
  },

  module: {
    preLoaders: [ { test: /\.ts$/, loader: 'tslint-loader' } ],
    loaders: [
      // Support for .ts files.
      {
        test: /\.ts$/,
        loader: 'ts-loader',
        query: {
          'ignoreDiagnostics': [
            2403, // 2403 -> Subsequent variable declarations
            2300, // 2300 Duplicate identifier
            2304, // 2304 Cannot find name
            2374, // 2374 -> Duplicate number index signature
            2375  // 2375 -> Duplicate string index signature
          ]
        },
        exclude: [ /\.spec\.ts$/, /\.e2e\.ts$/, /node_modules/ ]
      },

      // Support for *.json files.
      { test: /\.json$/,  loader: 'json-loader' },

      // Support for CSS as raw text
      { test: /\.css$/,   loader: 'raw-loader' },

      // support for .html as raw text
      { test: /\.html$/,  loader: 'raw-loader' },
      
      //Materialize CSS
      {
        test: /materialize-css\/dist\/js\/materialize\.js/,
        loader: 'imports?materializecss'
      },
      { test: /materialize\.css$/,   loader: 'style-loader!css-loader' },
      { test: /.(png|woff(2)?|eot|ttf|svg)(\?[a-z0-9=\.]+)?$/, loader: 'url-loader?limit=100000' },
    ],
    noParse: [
     /zone\.js\/dist\/.+/,
     /reflect-metadata/,
     /es(6|7)-.+/,
     /.zone-microtask/, 
     /.long-stack-trace-zone/
    ]
  },

  plugins: [
    new CommonsChunkPlugin({ name: 'vendor', filename: 'vendor.js', minChunks: Infinity }),
    new CommonsChunkPlugin({ name: 'common', filename: 'common.js', minChunks: 2, chunks: ['app', 'vendor'] }),
    new webpack.ProvidePlugin({
          $: "jquery",
          jQuery: "jquery",
          "window.jQuery": "jquery",
          "root.jQuery": "jquery",
          Hammer: "hammerjs/hammer"
      })
  ],
  
  // Other module loader config
  tslint: {
    emitErrors: false,
    failOnHint: false
  },
  
  // our Development Server configs
  // our Webpack Development Server config
  devServer: {
    historyApiFallback: true,
    publicPath: '/build'
  }
};

function getBanner() {
  return 'This is a sample that shows how to add authentication to an Angular 2 (ng2) app by @auth0';
}

function root(args) {
  args = sliceArgs(arguments, 0);
  return path.join.apply(path, [__dirname].concat(args));
}
function rootNode(args) {
  args = sliceArgs(arguments, 0);
  return root.apply(path, ['node_modules'].concat(args));
}

Can anyone help me please ???

**Comment by rubyboy** [comment]
Check out the webpack starter repo which is configured properly and works. Maybe it will help you configure it for your project: https://github.com/InfomediaLtd/angular2-webpack-starter

If that doesn't help you, could you share your working repo and I can try to add angular2-materialize to it ?

**Comment by krsrk** [comment]
I dont know if this affect to the configuration of the JWT project; i took it from another repo and it has this configuration mention in the post. I will upload the project to GITHUB so you can help me please.

**Comment by krsrk** [comment]
Sorry for the late here is my repo, i try to configure webpack with your configuration with no success :( but here is my repo https://github.com/krsrk/angular2-auth.
Greetings

**Comment by rubyboy** [comment]
@krsrk I cloned the repository, "npm install"-ed, then "npm start"-ed and it seems to work well. I can see tabs transitioning as expected and no error like the one you mentioned above (Couldn't find materialize function ''tabs' on element or the global).
I also added a few buttons to the login screen to check that the button highlight effect works as expected. It does.
See below a screengrab of how it looks like for me.

Could you clean up your node_modules folder, install and check again?

![test1](https://cloud.githubusercontent.com/assets/1908166/15707166/ef36c866-27ff-11e6-89b3-4564a362eff4.gif)
![test2](https://cloud.githubusercontent.com/assets/1908166/15707168/ef3a83c0-27ff-11e6-9aca-90225f85512c.gif)

**Comment by krsrk** [comment]
i rebuild de node modules and work fine, but i clone the project in my Mac, i was developed in a PC with WIN 7 let me test in this machine to see if there's no problem, Thank you.

**Comment by rubyboy** [comment]
@krsrk how did you go? Can I close this issue? Thanks.

**Comment by krsrk** [comment]
Sobre for answer late yes you can close the issue for me works fine

**Comment by rafaelzuckerberg** [comment]
Well, in may case, close Atom IDE and restart the server (ng serve) again and working to me, I do not know why....
