### ISSUE TITLE
Datepicker issue

### ISSUE THREAD

**Issue by imaress** [InfomediaLtd/angular2-materialize#4]
First all, thanks for sharing!! I try with your directive but when put a datepicker i have some issues, in your example page in the form section the date picker don't show. In my project when put a datepicker or a reveal card (activator class) the icons doesn't show only text on all my project, but i think maybe is because i try to load components dynamically and routing in the same way. But the issue with datepicker is different from my configurations. Thanks for all!!!

**Comment by rubyboy** [comment]
Thanks for the feedback. Much appreciated.
Yeah, datepicker is not supported yet. See https://github.com/InfomediaLtd/angular2-materialize/issues/1 . I hope to look into it sometime soon as we'll need it in our projects, but it's a bit complex so need to spend some time figuring out the right approach here.
Did you have another issue that you want to share code/screenshot, which I can help with? We are using cards as well and so far it work well, but maybe there are some corner cases. Happy to look into it if you provide the exact issue with code sample that doesn't work as expected.

**Comment by imaress** [comment]
Hi!,
My issue with the icons font is only when storage locally the Material+Icons.css file from google and using the font include in materialize, but i found [this](https://forums.meteor.com/t/solved-materialize-materialize-icons-not-working/6753/2) and i solved the problem. Thanks for all and i hope you can find datepicker's problem, thanks for all!!.

**Comment by rubyboy** [comment]
Thanks for the tip and feedback!
We will definitely need a datepicker in the next few months so I'm sure that something that will be fixed soon-ish.
I'll close this issue now, if you don't mind. Please follow the other one for progress or adding any related information in regards to the datepicker.

**Comment by rubyboy** [comment]
@imaress notice that @criticalbh has just added support for datepicker: https://github.com/InfomediaLtd/angular2-materialize/pull/8
If you get the latest version it should work. See example here: http://angular2-materialize.surge.sh/#/datepicker
