### ISSUE TITLE
Angular 2 Web pack starter production build not working

### ISSUE THREAD

**Issue by Arkanayan** [InfomediaLtd/angular2-materialize#40]
Hi,
I am using your angular2 webpack starter pack. Everything runs fine on dev build. But on production build everything that requires materialize javascript  not working. I am getting this error 

browser_adapter.js:77 TypeError: d.each is not a function
    at e (materialize.js:236)
    at HTMLDivElement.n (materialize.js:236)
    at HTMLDivElement.<anonymous> (materialize.js:237)
    at Function.v.extend.each (jquery.js:365)
    at x [as velocity] (materialize.js:237)
    at HTMLAnchorElement.<anonymous> (materialize.js:1306)
    at HTMLUListElement.v.event.dispatch (jquery.js:4737)
    at HTMLUListElement.g.handle (jquery.js:4549)
    at ZoneDelegate.invokeTask (zone.js:356)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (ng_zone_impl.js:36)

I think this is because of UglifyJsPlugin on production build. This is my UglifyJsPlugin config

 new UglifyJsPlugin({
      // beautify: true, //debug
      mangle: false, //debug
      dead_code: false, //debug
      unused: false, //debug
      deadCode: false, //debug
      // compress: {
      //   screw_ie8: true,
      //   keep_fnames: true,
      //   drop_debugger: false,
      //   dead_code: false,
      //   unused: false
      // }, // debug
      // comments: true, //debug

      beautify: false, //prod

  /*      mangle: {
        screw_ie8 : true,
        keep_fnames: true
      }, //prod*/

      compress: {
        screw_ie8: true
      }, //prod

      exclude: ['/materialize.js/g'],
      comments: false //prod
    }),

**Comment by rubyboy** [comment]
Few questions to direct this issue to the right place:
1. Does it work if you don't minify the code?
2. Try to mangling the code. Does that work?
3. Do you get the same problem when you run the non-webpack minified version? (plain scripts imported in the HTML)

**Comment by Arkanayan** [comment]
1. Yes, It works when I don't minify.
2. Yes, without any mangling, the code works fine.
3. Yes, when I was testing without webpack, it worked.

I think if I exclude materialize.js from UglifyJsPlugin, it will work. But I think I wrote the regex wrong. 

Also I noticed the files becomes significantly bigger on including MaterializeJs ( >1MB). 

Is there a way to load the js files from cdn ? I tried with externals plugin. But it didn't work.

**Comment by rubyboy** [comment]
I tried minifiying the example app and it worked well when using JSPM. Here's the minified JS: http://angular2-materialize.surge.sh/index.js (the example app is here: http://angular2-materialize.surge.sh)

You can load the MaterializeCSS scripts directive like this:
```html
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
```

Which version of Angular2 are you using? During beta there were problems with minifying it. The reason I'm asking is that the problem you're getting it actually in the Angular code. In browser_adapter.js .

**Comment by rubyboy** [comment]
Is there a way to alias something to an empty return value in Webpack?
The import in angular2-materialize is global: https://github.com/InfomediaLtd/angular2-materialize/blob/master/src/index.ts#L1
So it doesn't expect anything to come back. Only expects "materialize" to point at something.

I can also create a different entry point for angular2-materialize that doesn't include the import. This way it stands on its own and you can import materialize separately (before angular2-materialize, though). Of that helps..

**Comment by Arkanayan** [comment]
If I point 'materialize' to global 'Materialize and disable alias 'materialize' to local script,

```
 externals : {
    "materialize": "Materialize"
  },

```
and
```
    alias: {
      materializecss: 'materialize-css/dist/css/materialize.css',
      // materialize: 'materialize-css/dist/js/materialize.js',
  }
```
I am getting this error 
`ORIGINAL EXCEPTION: Error: Couldn't find materialize function ''tabs' on element or the global Materialize object.`

**Comment by rubyboy** [comment]
It means that Materialize doesn't exist on the window. It hasn't been loaded.

**Comment by rubyboy** [comment]
@Arkanayan I've just read this on the Uglify documentation: "by default, UglifyJS will remove code that is obviously unreachable". Maybe it removed Materialize, thinking it's not used?

Can you try running your same setup with the following Uglify flag? ```--no-dead-code```
It should disable the dead code elimination and then we'll know if this is what's causing Materialize to be removed from your prod build.

**Comment by Arkanayan** [comment]
@rubyboy You are right. With dead code not removed it works.

This is config on webpack

``` 
  new UglifyJsPlugin({
      // beautify: true, //debug
      // mangle: false, //debug 
      // unused: false, //debug
      // deadCode: false, //debug
      // compress: {
      //   screw_ie8: true,
      //   keep_fnames: true,
      //   drop_debugger: false,
      //   dead_code: false,
      //   unused: false
      // }, // debug
      // comments: true, //debug

      beautify: false, //prod
      dead_code: false, //debug  

// If you want to remove dead code, uncomment this mangle block
/*      mangle: {
        except: ['Materialize']
      },
*/

/*
      mangle: {
        screw_ie8 : true,
        keep_fnames: true
      }, //prod
*/

      compress: {
        screw_ie8: true
      }, //prod

      exclude: ['/materialize.js/g'],
      comments: false //prod
    }),
```

**Comment by Arkanayan** [comment]
You can close this issue, if you want.

**Comment by rubyboy** [comment]
Awesome. Thanks for checking and getting back to me. Much appreciated!
