### ISSUE TITLE
Materialize and Webpack issue

### ISSUE THREAD

**Issue by vouill** [InfomediaLtd/angular2-materialize#42]
Hey,

I was using this starter https://github.com/AngularClass/angular2-webpack-starter and the default prod config.

I encountered a little issue while using materialize and webpack. The build both in dev and prod mode were OK, however when i tried to reach my website i had this error : 
`materialize.js:238 Uncaught TypeError: Cannot convert undefined or null to object`

I then unminified it and it worked.

Hope it helps !
Great job on the component anyway !

**Comment by rubyboy** [comment]
@vouill take a look here and see how it's configured: https://github.com/InfomediaLtd/angular2-webpack-starter
This fork is using angular2-materialize on the same starter project so hopefully you can copy over the config and it would work.

**Comment by rubyboy** [comment]
Just noticed that you were referring to the minified version. It sounds similar to this issue: https://github.com/InfomediaLtd/angular2-materialize/issues/40
I have a feeling that materialize.js is not intended to be re-minified. Can you use the original minified file and not run minification again?

**Comment by rubyboy** [comment]
Check out this comment to verify if that helps you as well: https://github.com/InfomediaLtd/angular2-materialize/issues/40#issuecomment-222342077

**Comment by vouill** [comment]
Awesome thanks for the comment link :)
