### ISSUE TITLE
Using default html elements

### ISSUE THREAD

**Issue by YuryKorovko** [InfomediaLtd/angular2-materialize#436]
Hi! Please help. My angular app always uses materialize css.
What if I want to use default non-stylized select ? 
If i just put select without materialize="material_select" attribute then it is not displayed. 
Please help!

**Comment by gabrielrojasp** [comment]
@YuryKorovko just add class="browser-default" in select html tag

**Comment by YuryKorovko** [comment]
@kinoxhio Thank you so much!
