### ISSUE TITLE
Materialize CSS not being applied for starter pack (materialize fork)

### ISSUE THREAD

**Issue by pchristou** [InfomediaLtd/angular2-materialize#44]
Hi,

I'm on Windows 7 and I've triggered the following commands.

$ git clone --depth 1 https://github.com/InfomediaLtd/angular2-webpack-starter.git
$ cd angular2-webpack-starter/  
$ npm install typings webpack-dev-server rimraf webpack -g
$ npm install
$ npm start

I then added `import {MaterializeDirective} from "angular2-materialize";` to home.component.ts
and `<a materialize="tooltip" class="btn tooltipped" data-position="bottom" data-delay="50" data-tooltip="I am tooltip">Hover me!</a>` to home.html to test the Materialize element comes through as expect. Unfortunately, even though the hover works, no styling is applied.

I found this link which describes the issue https://github.com/InfomediaLtd/angular2-materialize/issues/2 but I'm using the https://github.com/InfomediaLtd/angular2-webpack-starter and the changes to webpack config have already been made. Any help on how I can get styling to come through as part of the configuration would be greatly appreciated.

**Comment by rubyboy** [comment]
I think you may have forgotten to add MaterializeDirective to your directives list in home.component.ts .
Remember that all angular2 directives that you use in a component have to be in that list.

**Comment by pchristou** [comment]
I checked and the directive is there. Like the previous issue linked to, if I directly link to materialize.css from index.html, the styling comes through without issue.

Looking at the output of webpack when running "npm start", I see materialize.js but no mention of materialize.css. 

At this rate, I may have to stick with loading the css file manually :(

**Comment by rubyboy** [comment]
I've just checked in the changes you mentioned back into the repository. When I clone it and npm install and start I see it working properly. https://github.com/InfomediaLtd/angular2-webpack-starter

Here's the output of my webpack start where it loads materialize.css:
```
[733] ./~/materialize-css/dist/css/materialize.css 897 bytes {3} [built]
       [0] 0ms -> [499] 3213ms -> [533] 1979ms -> [509] 1487ms -> factory:374ms building:3ms = 7056ms
```

The following bit in webpack.common.js is the one responsible for configuring materialize.css:
```
    alias: {
      materializecss: 'materialize-css/dist/css/materialize.css',
      materialize: 'materialize-css/dist/js/materialize.js',
```

Can you try a different OS to confirm it's not a problem with win? I don't think there should be a difference, but who knows...

**Comment by pchristou** [comment]
So.. I tried the procedure on my work Mac and received a normalize.css error. Has to be something funky going on with the config on the laptop so I then tried the produce on my personal Mac and lo and behold, everything worked as expected. Similar to yours, here's the webpack output for the build that worked.

  [508] ./~/css-loader!./~/materialize-css/dist/css/materialize.css 158 kB {3} [built]

Weirdly, when trying this on Windows, I receive the materialize.js output but not the materialize.css output. Can you think of any variation I can put in for the aliases on the Windows machine (maybe I can try an absolute path?)

**Comment by pchristou** [comment]
No luck. I've noticed the fonts aren't loaded on Windows either. It seems like anything prefixed with style-loader or css-loader isn't output by Webpack on Windows.

I'll continue experimenting..

**Comment by rubyboy** [comment]
@pchristou any luck? Unfortunately I don't even have a windows machine to try it on :)

**Comment by pchristou** [comment]
Unfortunately not, I've had to include the css file directly on the index page. Thanks for following up @rubyboy!
