### ISSUE TITLE
How can i make a navbar menu ? 

### ISSUE THREAD

**Issue by cyberbobjr** [InfomediaLtd/angular2-materialize#45]
Hi,
i've tried to use these syntax :
```
<a href="#" data-activates="mobile-demo" materialize="sideNav" class="button-collapse">
        <i class="material-icons">menu</i>
</a>
```

But when i click on the menu, angular2 restart.
In the materializecss doc, the authors write this :
$(".button-collapse").sideNav();

But how can i do this with Angular ?

Thanks for your help,
best regards

**Comment by rubyboy** [comment]
Have a look at the these two code samples in the example app, one with fake routing (using sidenav) and another that sets the href to a real route. It depends on your usage. Notice that href "#" will refresh the window. You can cancel that ("event.preventDefault") or use one of these techniques:
https://github.com/InfomediaLtd/angular2-materialize/blob/master/app/components/side-nav.ts
https://github.com/InfomediaLtd/angular2-materialize/blob/master/app/components/tabs-routing.ts

\T

**Comment by cyberbobjr** [comment]
Thanks for your answer, i'll look for that :)

**Comment by rubyboy** [comment]
Can I close this issue?

**Comment by cyberbobjr** [comment]
Hi, sorry for the delay 
not yet tested :(

**Comment by cyberbobjr** [comment]
Hi, it's works ! i made different class for visibility, like this :
```
<div class="navbar-fixed hide-on-small-only">
  <nav>
    <div class="nav-wrapper teal darken-3">
      <ul class="right">
        <li><a [routerLink]="['/yyyy']">yyyy</a></li>
        <li><a hreF="#" (click)="xxxx($event)">xxxx</a></li>
        <li><a href="#" (click)="logout($event)">Logout</a></li>
      </ul>
    </div>
  </nav>
</div>

<nav class="hide-on-med-and-up teal darken-3">
  <div class="container">
    <ul id="slide-out" class="side-nav fixed">
      <li class="logo" style="text-align: center;">
        <img src="image.png" style="padding-top: 10px;">
      </li>
      <li class="no-padding">
        <ul>
        <li><a [routerLink]="['/yyyy']">yyyy</a></li>
        <li><a hreF="#" (click)="xxxx($event)">xxxx</a></li>
        <li><a href="#" (click)="logout($event)">Logout</a></li>
        </ul>
      </li>
    </ul>
    <a href="#" materialize="sideNav" [materializeParams]="[{edge:'left'}]" data-activates="slide-out"
       class="button-collapse">
      <i class="fa fa-bars fa-2x"></i>
    </a>
  </div>
</nav>
```

**Comment by rubyboy** [comment]
Cool. Thanks for testing it and providing your solution.
