### ISSUE TITLE
Datepicker handlers

### ISSUE THREAD

**Issue by pchristou** [InfomediaLtd/angular2-materialize#47]
Hi,

In short, I have 2 questions.
1. How can I close the datepicker on selection?
2. Why does [this datepicker implementation](http://angular2-materialize.surge.sh/#/datepicker) not suffer from [this bug ](https://github.com/amsul/pickadate.js/issues/160) whereas [Materialize's](http://materializecss.com/forms.html) one (and mine) does?

Longer explanation:

I understand Materialize uses pickadate.js under the covers. Having checked its API I see there are a range of event callbacks available:
![callback_handlers](https://cloud.githubusercontent.com/assets/18244820/16042443/95ba005e-3232-11e6-868d-f681bc540d40.PNG)

How can I apply these to the datepicker in Angular 2? I got as far as grabbing the datepicker through 

```
        var $input =$(this.el.nativeElement); // We grab a reference to the datepicker here
        var picker = $input.pickadate('picker');
```

but there's not a great deal I can do from there. I actually want to close the datepicker on selection and found that an attribute 'closeOnSelect' exists: http://amsul.ca/pickadate.js/date/

Unfortunately, placing this in [materializeParams] doesn't seem to work. 

One more thing, I noticed the Datepicker sample here http://angular2-materialize.surge.sh/#/datepicker
does not suffer from [this bug ](https://github.com/amsul/pickadate.js/issues/160) whereas [Materializes](http://materializecss.com/forms.html) (plus mine) does... can you think of any reasons why? I thought the implementation between both would be near identical...

As always, thank you!
Pieris

**Comment by pchristou** [comment]
Got this sorted.

For the date handling part, I used:
```

        var $input = $(this.el.nativeElement); // We grab a reference to the datepicker here
        var picker = $input.pickadate('picker');
        picker.on('close', function() {
          //...
        })
```

**Comment by marciomsm** [comment]
Are we able to use events callback already? Do anyone knows how to do it in Angular 2?

**Comment by rubyboy** [comment]
See here: https://github.com/InfomediaLtd/angular2-materialize/issues/283

```html
<input materialize="pickadate" [materializeActions]="actions" type="text" />
```
```js
this.actions.emit({action:"pickadate",params:["close"]});
```
