### ISSUE TITLE
Tooltip Issue

### ISSUE THREAD

**Issue by vouill** [InfomediaLtd/angular2-materialize#51]
Hey !

I am having a pretty weird issue with tooltips.

When i hover an <a> link, the tooltip appear and disappear as expected.
However when i click on it , the tooltip stays, by looking at the html it looks like a tooltip with a brand new id got created and stays displayed. 
click again keeps on creating new displayed tool tip.

Any idea where this could come from ?

piece of code in question : 
```
<a  (click)="selectEnv(env)"  materialize="tooltip" data-position="top" data-delay="10" data-tooltip="Select Environment" ><i class=" fa fa-square fa-fw "  ></i></a>
```
Update:

This comes from a (click) event on the tooltip source. Removing the (click) event makes the bug disapear.

**Comment by vouill** [comment]
Update:

This comes from a (click) event on the tooltip source. Removing the (click) event makes the bug disapear.

**Comment by Chipintoza** [comment]
Hello,
I have same problem... :(

**Comment by rubyboy** [comment]
@vouill @Chipintoza is it happening on a specific browser?

Do you see the same behaviour here: http://angular2-materialize.surge.sh/#/dialogs ?

Here's the code I tried to reproduced, but haven't been able to see the problem, yet: https://github.com/InfomediaLtd/angular2-materialize/blob/master/app/components/dialogs.ts#L24
```html
<a materialize="tooltip" (click)="printSomething()" class="btn tooltipped" data-position="bottom" data-delay="10" data-tooltip="I am tooltip">Hover me!</a>
```

**Comment by vouill** [comment]
Im on the latest v of chrome.
The weirdest is that it was working in my app up until recently. I havent updated anything.
The (click) event simply fires a store.dispatch. 
When you click on it a new tooltip is created with a new id, and the previous one just stays. 
Ill keep on investigating

**Comment by vouill** [comment]
Ok so quick update , i have narrowed the issue to ngrx Effects.
 
Basically my (click) event fire a store dispatch.
Any random dispatch and the tooltip works.
However if is intercepted by an Effect , the tooltip breaks.
Any ideas on this ?

**Comment by vouill** [comment]
Ok i have narrowed the issue.

When i click on the tooltip source, i dispatch actions that change the state ( i am using ngrx)

Since the state has changed, angular rerender the component , and specifically the ngFor where the tooltip is included.

Since it's rerendered , clicking it again on it is like clicking on a new tooltip, explaining why new tooltips appear. 
And i guess along with that rerender, the initial displayed tooltip simply stays in the last known state.

Still digging it

**Comment by rubyboy** [comment]
@vouill it would be very helpful if you could create a component that reproduces this problem without external dependencies. For example, create a component that has an interval observable and shows a tooltip based on the info coming out of it. Once you have it reproduced, post it here and it may help whoever is trying to fix it look at the exact same use case and problem.

**Comment by henrique-rotava** [comment]
I am facing this same problem. It happens because when the angular destroys the component the event that should remove the tooltip is not being triggered.

**Comment by rubyboy** [comment]
@henrique-rotava thanks heaps for identifying the core issue. Would you like to submit a PR?

**Comment by rubyboy** [comment]
Sorry, just noticed that you did :)
Merging now.

**Comment by rubyboy** [comment]
https://github.com/InfomediaLtd/angular2-materialize/pull/52

**Comment by rubyboy** [comment]
https://github.com/InfomediaLtd/angular2-materialize/pull/52 was merged and a fix version (3.0.1) was released to npm: https://www.npmjs.com/package/angular2-materialize
@vouill @Chipintoza are you able to test and confirm this is now fixed with the new version?

@henrique-rotava thanks again for the fix. Much appreciated!

**Comment by vouill** [comment]
Awesome I confirm the fix !

**Comment by Chipintoza** [comment]
Sorry for late answer...
now all is well! thanks
