### ISSUE TITLE
Remove import "materialize" dependency

### ISSUE THREAD

**Issue by ArThoX** [InfomediaLtd/angular2-materialize#54]
Hi

I am using angular2-materialize along with meteor and poetic:materialize-scss package.
I do not use npm "materialize" package, so importing angular2-materialize would result in a dependency error.

My solution was to clone the repo and remove the `import "materialize"`, all works.
Here I am not sure why this import is necessary for this package. 

Can you please consider removing it ?

Regards

**Comment by rubyboy** [comment]
The reason "materialize" is imported is to ensure it is loaded before this directive. It uses some of its functions and this way the only required import is angular2-materialize in client projects.

But, I can see how it can be dealt with in another way, by importing materialize as a script. Would you like to create a different entry point that does not include this dependency? I'm happy to approve a PR that would export a separate bundle (index-independant.js).

**Comment by rubyboy** [comment]
@ArThoX another option is to alias materialize with poetic:materialize-scss. This way you won't need to import it separately and just let angular2-materialize import materialize, while it links to the repo you're using.

**Comment by rubyboy** [comment]
This has been implemented and released as a new breaking change for version 5.0.0
