### ISSUE TITLE
Script Error in index.ts

### ISSUE THREAD

**Issue by omrsmeh** [InfomediaLtd/angular2-materialize#56]
Hi,

I just try to use angular2-materialize with my latest project. I am very exciting to kick-start my project with angular2-seed and and angular2-materialize.

I setup my project and with angular2-seed and just add the angular2-materialize, and just stuck with an error:  

(index):75 Error: ReferenceError: Waves is not defined(…) "Report this error at https://github.com/mgechev/angular2-seed/issues"(anonymous function) @ (index):75ZoneDelegate.invoke @ zone.js?1467571370075:323Zone.run @ zone.js?1467571370075:216(anonymous function) @ zone.js?1467571370075:571ZoneDelegate.invokeTask @ zone.js?1467571370075:356Zone.runTask @ zone.js?1467571370075:256drainMicroTaskQueue @ zone.js?1467571370075:474ZoneTask.invoke @ zone.js?1467571370075:426

I debug the issue and found that file _"src/index.ts"_ have a declare statement i.e 

`
declare var Waves:any;
Waves.displayEffect();
`

This statement cause issue. As Waves declare with **_any_** so there is no method with name displayEffect() exists. 

So, Can you please create or remove these statement from final build.

**Comment by rubyboy** [comment]
@omrsmeh Waves is part of MaterializeCSS and should be global to the window. The error you're getting means you haven't configured your project to load MaterializeCSS JavaScript. Could you please confirm you load MaterializeCSS JavaScript bundle before using it in your project? This will ensure Waves exists and is working as expected.

**Comment by omrsmeh** [comment]
Thanks @rubyboy 
I have found the issue with my project, path for MaterializeCSS in my seed.config.ts was wrong.
Again thanks for your time

**Comment by rubyboy** [comment]
No worries. Thanks for getting back to me on this. Closing this one now.
