### ISSUE TITLE
Update bundle to RC4

### ISSUE THREAD

**Issue by pchristou** [InfomediaLtd/angular2-materialize#57]
Would be great if the bundle was upgraded to RC4 so users are able to take advantage of the updated Forms and new router functionality...

**Comment by rubyboy** [comment]
@pchristou thanks for the heads up.
Just to note that angular2-materialize doesn't use specific features that changed during newer RC releases. I assume you're referring to the demo app, that is still using RC1

Looking at the changes the major benefit is the new router. I think we'll wait for it to come out of beta, to avoid more breaking changes with each of its releases: https://github.com/angular/angular/blob/fe7de53b89ebe9e035197f15b43b45650cf44c50/modules/%40angular/router/CHANGELOG.md

**Comment by leNicDev** [comment]
@rubyboy I'm getting this error while using RC 4:
`No Directive annotation found on MaterializeDirective`

I imported it (`import {MaterializeDirective} from "angular2-materialize"`) and added it to the directives array.

**Comment by rubyboy** [comment]
@leNicDev are you using Ionic?
Just did a quick test of RC.4 on my machine and it looks well, but I'll only know once I full upgrade and use the new router, when it comes out of beta.

**Comment by leNicDev** [comment]
@rubyboy Seems like this error occurs if you're trying to import `angular2-materialize` before `zone.js`. But with making `angular2-materialize` the last import, I'm getting this error:
`Couldn't find materialize function ''material_select' on element or the global Materialize object.`.

**Comment by rubyboy** [comment]
@leNicDev Is it specific to RC4 or are you getting it for RC1 as well?

**Comment by rubyboy** [comment]
@leNicDev I think you're not bringing in materialize. Notice that Materialize needs to be imported before the directive (it's being used by it). What module loader system are you using?

**Comment by leNicDev** [comment]
@rubyboy I'm using Webpack and I'm getting the same error for RC1. I'm importing angular2-materialize in my boot.ts. After that I'm loading the stylesheet of Materialize in the template:
`<link href="../node_modules/materialize-css/dist/css/materialize.css" rel="stylesheet">`. If I'm requiring `materialize.js` before importing `angular2-materialize` the error still occurs.

**Comment by rubyboy** [comment]
Can you please create a separate issue. this is not related to this request to upgrade to RC4 and would confuse whoever is dealing with the upgrade.
Once created I have a few ideas on what to check, but I'll put that in the other issue, for other people coming in from webpack.
Thanks.
