### ISSUE TITLE
model/function binding

### ISSUE THREAD

**Issue by criticalbh** [InfomediaLtd/angular2-materialize#6]
I am trying to bind model or function to dropdown but I am still unsuccessful. This is what I have tried:
`<div class="input-field col s12">
    <select id="{{id}}" (change)="alert()" materialize="material_select">
        <option value="" disabled selected>Choose your option</option>
        <template ngFor #option [ngForOf]="options">
            <option value="{{option.value}}" *ngIf="option.selected" selected>{{ option.name }}</option>
            <option value="{{option.value}}" *ngIf="!option.selected">{{ option.name }}</option>
        </template>
    </select>
</div>`

But this is not working since this is later changed to list in dom. Can anyone show me how to bind model and function to particual example?

(edit) sorry, lately I have saw model is working but still I can not create on change event to work?

(edit nr2) one of the solution for tracking value changes is (ngModelChange) e.g.  `<select id="{{id}}" (ngModelChange)="alert()" materialize="material_select">`

**Comment by rubyboy** [comment]
@criticalbh have you found a way to get an ever for the change?
If not, I can look into this tomorrow.

**Comment by criticalbh** [comment]
Yes I have, I will fork this repo and contribute with some examples.

**Comment by rubyboy** [comment]
Awesome. Much appreciated!

On 11 Mar 2016, at 6:52 PM, criticalbh <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes I have, I will fork this repo and contribute with some examples.

-
