### ISSUE TITLE
Release v3.0.2 Error

### ISSUE THREAD

**Issue by lbertenasco** [InfomediaLtd/angular2-materialize#62]
node_modules folder for v 3.0.1
![angular2-materialize-3 0 1](https://cloud.githubusercontent.com/assets/2036780/16742147/cfc2c772-477c-11e6-9717-feea0508e3cb.png)

node_modules folder for v 3.0.2
![angular2-materialize-3 0 2](https://cloud.githubusercontent.com/assets/2036780/16742148/cfc3a2f0-477c-11e6-9b0c-ef12bb4b8047.png)

The file `custom-event-polyfill.ts` does not get parsed into .js and it causes this error:
`zone.js:101 GET http://localhost:4200/vendor/angular2-materialize/dist/custom-event-polyfill.js 404 (Not Found)`

**Comment by rubyboy** [comment]
@lbertenasco thanks for the quick find. A new release is on its way (3.0.2). Should be done within the next few minutes. Please let me know if it's fixed there.
