### ISSUE TITLE
HTML Element with 2 types of functions

### ISSUE THREAD

**Issue by miguelpinto98** [InfomediaLtd/angular2-materialize#65]
It's possible to combine two functions of "MaterializeDirectives" on one HTML element? 

eg:

``` HTML
<a materialize="tooltip" materialize="leanModal" data-position="bottom" 
data-delay="10" data-tooltip="Open Modal"  [materializeParams]="[{dismissible: true}]" 
href="#modal" class="secondary-content">Open Modal</a>

or
<a materialize="tooltip leanModal" data-position="bottom" data-delay="10" 
data-tooltip="Open Modal" [materializeParams]="[{dismissible: true}]" 
href="#modal" class="secondary-content">Open Modal</a>
```

**Comment by rubyboy** [comment]
Interesting idea. Not sure how the materializeParams would correspond to each of them, though.

How about you try the new materializeActions feature?
Here's the relevant piece from the README:
Another useful option is emitting actions on an element. You may want to do that for calling Materialize functions, like closing a modal dialog or triggering a toast. You can do that by setting the **materializeActions** attribute, which accepts an [EventEmitter](https://angular.io/docs/ts/latest/api/core/index/EventEmitter-class.html) :
```html
<div id="modal1" class="modal" materialize [materializeActions]="actions">
  <div class="modal-content">
    <h4>Modal Header</h4>
    <p>A bunch of text</p>
  </div>
  <div class="modal-footer">
    <a class="waves-effect waves-green btn-flat" (click)="closeModel()">Close</a>
  </div>
</div>
```
```js
  actions = new EventEmitter<string>();
  closeModel() {
    this.actions.emit("closeModal");
  }
```
