### ISSUE TITLE
How to close modal, use the callback method?

### ISSUE THREAD

**Issue by yrfandre** [InfomediaLtd/angular2-materialize#69]
How can I to show or close the modal, use the callback method?

**Comment by cristianurbano** [comment]
I have the same question ....   how to close or open the modal from the component? is it necesarry use jquery function? like ` $('#modal1').closeModal();` or do we have another option?

**Comment by rubyboy** [comment]
I've just added a new feature that lets you do that easily by setting the materializeActions attribute and emitting actions to it.

Here's the relevant excerpt from the updated README:
Another useful option is amitting actions on an element. You may want to do that for calling Materialize functions, like closing a modal dialog or triggering a toast. You can do that by setting the **materializeActions** attribute, which accepts an [EventEmitter](https://angular.io/docs/ts/latest/api/core/index/EventEmitter-class.html) :
```html
<div id="modal1" class="modal" materialize [materializeActions]="actions">
  <div class="modal-content">
    <h4>Modal Header</h4>
    <p>A bunch of text</p>
  </div>
  <div class="modal-footer">
    <a class="waves-effect waves-green btn-flat" (click)="closeModel()">Close</a>
  </div>
</div>
```
```js
  actions = new EventEmitter<string>();
  closeModel() {
    this.actions.emit("closeModal");
  }
```

**Comment by cristianurbano** [comment]
nice! thank you very much @rubyboy
