### ISSUE TITLE
How to initialize carousel and parallax

### ISSUE THREAD

**Issue by camarrone** [InfomediaLtd/angular2-materialize#71]
Hello,

How can I initialize carousel and parallax using angular2-materialize ?

Thanks for the help!

My best regards.

**Comment by camarrone** [comment]
Gotta read the docs better next time :-)

```
<div materialize="carousel" [materializeParams]="[{full_width: true}]" class="carousel carousel-slider center" data-indicators="true">
    <div class="carousel-fixed-item center">
        <a class="btn waves-effect white grey-text darken-text-2">button</a>
    </div>
    <div class="carousel-item red white-text" href="#one!">
        <h2>First Panel</h2>
        <p class="white-text">This is your first panel</p>
    </div>
    <div class="carousel-item amber white-text" href="#two!">
        <h2>Second Panel</h2>
        <p class="white-text">This is your second panel</p>
    </div>
    <div class="carousel-item green white-text" href="#three!">
        <h2>Third Panel</h2>
        <p class="white-text">This is your third panel</p>
    </div>
    <div class="carousel-item blue white-text" href="#four!">
        <h2>Fourth Panel</h2>
        <p class="white-text">This is your fourth panel</p>
    </div>
</div>
```

**Comment by ArturCzopek** [comment]
It works even without href attributes :)

**Comment by peruku** [comment]
Hi 
Can you point me on where the documentation available...

**Comment by rubyboy** [comment]
@peruku http://materializecss.com/carousel.html

**Comment by peruku** [comment]
Hi rubyboy,
Thanks for pointing for documentation. I was searching in 'github'.
Any idea on carousel autoplay (slide changes automatically  ) ?
 According to the documentation it should be on by default and slide change will happen on every 200 milliseconds. 

 
**duration :	Transition duration in milliseconds. (Default: 200)**

**Comment by rubyboy** [comment]
@peruku you can try searching or asking on the MaterlizeCSS repo: https://github.com/Dogfalo/materialize

**Comment by ohmpzz** [comment]
`[materializeParams]="[{full_width: true}]" `  to `[materializeParams]="[{fullWidth: true}]" `
