### ISSUE TITLE
Error on ZoneDelegate

### ISSUE THREAD

**Issue by alonzing** [InfomediaLtd/angular2-materialize#72]
Hi

When adding 
import {MaterializeDirective} from "angular2-materialize";

I got the following JS error and no components are rendered:

(index):26 Error: SyntaxError: Unexpected token <(…)
(anonymous function)	@	(index):26
ZoneDelegate.invoke	@	zone.js:323
Zone.run	@	zone.js:216
(anonymous function)	@	zone.js:571
ZoneDelegate.invokeTask	@	zone.js:356
Zone.runTask	@	zone.js:256
drainMicroTaskQueue	@	zone.js:474
ZoneTask.invoke	@	zone.js:426

Thanks.

**Comment by rubyboy** [comment]
I can only assume it's related to the setup of your project. Hard to know without more details.
Does the example app work for you when forking this repository?

**Comment by rubyboy** [comment]
No more details. Closing.
