### ISSUE TITLE
Problems with dynamic Tooltips and translate Directive

### ISSUE THREAD

**Issue by Aalphones** [InfomediaLtd/angular2-materialize#74]
Got an issue on using a tooltip in combination with the Translation pipe of
ng2-translate:  https://www.npmjs.com/package/ng2-translate

`
<a materialize="tooltip" routerLink="/dashboard" class="tooltipped" data-position="bottom" data-delay="50" [attr.data-tooltip]="'primary-nav.home' | translate">
                <img src="img/logo_large.png" class="responsive-img">
            </a>
`

Just gives me an empty tooltip but the data-tooltip is filled correctly with the translation as you can see at inspecting the Code afterwards. 

`
<a class="tooltipped" data-delay="50" data-position="bottom" materialize="tooltip" routerlink="/dashboard" ng-reflect-router-link="/dashboard" ng-reflect-materialize="tooltip" data-tooltip="Übersicht" ng-reflect-href="/dashboard" href="/dashboard" data-tooltip-id="19c075f7-a5fb-6c17-861f-3cdf26ca765a">
                <img class="responsive-img" src="img/logo_large.png">
            </a>
`

Is there any way to refresh the View after the attribute is filled in?

**Comment by rubyboy** [comment]
To refresh the view you can update the bound value of the [materializeParams]. So, for example do ```[materializeParams]="someProperty"```. When you assign a new array to the someProperty property of the class then it should kick off a refresh of the component Materialize behaviour

**Comment by rubyboy** [comment]
See more details and an example here: https://github.com/InfomediaLtd/angular2-materialize/issues/63#issuecomment-232092307

**Comment by Aalphones** [comment]
Still not working with this hack :/
Tried to load the text into an property and kick off the refresh by assigning a new array to the Property [materializeParams] is bound to in the callback function.
Results always the same. An empty tooltip altough the data-tooltip attribute is set correctly in the DOM.

The only thing that worked is to kick off the refresh manually (e.g. by clicking a button, that kicks off the refresh as you explained) but that cant be the solution...

**Comment by Aalphones** [comment]
Fixed it with your hack like this:

`
<a materialize="tooltip" routerLink="/dashboard" *ngIf="tooltips != null" materialize="tooltip" [materializeParams]="tooltips" class="tooltipped" data-position="bottom" data-delay="50" [attr.data-tooltip]="tooltips['home']">
               <img src="img/logo_large.png" class="responsive-img">
            </a>
`

the translations are loaded asynchronously in the constructor like this:

`
export class AppComponent {
    tooltips = null;

    constructor(translate: TranslateService) {
        // Render tooltips for primary Navigation
        translate.get('primary-nav').subscribe(data => {
            this.tooltips = [];
            this.tooltips['home'] = data.home;
        });
    }
`

Thanks for the Help!

**Comment by lengtche** [comment]
I wasn't able to get anyone's workarounds.

Fortunately, I was able to fix it by adding an `id` (in my case, `id="user-tooltip"`) to my `a` element, then using this jQuery.

`$('#' + $('#user-tooltip').attr('data-tooltip-id') + ' > span').html(YOUR_NEW_TEXT)`

**Comment by sergiobrr** [comment]
Try something like
`<a class="btn-floating btn-large waves-effect waves-light {{ configuration.secondary_color }}"
                (click)="toggleConfigMode()"
                *ngIf="config_mode"
                materialize="tooltip" 
                [attr.data-tooltip]="'TOOLTIPS.COMPAGNIA.INTERFACCIA_KO' | translate">
            <i class="material-icons">remove</i>
        </a>`
Worked for me like a charm
