### ISSUE TITLE
TOAST

### ISSUE THREAD

**Issue by moumoune** [InfomediaLtd/angular2-materialize#76]
Hi, How to do that with angular2-materialize :

```
Materialize.toast('I am a toast!', 4000);
```
How to get the Materialize object into my component ?

Thx.

**Comment by rubyboy** [comment]
Materialize is a global object that exists by importing angular2-materialize (it actually import materialize itself). So you can just call it whenever you want.
See the example here: ```https://github.com/InfomediaLtd/angular2-materialize/blob/master/app/components/dialogs.ts```

**Comment by moumoune** [comment]
Ok, it's work into the component too, but TypeScript don't recognize the object, that's why I thought there was a mistake.

thx, closed for me too.

**Comment by maxmumford** [comment]
Do you have an example triggering a toast from typescript instead of from within the template?

**Comment by maxmumford** [comment]
For other people wanting to trigger toasts from code, Materialize isn't accessible as a standard webpack / systemjs import, so the only way to achieve this (afaik) is to access the global Materialize object, like so:

```
import { Injectable } from '@angular/core';

declare var Materialize:any;

@Injectable()
export class ToastService {

  constructor() { }

  toast(text: string, duration: number = 3000, style: string = ""){
    Materialize.toast(text, duration, style);
  }

}
```

**Comment by sergiobrr** [comment]
@maxmumford 
Hello,
using your code i get the error 'Cannot read property 'toast' of undefined' like he cant get the Materialize object.

**Comment by DarkChopper** [comment]
@sergiobrr
you need to import MaterializeDirective and MaterializeAction and the solution of @maxmumford works fine.

import { MaterializeDirective, MaterializeAction } from 'angular2-materialize';
