### ISSUE TITLE
angular-cli@webpack

### ISSUE THREAD

**Issue by murac** [InfomediaLtd/angular2-materialize#77]
I'm trying to use this package with the new angular-cli@webpack branch and I am getting the error "cannot resolve 'materialize'". I tried npm i --save materialize and that fixed that error but still I get errors. (Waves is not defined). Could you add new directions for angular-cli@webpack? Looking at the current instructions for angular-cli I don't see any equivalent to the steps concerning adding vendors or mapping the packages. thanks!

**Comment by murac** [comment]
Update, I ended up running npm install --save angular2-material and materializecss  and then i believe i ran the @types/[pkg] for them. i couldnt get the import working beyond angular2-material so i ended up just adding the scripts and stylesheets in index and it works. I'm pretty sure the goal of angular-cli is to not have to do this. I'll keep an eye out on their documentation to see if a proper solution is developed for 3rd party apps.

**Comment by rubyboy** [comment]
Just to confirm, did you follow the instructions in the README and they didn't work? https://github.com/InfomediaLtd/angular2-materialize#installing--configuring-angular2-materialize-in-projects-created-with-angular-cli

If it doesn't, in the next round of updates to the latest angular version I'll take a look to confirm it works with the CLI.
@hendrik91 may also be able to help if the instructions are not compatible to the latest CLI.

**Comment by murac** [comment]
Yes I followed the instructions best I could however angular-cli@webpack does not have "angular-cli-build.js" nor "system-config.ts" and it's my understanding that webpack should be handling the loading of these libraries without the need for adding <script> and <link> tags in index.html. So ultimately what I did was include all the scripts and styles in index.html. They have mentioned they're working on support for global styles and I assume the same goes for 3rd party libraries. So I'll wait and see. I admit though, something feels wrong about using jQuery in my components but that wave effect is just too damn sexy.

**Comment by FoodBuster** [comment]
@murac I have the same problem. Can you please copy the code you added to index.html? I've tried including scripts for materialize-css and angular2-materialize, but I'm still getting the unresolved package error.

**Comment by murac** [comment]
sure, this is my <head> https://gist.github.com/murac/2b3d13852934740a38dfdf280812a017
then I declare var jQuery when I need to make calls on the elements.
import {MaterializeDirective} from "angular2-materialize"; seemed to work for me in app.component.ts. What errors are you getting? also don't forget to add the materialize="component" to the html

**Comment by FoodBuster** [comment]
I got it. Thanks a lot for the help. I was having the same "cannot resolve 'materialize'" error up top and didn't notice the materialize package you mentioned was separate from materialize-css (I know, amateur mistake on my part). Your link also helped me clean up my materialize scripts.

**Comment by nurkkala** [comment]
@murac, does your workaround of adding `link` and `script` tags to `index.html` simply retrieve the components from your server, or do they result in some kind of webpack magic that adds the materialize components being added to a bundle? Thanks.

**Comment by murac** [comment]
I'm using angular-cli@webpack so I just drop the files in the public/js  or css folder and the relative paths work.

**Comment by pchristou** [comment]
@murac do dialogs or 'toast' functionality work for you? For instance, `Materialize.toast('Selection ignored, please select just one option', 1000);` 

I have the same setup as you i.e. angular-cli webpack and am linking to jQuery and materialize js/css files locally. Unfortunately, I'm running into issues which I think may be similar to #20 and #48...

**Comment by nurkkala** [comment]
Do you also include `jQuery` in your `package.json` file? When I have both the explicit reference from `index.html` to the `public` directory _and_ one in `package.json`, it seems like some behaviors in Materialize are wrong.

For example, the indicator bar under tabs don't work properly and even appear to be inserted multiple times in the DOM as if `jQuery` was running twice. However, when I remove `jQuery` from `package.json`, I get an error from webpack about not being able to find `jQuery` from `node_modules/materialize-css/bin/materialize.js`.

Any suggestions?

**Comment by rubyboy** [comment]
Try the new version (5.0.0). It has a breaking change of removing the dependency on materialize-css. This library will need to be imported separately. Hopefully that will make it easier to control how this library is imported.

**Comment by rubyboy** [comment]
Closing this issue. The library now fully supports https://github.com/angular/angular-cli
