### ISSUE TITLE
Materialize import breaks webpack (angular-cli)

### ISSUE THREAD

**Issue by Sixthdim** [InfomediaLtd/angular2-materialize#82]
I'm curious as to why the `materialize-css` package is installed as `materialize`.
Here: https://github.com/InfomediaLtd/angular2-materialize/blob/master/package.json#L99

This causes an error with Webpack:
````
ERROR in ./~/angular2-materialize/dist/index.js                                                                                                                                                                                      
Module not found: Error: Can't resolve 'materialize' in '.../node_modules/angular2-materialize/dist'                                                                               
 @ ./~/angular2-materialize/dist/index.js 2:0-22
````

The only way to get this to work is to create an alias in the build process (webpack, systemjs, etc.), but this is currently not available with the latest angular-cli, and also seems a little unnecessary.

Are you able to install the `materialize-css` package as is, and then just import "materialize-css" here: https://github.com/InfomediaLtd/angular2-materialize/blob/master/src/index.ts#L1

Thanks!

**Comment by MarkusPint** [comment]
@rubyboy Are you accepting PR-s?

**Comment by rubyboy** [comment]
@Sixthdim thanks for the feedback. You can find more details in a similar issue here: https://github.com/InfomediaLtd/angular2-materialize/issues/54

@MarkusPint most definitely! See my comments in https://github.com/InfomediaLtd/angular2-materialize/issues/54. Maybe two deployment targets, one with and one without materialize-css, would be a good option. This way if someone wants to just import angular-materialize and let it bring all required dependencies (it does need materialize-css) they would use the current deployment. Then, create another entry point without that dependency for other people who want to bring it materialize-css any other way they want.

Thanks for offering to contribute.

**Comment by pchristou** [comment]
This is affecting me too. I'm still not clear on why this affects angular-cli webpack and not the standard seed project? Is there a workaround we can use for the moment to get around this issue?

**Comment by Sixthdim** [comment]
@pchristou This mainly affects angular-cli@webpack because it doesn't (yet) support a webpack config file, so there is no way to setup an alias for "materialize" -> "materialize-css", and "materialize" doesn't exist in node_modules. The way it's setup in this project only works with JSPM. I'll see if I can get a PR up today.

**Comment by pchristou** [comment]
Thanks for the explanation @Sixthdim.

**Comment by Sixthdim** [comment]
PR Created: https://github.com/InfomediaLtd/angular2-materialize/pull/84

**Comment by rubyboy** [comment]
OK, PR merged and a new version has been released to npm. I haven't tested it, so please give it a whirl and I hope it will work.
Thanks @Sixthdim for picking this issue up and contributing!

**Comment by pchristou** [comment]
@rubyboy @Sixthdim Thank you both for your work. I recreated a project, imported the MaterializeDirective and that change seems to have done the trick..
