### ISSUE TITLE
Not working with multiple NgModules

### ISSUE THREAD

**Issue by juanpmarin-infocorp** [InfomediaLtd/angular2-materialize#83]
When I try to use the directive in several application modules does not work, throw this error

> Type MaterializeDirective is part of the declarations of 2 modules

Thank you

**Comment by 7Kronos** [comment]
What Angular 2 version are you using ?

**Comment by juanpmarin-infocorp** [comment]
2.0.0-rc.5

**Comment by juanpmarin-infocorp** [comment]
Any update ? D:

**Comment by rubyboy** [comment]
@juanpmarin-infocorp are you able to confirm if this works now with the latest version of angular2-materialize? Thanks.

**Comment by juanpmarin-infocorp** [comment]
It works :D

**Comment by bigggge** [comment]
I upgrade to v6.3.0 and angular 2.3.0 but still give me a error
```
Error: Type MaterializeDirective is part of the declarations of 2 modules: MaterializeModule and AppModule! Please consider moving MaterializeDirective to a higher module that imports MaterializeModule and AppModule. You can also create a new NgModule that exports and includes MaterializeDirective then import that NgModule in MaterializeModule and AppModule.
```

**Comment by rubyboy** [comment]
@bigggge 
https://github.com/InfomediaLtd/angular2-materialize/issues/98#issuecomment-245442536
https://angular.io/docs/ts/latest/guide/ngmodule.html#!#shared-module
