### ISSUE TITLE
velocity function issue

### ISSUE THREAD

**Issue by chandumunna** [InfomediaLtd/angular2-materialize#88]
i updated to the latest version of angular2 materialize but when use $ functions it getting the .velocity function issue...
for example....
$('.materialboxed').materialbox();

**Comment by rubyboy** [comment]
@chandumunna thanks for reporting this issue.
There's a few existing bugs on this and info on where it comes from (no fix yet, though).
Can you please add your details to the existing bugs and close this one?
Thanks.

**Comment by chandumunna** [comment]
html page -->
<img class="materialboxed" width="650" src="imgs/about-us.gif">

ts page-->
import { Component, OnInit, AfterViewInit } from '@angular/core';
declare var $:any;
declare var Materialize:any;
import {MaterializeDirective} from "angular2-materialize";
@Component({
  selector: 'app-home',
  directives:[MaterializeDirective],
  templateUrl: 'home.component.html',
  styleUrls: ['home.component.css']
})
export class HomeComponent implements AfterViewInit {

  constructor() { }
  ngAfterViewInit(){
    $('.materialboxed').materialbox();
  }

}

**Comment by chandumunna** [comment]
Need urgency any one help me 
thanks in advance...

**Comment by rubyboy** [comment]
Sorry, I won't be able to look into it for the next couple of weeks. If you happen to check it yourself and figure it out PR's are welcome. Thanks.

Please close duplicate issues, to help maintain a clear list of issues. Cheers.

**Comment by rubyboy** [comment]
Solve with the latest version of angular2-materialize. Notice that the setup process is different and materialize-css needs to be imported separately.
See working example here: https://github.com/InfomediaLtd/angular2-webpack-starter
