### ISSUE TITLE
Couldn't find Materialize object on window

### ISSUE THREAD

**Issue by dazziola** [InfomediaLtd/angular2-materialize#90]
I've installed angular2-materialize as per the read me, but I'm getting an error regarding the Materialize object.

`Couldn't find Materialize object on window. It is created by the materialize-css library. Please import materialize-css before importing angular2-materialize.`

Anyone run into this before?

**Comment by numerick** [comment]
The materialize js file is missing.

In your index.html:
`<script type="text/javascript" src="vendor/materialize-css/dist/js/materialize.min.js"></script>`

**Comment by rubyboy** [comment]
@numerick thanks heaps for picking this one up. I'll close this issue now.
If any of you two think the documentation is lacking I'd love for a PR to fix what's missing. Cheers.

**Comment by rafaelzuckerberg** [comment]
Well, in may case, I close Atom IDE and restart the server (ng serve) again and working to me, I do not know why....

**Comment by faisal-web** [comment]
GET http://localhost:4200/node_modules/materialize-css/dist/css/materialize.css 
localhost/:12 GET http://localhost:4200/node_modules/jquery/dist/jquery.js 
localhost/:13 GET http://localhost:4200/node_modules/hammerjs/hammer.js 
localhost/:14 GET http://localhost:4200/node_modules/materialize-css/dist/js/materialize.js 

index.js:4 Uncaught Error: Couldn't find Materialize object on window. It is created by the materialize-css library. Please import materialize-css before importing angular2-materialize.
    at Object.../../../../angular2-materialize/dist/index.js (index.js:4)
    at __webpack_require__ (bootstrap 0890751…:54)
    at Object.../../../../../src/app/app.module.ts (app.component.ts:8)
    at __webpack_require__ (bootstrap 0890751…:54)
    at Object.../../../../../src/main.ts (environment.ts:8)
    at __webpack_require__ (bootstrap 0890751…:54)
    at Object.2 (main.ts:11)
    at __webpack_require__ (bootstrap 0890751…:54)
    at webpackJsonpCallback (bootstrap 0890751…:25)
    at main.bundle.js:1

any one resolve the issue?

**Comment by djamajo** [comment]
restart the web server

**Comment by Hamelina** [comment]
I have the same problem as you faisal-web ! 

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (materialize.min.js, line 0)
[Error] Did not load script at 'http://localhost:4200/vendor/materialize-css/dist/js/materialize.min.js' because non script MIME types are not allowed when 'X-Content-Type: nosniff' is given.
[Error] Error: Couldn't find Materialize object on window. It is created by the materialize-css library. Please import materialize-css before importing angular2-materialize.
	./node_modules/angular2-materialize/dist/index.js (vendor.bundle.js:94111:183)
	__webpack_require__ (inline.bundle.js:55)
	./src/app/app.module.ts (main.bundle.js:121)
	__webpack_require__ (inline.bundle.js:55)
	./src/main.ts (main.bundle.js:1756)
	__webpack_require__ (inline.bundle.js:55)
	(fonction anonyme) (main.bundle.js:1770)
	__webpack_require__ (inline.bundle.js:55)
	webpackJsonpCallback (inline.bundle.js:26)
	Code général (main.bundle.js:1)

Any on can help me ?

**Comment by ghost** [comment]
Estoy instalando materialize y me da este error
Uncaught Error: Couldn't find Materialize object on window. It is created by the materialize-css library. Please import materialize-css before importing angular2-materialize.
    at eval (webpack-internal:///./node_modules/angular2-materialize/dist/index.js:10)

**Comment by ghost** [comment]
Este es mi angular cli
 "styles": [
        "../node_modules/materialize-css/dist/css/materialize.css",
        "../node_modules/materialize-css/dist/css/materialize.min.css",
        "styles.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/hammerjs/hammer.js",
        "../node_modules/materialize-css/dist/js/materialize.js",
        "../node_modules/materialize-css/dist/js/materialize.min.js"

**Comment by davidpestana** [comment]
TRY IT 

            "styles": [
              "src/styles.css",
              "./node_modules/materialize-css/dist/css/materialize.css"
            ],
            "scripts": [
              "./node_modules/jquery/dist/jquery.js",
              "./node_modules/hammerjs/hammer.js",
              "./node_modules/materialize-css/dist/js/materialize.js"
            ]


warning for relative route...
and in your angular.json file ... put it in "build" zone...   its possible get a mistake put in "test" zone.

**Comment by eduardodataa** [comment]
TRY IT

In app.module.css: Remove the **MaterializeModule** in Imports. Remove **import { MaterializeModule } from 'angular2-materialize';**

**Comment by ghost** [comment]
Hello thanks 
I fix

**Comment by lucas-ssgomes** [comment]
> TRY IT
> 
> In app.module.css: Remove the **MaterializeModule** in Imports. Remove **import { MaterializeModule } from 'angular2-materialize';**

I had the same problem and this worked, thanks.

**Comment by wasHereD** [comment]
![image](https://user-images.githubusercontent.com/26344886/52772670-fd6f3d00-3030-11e9-8c95-3da356cb58f9.png)
i used materialize-css v0.100.2 and worked fine

**Comment by GnRSlash** [comment]
> TRY IT
> 
> In app.module.css: Remove the **MaterializeModule** in Imports. Remove **import { MaterializeModule } from 'angular2-materialize';**

Wolud you mind to tell why? Because angular2-materialize wizard tells to put it.....
