### ISSUE TITLE
System.js setup is not working

### ISSUE THREAD

**Issue by golechwierowicz** [InfomediaLtd/angular2-materialize#91]
The system js config in README is not working for me. (I had 404 on getting angular2-materialize.js) so I fixed it to following

```
    map['materialize-css'] = "node_modules/materialize-css";
    packages['materialize-css'] = { main: 'dist/js/materialize'};
    map['angular2-materialize'] = "node_modules/angular2-materialize";
    packages['angular2-materialize'] = { main: 'dist/index'};

    System.config({
        defaultJSExtensions: true,
        map: map,
        packages: packages
    });
```

but now I get a warning

> Velocity is already loaded. You may be needlessly importing Velocity again; note that Materialize includes Velocity.

and an error:

> zone.min.js:1 Error: (SystemJS) Error: Multiple anonymous defines in module http://localhost:1111/path/to/node/modules/materialize-css/dist/js/materialize.js(…)

What is the correct system js setup?

**Comment by golechwierowicz** [comment]
I fixed this. It seems that you only have to provide 

`import "angular2-materialize"`

in root component/module file. Without plain materialize

**Comment by camarrone** [comment]
@golechwierowicz Could you please provide your systemjs.config.js? I'm still trying to resolve this one. When I don't get the error that I you mentioned, I get an "unexpected token <" error msg.

Thanks very much.

**Comment by camarrone** [comment]
@golechwierowicz Never mind... got it fixed :-)

Here goes my systemjs.config.js along with my app.module.ts and main.ts:

Cheers!

systemjs.config.js

`/**
 * System configuration for Angular 2 samples
 * Adjust as necessary for your application needs.
 */
(function(global) {

  // map tells the System loader where to look for things
  var map = {
    'app':                        'app', // 'dist',

    '@angular':                   './lib/@angular',
    'rxjs':                       './lib/rxjs',

    "materialize-css": "./lib/materialize-css",
    'angular2-materialize': './lib/angular2-materialize'
  };

  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    'app'              : { main: 'main.js',  defaultExtension: 'js' },
    'rxjs'             : { defaultExtension: 'js' },

    'materialize-css': { main: 'js/materialize' },
    'angular2-materialize' : { main: 'dist/index', defaultExtension: 'js' }
  };

  var ngPackageNames = [
    'common',
    'compiler',
    'core',
    'forms',
    'http',
    'platform-browser',
    'platform-browser-dynamic',
    'router',
    'router-deprecated',
    'upgrade',
  ];

  // Individual files (~300 requests):
  function packIndex(pkgName) {
    packages['@angular/'+pkgName] = { main: 'index.js', defaultExtension: 'js' };
  }

  // Bundled (~40 requests):
  function packUmd(pkgName) {
    packages['@angular/'+pkgName] = { main: '/bundles/' + pkgName + '.umd.js', defaultExtension: 'js' };
  }

  // Most environments should use UMD; some (Karma) need the individual index files
  var setPackageConfig = System.packageWithIndex ? packIndex : packUmd;

  // Add package entries for angular packages
  ngPackageNames.forEach(setPackageConfig);

  // No umd for router yet
  packages['@angular/router'] = { main: 'index.js', defaultExtension: 'js' };

  var config = {
    map: map,
    packages: packages
  };

  System.config(config);

})(this);
`

**main.ts**

`
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app.module';

platformBrowserDynamic().bootstrapModule(AppModule);
`

**app.module.ts**

`
import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import {MaterializeDirective} from "angular2-materialize";

import { AppComponent }  from './app.component';

@NgModule({
  imports: [
    BrowserModule,
  ],
  declarations: [
    MaterializeDirective,
    AppComponent
  ],
  providers: [   ],
  bootstrap: [ AppComponent ]
})
export class AppModule { }
 `

**Comment by leonardobazico** [comment]
Somebody using MaterializeDirective in more than one module?

```error
zone.js:461 Unhandled Promise rejection: Error: Type MaterializeDirective is part of the declarations of 2 modules: ClientModule and AppModule!
```

**Comment by camarrone** [comment]
@leonardobazico check your AppModule. In my case I was using FormsModule in the AppModule and also in another module. Got the same issue with HttpModule.

**Comment by leonardobazico** [comment]
@camarrone, thanks!
I did a SharedModule with directives and modules that I use in whole application.
I follow this documentation page: https://angular.io/docs/ts/latest/guide/ngmodule.html#!#shared-module

**Comment by camarrone** [comment]
@leonardobazico Try not Importing  your SharedModule in your AppModule. Import it only where you are gonna use it. I was doing the same mistake with the HttpModule and FormsModule. I removed them from the AppModule and imported it only in my modules where I need them.

This is my AppModule:

```
import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import {MaterializeDirective} from "angular2-materialize";

import { HomeComponent } from './home/home.component';

import { AppComponent }  from './app.component';
import { RegisterModule } from './register/register.module';
import { LoginModule } from './login/login.module';
import { DashboardComponent } from './dashboard/dashboard.component';
import { DashboardDetailComponent } from './dashboard/dashboard.detail.component';

import { routing } from './app.routing';

@NgModule({
  imports: [
    BrowserModule,
    RegisterModule,
    LoginModule,
    routing
  ],
  declarations: [
    MaterializeDirective,
    AppComponent,
    HomeComponent,
    DashboardComponent,
    DashboardDetailComponent,
  ],
  providers: [  ],
  bootstrap: [ AppComponent ]
})
export class AppModule { }
```

And here goes my LoginModule

```
import { NgModule }      from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { LoginComponent } from './login.component';
import { AuthService } from './auth.service';
import { AuthGuard } from './auth-guard.service';

import { loginRoutes } from './login.routing';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    HttpModule,
    loginRoutes
  ],
  declarations: [
    LoginComponent
  ],
  providers: [
    AuthService,
    AuthGuard
  ]
})

export class LoginModule {}
```

**Comment by leonardobazico** [comment]
@camarrone, well done! This works for me!

**Comment by rubyboy** [comment]
I'd like to close this issue. Any objections from anyone?
