### ISSUE TITLE
Demo addition: autocomplete?

### ISSUE THREAD

**Issue by pchristou** [InfomediaLtd/angular2-materialize#92]
Hi, version v0.97.7 of materialize has an autocomplete form component but examples are rather lacklustre. Has anyone incorporated this alongside ng2? 

I'm sure it'd be a great help to many if an example could be added to the demo: http://angular2-materialize.surge.sh/#/forms

**Comment by rubyboy** [comment]
Maybe @ziracmo can help here, given this issue: https://github.com/InfomediaLtd/angular2-materialize/issues/79

@pchristou , if you have an example with pure materialize-css I'd be happy to try it out with angular2-materialize and add to the demo

**Comment by maxmumford** [comment]
For those looking for a simple code example:

```
<input type="text" materialize="autocomplete" [materializeParams]="[{'data': {'apple': null, 'google': null}}]">
```

**Comment by AAAnderson7301** [comment]
@maxmumford  When I use your example and bind to model [(ngModel)] It only binds the first 2 or 3 characters.

**Comment by maxmumford** [comment]
Yeah there's a data binding bug that means the ng2 model isn't updated. As far as I remember it's related to the materializecss select box not triggering the "change" event. It's been fixed, we're now waiting for a release to be created on the materializecss repo, and then here too.

**Comment by bernhardwaidacher** [comment]
Any news here? :)

**Comment by AAAnderson7301** [comment]
@maxmumford  How would you use data from a component ? ```[{'data': {{locations}}}]```

**Comment by maxmumford** [comment]
@AAAnderson7301 just pass your data map into the materializeParams attribute, for example:

in your component:

```
locations: any;
ngOnInit(){
    this.locations = {'apple': null, 'google': null};
}
```

In your template:

```
<input type="text" materialize="autocomplete" [materializeParams]="[{'data': locations}]">
```

The second (optional) parameter in the data map can be an image URL to show icons in the dropdown.

**Comment by AAAnderson7301** [comment]
@maxmumford  Thank you. I found the issue. locations is dynamic based on the user selection in the form. I am subscribing to changes and building the locations array based on those changes. This does not seem to work for that. If I hard code the data it does work...

**Comment by maxmumford** [comment]
No worries. I seem to remember reading somewhere that modifying an array does not trigger angular2 change detection because it's a referenced based variable... perhaps if you clone the entire array each time you add or remove an element it'll detect it. Otherwise there's probably a way to manually trigger ng2 change detection.

**Comment by AAAnderson7301** [comment]
@maxmumford  I was able to get it working. I for to add null to every item I added to the object 
```
    filterList(locations:any) {
        this.locations = {}
        for (var i = 0; i < locations.length; i ++){
            this.locations[locations[i].Location] = null;
        }
    }
```

**Comment by rubyboy** [comment]
I've added the simple example provided by @maxmumford to http://angular2-materialize.surge.sh/#/Forms . Thanks for that.

**Comment by akrepon** [comment]
@AAAnderson7301  I am struggeling to dynamically load the autocomplete data. I thought that updating the data would trigger a change and thus update the list. But i doesn't seem to work. I see you have managed to do it. 

Can you tell me how you did it and which version of materializecss and angular2-materialize you are using?

Thanks.

**Comment by rubyboy** [comment]
https://infomedialtd.github.io/angular2-materialize/#/Forms
