### ISSUE TITLE
Checkbox and radiobuttons page jump on change

### ISSUE THREAD

**Issue by joomi** [InfomediaLtd/angular2-materialize#95]
Hi 
I'm using the RC4 version and I encounter an issue with selecting checkboxes or radio buttons 
The window jumps to the top of the page (like clicking on encore)

**Comment by Jonibigoud** [comment]
Hi,
is an implementation of radio and checkboxes planned?

**Comment by rubyboy** [comment]
@Jonibigoud both checkboxes and radio buttons are supported. You can view an example on the demo page: http://angular2-materialize.surge.sh/#/Forms and in the sample code: https://github.com/InfomediaLtd/angular2-materialize/blob/master/app/components/forms.ts#L79
