### ISSUE TITLE
RC6 AOT

### ISSUE THREAD

**Issue by AAAnderson7301** [InfomediaLtd/angular2-materialize#97]
Hello, 

I am getting the following error with Angular2 RC6 using AOT compiler. (Error: Unexpected value 'MaterializeDirective' declared by the module 'AppModule'). My App Module looks like this. 
import {MaterializeDirective} from "angular2-materialize";

declarations 
materializeDirective

Should I be using the Module import instead? I tried it and got errors. Was curious because I do not see this import referenced in the documentation.

**Comment by vesteraas** [comment]
I'm experiencing the same, using Angular 2.0.1.  What was the solution?

**Comment by rubyboy** [comment]
CC @bitbeter @ https://github.com/InfomediaLtd/angular2-materialize/issues/121
