### ISSUE TITLE
[Resolved] How use MaterializeDirective in more than one module?

### ISSUE THREAD

**Issue by leonardobazico** [InfomediaLtd/angular2-materialize#98]
I need use the MaterializeDirective in multiple modules. But Angular throws a error.
[NgModule documentation](https://angular.io/docs/ts/latest/guide/ngmodule.html) says for don't use same directive in multiple modules, but I don't see other solution. 

`zone.js:461 Unhandled Promise rejection: Error: Type MaterializeDirective is part of the declarations of 2 modules: ClientModule and AppModule!`

**Comment by leonardobazico** [comment]
The solution was make a SharedModule with directives and modules that I use in whole application.
I followed the documentation page: https://angular.io/docs/ts/latest/guide/ngmodule.html#!#shared-module

**Comment by AAAnderson7301** [comment]
@leonardobazico  What version of Angular are you using?

**Comment by leonardobazico** [comment]
@AAAnderson7301, Angular 2 RC5. But I found a solution.

**Comment by rikdc** [comment]
Seconding @leonardobazico, a shared module is how I've also managed to get this to work and seems to be what the developers of Angular2 recommend.

```typescript
import { NgModule }            from '@angular/core';
import { CommonModule }        from '@angular/common';
import { FormsModule }         from '@angular/forms';
import { MaterializeDirective } from "angular2-materialize";

@NgModule({
  imports: [ CommonModule ],
  declarations: [ MaterializeDirective ],
  exports:      [ MaterializeDirective ]
})
export class SharedModule { }
```

**Comment by rubyboy** [comment]
Thanks @rikdc and @leonardobazico for the info and provided solution.
